### ISSUE TITLE
Segmentation fault SIGSEGV on first backup

### ISSUE THREAD

**Issue by rohitrav33ndran** [pgbackrest/pgbackrest#1447] opened 2021-07-01 12:44 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: `2.34`

2. PostgreSQL version: `11.3`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
          `OS - Ubuntu x86_64 GNU/Linux`
          `Database - TimescaleDB (1.7.3)/PostgreSQL Version(11.3)`

          Running on AWS t3.medium where the database is also hosted and backup storage as remote S3. 
          RAM: 4GB
          vCPUs: 2

4. Did you install pgBackRest from source or from a package? `Installed pgbackrest from package. `

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    
        [pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/6747971/pgbackrest.txt)

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
         
        [postgresql.conf.settings.txt](https://github.com/pgbackrest/pgbackrest/files/6747976/postgresql.conf.settings.txt)

    - errors in the postgresql log file before or during the time you experienced the issue
      `No errors observed in postgresql logs.`
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
      
       [dev-backup.log.txt](https://github.com/pgbackrest/pgbackrest/files/6748117/dev-backup.log.txt)

7. Describe the issue:

**Segmentation fault on first full backup.**  
```
2021-07-01 12:00:48.278 P00   INFO: backup command begin 2.34: --buffer-size=32768 --exec-id=11432-4d69f4c4 --log-level-console=info --log-level-file=trace --pg1-database=pipeline --pg1-path=/timescale-data --pg1-port=5432 --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/dev --repo1-retention-full=4 --repo1-s3-bucket=envio-timescaledb-backup --repo1-s3-endpoint=s3.eu-central-1.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=eu-central-1 --repo1-type=s3 --stanza=dev --start-fast
WARN: no prior backup exists, incr backup has been changed to full
2021-07-01 12:00:49.034 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2021-07-01 12:00:52.641 P00   INFO: backup start archive = 00000001000030BF000000B9, lsn = 30BF/B9000190
Segmentation fault (core dumped)

Core was generated by `pgbackrest --stanza=dev --log-level-console=info backup'.
Program terminated with signal SIGSEGV, Segmentation fault.
```
The pgbackrest check returned no problems. 

```
2021-07-01 12:04:51.603 P00   INFO: check command begin 2.34: --buffer-size=32768 --exec-id=11839-2f952bd9 --log-level-console=info --pg1-database=pipeline --pg1-path=/timescale-data --pg1-port=5432 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/dev --repo1-s3-bucket=envio-timescaledb-backup --repo1-s3-endpoint=s3.eu-central-1.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=eu-central-1 --repo1-type=s3 --stanza=dev
2021-07-01 12:04:52.207 P00   INFO: check repo1 configuration (primary)
2021-07-01 12:04:52.461 P00   INFO: check repo1 archive for WAL (primary)
2021-07-01 12:04:53.243 P00   INFO: WAL segment 00000001000030BF000000D4 successfully archived to '/dev/archive/dev/11-1/00000001000030BF/00000001000030BF000000D4-1dea135a931a22321eb7b70a4e336cb611da335.gz' on repo1
2021-07-01 12:04:53.243 P00   INFO: check command end: completed successfully (1641ms)
```

**Comment by rohitrav33ndran** [comment] 2021-07-01 12:46
This worked for me on a larger server with 16GB of memory with identical configuration.

**Comment by dwsteele** [comment] 2021-07-01 15:07
Ah, I see you attached a log with trace level. What's this:

`/timescale-data/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/pg_wal/00000001000030C000000016`

Seems like you might have some link issues here?

**Comment by rohitrav33ndran** [comment] 2021-07-01 15:16
I have no idea why the pg_wal/ keeps adding to the path. It doesn't start with the same path. catchsegv log attached.

It initially starts with this.

```
2021-07-01 11:48:23.881 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-data/pg_wal"}, level: 4, param.followLink: false)
2021-07-01 11:48:23.881 P00  TRACE:         storage/posix/storage::storagePosixInfo: => {StorageInfo}
2021-07-01 11:48:23.881 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-data/pg_wal/00000001000030C000000031"}, level: 4, param.followLink: false)

Something happens


2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-data/pg_wal/00000001000030BF00000098"}, level: 4, param.followLink: false)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: => {StorageInfo}
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfoList: => true
2021-07-01 11:48:23.895 P00  TRACE:         storage/storage::storageInfo: (this: {type: posix, path: {"/timescale-data"}, write: false}, fileExp: {"/timescale-wal/pg_wal"}, param.level: 0, param.ignoreMissing: true, param.followLink: false, param.noPathEnforce: true)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-wal/pg_wal"}, level: 4, param.followLink: false)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: => {StorageInfo}
2021-07-01 11:48:23.895 P00  TRACE:         storage/storage::storageInfo: => {StorageInfo}
2021-07-01 11:48:23.895 P00  TRACE:         storage/storage::storageInfo: (this: {type: posix, path: {"/timescale-data"}, write: false}, fileExp: {"/timescale-data/pg_wal/pg_wal"}, param.level: 0, param.ignoreMissing: true, param.followLink: true, param.noPathEnforce: false)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-data/pg_wal/pg_wal"}, level: 4, param.followLink: true)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: => {StorageInfo}
2021-07-01 11:48:23.895 P00  TRACE:         storage/storage::storageInfo: => {StorageInfo}
2021-07-01 11:48:23.895 P00  TRACE:         storage/storage::storageInfoList: (this: {type: posix, path: {"/timescale-data"}, write: false}, pathExp: {"/timescale-data/pg_wal/pg_wal"}, callback: (function *), callbackData: *void, param.level: 0, param.errorOnMissing: false, param.sortOrder: 1, param.expression: null, param.recurse: false)
2021-07-01 11:48:23.895 P00  TRACE:         storage/storage::storageInfoListSort: (this: {type: posix, path: {"/timescale-data"}, write: false}, path: {"/timescale-data/pg_wal/pg_wal"}, level: 4, expression: null, sortOrder: 1, callback: (function *), callbackData: *void)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfoList: (this: {StoragePosix *}, path: {"/timescale-data/pg_wal/pg_wal"}, level: 4, callback: (function *), callbackData: *void)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-data/pg_wal/pg_wal"}, level: 4, param.followLink: false)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: => {StorageInfo}
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-data/pg_wal/pg_wal/00000001000030C000000031"}, level: 4, param.followLink: false)
2021-07-01 11:48:23.895 P00  TRACE:         storage/posix/storage::storagePosixInfo: => {StorageInfo}
2021-07-01 11:48:23.896 P00  TRACE:         storage/posix/storage::storagePosixInfo: (this: {StoragePosix *}, file: {"/timescale-data/pg_wal/pg_wal/00000001000030BF000000E1"}, level: 4, param.followLink: false)
```


[catchsegv.txt](https://github.com/pgbackrest/pgbackrest/files/6749187/catchsegv.txt)

**Comment by dwsteele** [comment] 2021-07-01 15:47
Sure looks like `/timescale-data/pg_wal/pg_wal` is a symlink to `/timescale-data/pg_wal` or something like that. You should be able to resolve the issue by removing the erroneous symlink.

Still, not sure why we are not catching it and throwing an error. Can you verify this is the case and we'll see why we are not catching it?

**Comment by rohitrav33ndran** [comment] 2021-07-01 16:01
Its actually a symbolic link to the wal directory. 

so we have 2 different directories /timescale-data and /timescale-wal.   
lrwxrwxrwx 1 postgres postgres 21 May 22  2019 timescale-data/pg_wal -> /timescale-wal/pg_wal

The log says timescale-data/pg_wal and timescale-data/pg_wal/pg_wal. I can't find something like this coz the link is set to pg_wal within timescale-wal and not timescale-data.

**Comment by rohitrav33ndran** [comment] 2021-07-05 08:31
@dwsteele The documentation says that it is allowed to have the pg_wal on a separate volume.

> It is advantageous if the log is located on a different disk from the main database files. This can be achieved by moving the pg_wal directory to another location (while the server is shut down, of course) and creating a symbolic link from the original location in the main data directory to the new location.

So this is reproducable. I have tried this on multiple servers and I can confirm that pgbackrest works if pg_wal is on the same volume and no symbolic link.  And it doesn't work if pg_wal is on a different volume.

**Comment by pgstef** [comment] 2021-07-05 09:48
> So this is reproducable. I have tried this on multiple servers and I can confirm that pgbackrest works if pg_wal is on the same volume and no symbolic link. And it doesn't work if pg_wal is on a different volume.

On a simple quick CentOS7/PG13 test:

```bash
$ ll /var/lib/pgsql/13/data/|grep pg_wal
lrwxrwxrwx. 1 postgres postgres    12 Jul  5 10:52 pg_wal -> /data/pg_wal

$ pgbackrest --stanza=my_stanza backup --log-level-file=trace --type=full 
2021-07-05 11:21:54.289 P00   INFO: backup command begin 2.34: --delta --exec-id=28656-f3df48ae --log-level-console=info --log-level-file=trace --pg1-path=/var/lib/pgsql/13/data --pg1-port=5432 --pg1-user=postgres --process-max=2 --repo1-path=/var/lib/pgbackrest --repo1-retention-full=1 --stanza=my_stanza --start-fast --type=full
...
2021-07-05 11:22:01.829 P00   INFO: backup command end: completed successfully
```

So, it should work with `pg_data/pg_wal` being a symlink to `somewhere/pg_wal`.

The following part of your TRACE is a bit confusing imho `storage/storage::storageInfo: (this: {type: posix, path: {"/timescale-data"}, write: false}, fileExp: {"/timescale-data/pg_wal/pg_wal"}, param.level: 0, param.ignoreMissing: true, param.followLink: true, param.noPathEnforce: false)`.

Could you check your system links ? Perhaps the following commands could help understand the issue `ls -l /timescale-data`, `ls -l /timescale-data/pg_wal`, `ls -l /timescale-wal`, `ls -l /timescale-wal/pg_wal` ?

**Comment by rohitrav33ndran** [comment] 2021-07-05 11:43
@pgstef You are right.  Here is the details of the incorrect folder structure.

[list-postgres-folder-struct.txt](https://github.com/pgbackrest/pgbackrest/files/6763915/list-postgres-folder-struct.txt)

We had a symbolic link within /timescale-wal/pg_wal/ pointing to the same directory which was not intended. Thanks for helping to identify the problem.  I can confirm the problem is resolved.

**Comment by dwsteele** [comment] 2021-07-07 14:05
This definitely looked like a link loop so glad you found it.

The question is -- why aren't we detecting this loop and throwing an error? Thanks for the additional info, this will help us reproduce the issue and fix it.

**Comment by dwsteele** [comment] 2021-07-07 17:45
I was able to reproduce this and it has been fixed in #1452. Now you will get a clear error when there are circular links present.

Thanks for the report and details. How would you like your name to appear in the release notes?

**Comment by rohitrav33ndran** [comment] 2021-07-07 18:49
Oh that's great and Thank you.  My Name - Rohit Raveendran.

**Comment by dwsteele** [comment] 2021-07-07 19:08
We'll track this via the PR now so you can check there to see when it gets committed.

**Closed by dwsteele** 2021-07-07 19:08 UTC
Labels: bug
