### ISSUE TITLE
Nicer error message on SSH errors

### ISSUE THREAD

**Issue by terrorobe** [pgbackrest/pgbackrest#123] opened 2015-08-07 15:58 UTC
Might make sense to escalate the SSH exception to the log.

```
$ ssh off-ba-01-ber  -o ConnectTimeout=3
ssh: connect to host off-ba-01-ber port 22: Connection timed out
```

vs.

```
$ /opt/backrest/bin/pg_backrest --stanza=off-wiki-01-ber archive-push pg_xlog/000000010000027300000021 --log-level-console debug
2015-08-07 17:57:17.765 T00   INFO: pushing WAL segment pg_xlog/000000010000027300000021
2015-08-07 17:57:17.765 T00  DEBUG:     Remote->new(): command = /opt/backrest/bin/pg_backrest --no-config --repo-remote-path=/data/postgresql/backups --stanza=off-wiki-01-ber remote, host = off-ba-01-ber, user = backrest
2015-08-07 17:57:17.766 T00  DEBUG:     Protocol->new(): blockSize = 4194304, command = /opt/backrest/bin/pg_backrest --no-config --repo-remote-path=/data/postgresql/backups --stanza=off-wiki-01-ber remote, compressLevel = 6, compressLevelNetwork = 3, host = off-ba-01-ber, isBackend = false, name = remote, user = backrest
2015-08-07 17:57:24.785 T00  ERROR: [124]: remote process terminated: no error captured because stderr is already closed
2015-08-07 17:57:24.786 T00  ERROR: [124]: protocol version mismatch
2015-08-07 17:57:24.787 T00  DEBUG:     safe exit called, terminating threads
```

**Comment by dwsteele** [comment] 2015-08-07 16:03
This was fixed in 021afa8 but has not been release yet.

Annoyingly the -q option for OpenSSH suppresses error output as well as information messages.  I had turned on that option to make the regression tests work better against new trusted ssh setups.  It was reverted as part of the protocol rework.

**Comment by terrorobe** [comment] 2015-08-07 16:04
Doh, sorry! Thanks! :)

**Comment by dwsteele** [comment] 2015-08-07 16:05
No worries - better safe than sorry!

**Comment by plmayekar** [comment] 2016-05-13 09:37
Hi Team,

I have downloade latest version of pgbackrest tool .But when I am performing remote operation to take backup of remote postgres server ,I am getting below error


-bash-4.1$ pgbackrest --stanza=data backup --log-level-console debug
2016-05-13 15:06:22.640 T00   INFO: backup start: --db-host=pgtest --db-path=/opt/postgresql/pg95/data --log-level-console=debug --repo-path=/var/lib/pgbackrest --stanza=data
2016-05-13 15:06:22.640 T00  DEBUG:     Common:::Lock::lockAquire(): bFailOnNoLock = <true>, bRemote = <false>, iProcessIdx = [undef], strLockType = backup
2016-05-13 15:06:22.641 T00  DEBUG:     Common:::Lock::lockAquire=>: bResult = true
2016-05-13 15:06:22.680 T00  DEBUG:     Protocol::RemoteMaster->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 1830, strCommand = /usr/bin/pgbackrest --command=backup --repo-path=/var/lib/pgbackrest --stanza=data remote, strHost = pgtest, strUser = postgres
2016-05-13 15:06:22.680 T00  DEBUG:     Protocol::CommonMaster->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 1830, strCommand = ssh -o Compression=no -o PasswordAuthentication=no postgres@pgtest '/usr/bin/pgbackrest --command=backup --repo-path=/var/lib/pgbackrest --stanza=data remote', strName = remote
2016-05-13 15:06:22.694 T00  ERROR: [124]: protocol version mismatch
2016-05-13 15:06:22.696 T00  DEBUG:     Exit::exitSafe(): iExitCode = 124, strSignal = [undef]
2016-05-13 15:06:22.696 T00   INFO: backup stop
2016-05-13 15:06:22.696 T00  DEBUG:     Common:::Lock::lockRelease(): bFailOnNoLock = false


Kindly  help to resolve this issue


-bash-4.1$ pgbackrest --stanza=data backup
2016-05-13 15:05:50.952 T00  ERROR: [124]: protocol version mismatch

**Comment by dwsteele** [comment] 2016-05-13 12:11
It looks like some basic SSH connectivity issue.  Try `ssh postgres@pgtest` to be sure that your trusted SSH connection is property configured (http://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps).

If that works then try running the command that the protocol is running which you can find in the debug output above:
```
ssh -o Compression=no -o PasswordAuthentication=no postgres@pgtest '/usr/bin/pgbackrest --command=backup --repo-path=/var/lib/pgbackrest --stanza=data remote'
```
The output should look something like:
```
PGBACKRESTREMOTE 1.00
```
If you don't get that hopefully you'll see some kind of helpful ssh error.  Let me know what result you get and I'll see if I can improve the error handling in this area.

**Comment by plmayekar** [comment] 2016-05-16 08:27
Hi,

Thank you for reply.

Yes,It was ssh connectivity issues.Now, I have configured ssh between remote and backup server and vice versa.But whenever I am firing backup command from backup host ,archive_command is failing on remote and giving error as shown below:

.2016-05-15 18:04:44.661 T00  ERROR: [124]: protocol version mismatch
2016-05-15 18:04:44 IST [8114]: [12-1] user=,db=,app=,client= LOG:  archive command failed with exit code 124
2016-05-15 18:04:44 IST [8114]: [13-1] user=,db=,app=,client= DETAIL:  The failed archive command was: pgbackrest --stanza=data archive-push pg_xlog/000000060000000000000020
2016-05-15 18:04:44 IST [8114]: [14-1] user=,db=,app=,client= WARNING:  archiving transaction log file "000000060000000000000020" failed too many times, will try again later


My archive_command is failing and I have set it as  'pgbackrest --stanza=data archive-push %p'


If I take backup locally on remote server with same archive_command,it works but from another backup server is is giving error as shown above.

Kindly guide about archive_command,what do I need to make changes to take backup of remote server from backup server.

**Comment by dwsteele** [comment] 2016-05-16 13:11
Are you sure you have setup the trusted ssh connection in both directions, backup->db and db->backup?  Otherwise, it may be a configuration error.  Is backup-host set in pgbackrest.conf on the database server?  If neither of those work be sure to attach both of your pgbackrest.conf files so I can have a look.

**Comment by plmayekar** [comment] 2016-05-16 14:55
Hi David,

Yes I have configured ssh connection in both directions:

From Backup Server:
-bash-4.1$ ssh postgres@pgtest
Last login: Mon May 16 14:57:23 2016 from backup

From Db server:
-bash-4.1$ ssh postgres@backup
Last login: Mon May 16 20:22:54 2016 from pgtest

pgbackrest.conf on Backup Server:

[data]
db-path=/opt/postgresql/pg95/data
db-host=pgtest

[global]
#backup-host=pgtest1
repo-path=/var/lib/pgbackrest
start-fast=y

pgbackrest.conf on DB server:
-bash-4.1$ cat /etc/pgbackrest.conf 
[data]
db-path=/opt/postgresql/pg95/data


[global]
backup-host=backup
repo-path=/var/lib/pgbackrest

**Comment by dwsteele** [comment] 2016-05-16 15:32
The default `backup-user` is `backrest` so you'll need to set that to `postgres` in the db config:
```
[global]
backup-user=postgres
```
I don't recommend using `postgres` as the user on the backup server as this can lead to confusion, but it's your choice of course.

**Comment by plmayekar** [comment] 2016-05-17 07:43
Hi David,

Currently,I am using pgbackrest for test purpose.So I am using postgres user as a backup user.
Though I used backup-user as postgres in pgbackrest.conf, I am getting the same error:archive_command failed-protocol version mismatch

pgbackrest.conf on db server:

[data]
db-path=/opt/postgresql/pg95/data


[global]
backup-host=backup
backup-user=backrest
repo-path=/var/lib/pgbackrest

I have also tried manually to push archives using below command but the same error :(
-bash-4.1$ pgbackrest --stanza=data --backup-user=postgres --backup-host=backup archive-push %p
2016-05-17 13:07:31.323 T00  ERROR: [124]: protocol version mismatch

**Comment by dwsteele** [comment] 2016-05-17 12:31
Check the example above, should be:
```
[global]
backup-user=postgres
```
You have:
```
[global]
backup-user=backrest
```

**Comment by plmayekar** [comment] 2016-05-19 11:49
Hey,

Though I have given backup-user=postgres,it did not work.

Conf on db server:

-bash-4.1$ cat /etc/pgbackrest.conf 
[data]
db-path=/opt/postgresql/pg95/data
[global]
backup-host=backup
backup-user=postgres


Conf on backup server:
[data]
db-path=/opt/postgresql/pg95/data
db-host=pgtest

[global]
#backup-host=pgtest1
repo-path=/home/postgres/backup
backup-user=postgres
start-fast=y


Error:

LOG:  archive command failed with exit code 124
DETAIL:  The failed archive command was: pgbackrest --stanza=data  archive-push pg_xlog/000000060000000000000031

..2016-05-19 17:08:48.544 T00  ERROR: [124]: protocol version mismatch
LOG:  archive command failed with exit code 124
DETAIL:  The failed archive command was: pgbackrest --stanza=data  archive-push pg_xlog/000000060000000000000031
.


.2016-05-19 17:08:50.150 T00  ERROR: [124]: protocol version mismatch
LOG:  archive command failed with exit code 124
DETAIL:  The failed archive command was: pgbackrest --stanza=data  archive-push pg_xlog/000000060000000000000031
WARNING:  archiving transaction log file "000000060000000000000031" failed too many times, will try again later
2016-05-19 17:08:50.755 T00  ERROR: [124]: protocol version mismatch

**Comment by dwsteele** [comment] 2016-05-19 14:41
It still looks like some kind of ssh misconfiguration.  Can you verify that this works from the db server:
```
ssh postgres@backup
```

**Comment by plmayekar** [comment] 2016-05-20 07:17
Yes, Its working.I have already shared ssh connectivity with you.
From Db server:
-bash-4.1$ hostname
pgtest
-bash-4.1$ ssh postgres@backup
Last login: Mon May 16 20:23:40 2016 from pgtest
-bash-4.1$ 

From Backup server:

-bash-4.1$ hostname
backup
-bash-4.1$ ssh postgres@pgtest
Last login: Mon May 16 20:22:06 2016 from backup
-bash-4.1$

**Comment by dwsteele** [comment] 2016-05-20 13:03
Try adding ~/.ssh/config with these contents:
```
Host *
    LogLevel quiet
```
I don't think this should be needed but perhaps your ssh server is chattier than most.  What OS/version are you running?

**Closed** 2016-06-09 12:14 UTC
Labels: duplicate
