### ISSUE TITLE
primary database not found on 2.19

### ISSUE THREAD

**Issue by marco44** [pgbackrest/pgbackrest#878] opened 2019-11-20 10:24 UTC
Hi, I'm having this error on a just-migrated 2.19 pgbackrest (from 2.18, that worked), during a check command.

If I understand the code correctly, my configuration fails on a standby database for which repoIsLocal. repoIsLocal being defined as !cfgOptionTest(cfgOptRepoHost)

I don't have a repo host, as it's a S3 storage. But I'm wondering about this test anyway: why check that the primary is on the same machine ? There are so many ways that we could have a standby database with no primary database, such as a NFS or CIFS storage.

Here is may configuration, for reference...

```
[11-main
pg1-path=/mnt/secure/11/main
pg1-port=5433

[global]
compress-level=3
archive-async=y
archive-get-queue-max=4294967296
process-max=8
repo1-cipher-pass=xxxxxxxxxxxxxxxxxxxxxxxx
repo1-cipher-type=aes-256-cbc
repo1-path=/pgbackrest
repo1-s3-bucket=pgbackrest_bucket
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-key=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
repo1-s3-key-secret=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
repo1-s3-region=us-east-1
repo1-type=s3
spool-path=/mnt/secure/main/spool/
```

**Comment by dwsteele** [comment] 2019-11-20 12:32
So you are doing backups from the primary?  It looks like check thinks that backups are running from the standby (which requires a primary) but `backup-standby` is not set, so not sure why.

**Comment by marco44** [comment] 2019-11-20 12:36
We are also doing backups on the primary. But here, we are only setting up pgbackrest to be able to backup on all nodes, in case of a later switchover (so we don't have to deploy and setup pgbackrest in a rush the day we have an incident). We only have the standby node on the server we are doing this test. On 2.18, doing a pgbackrest check didn't fail here.

**Comment by dwsteele** [comment] 2019-11-20 12:47
So you wouldn't be doing a backup on this host until after a failover.  That's why `backup-standby` is not set.

OK -- we'll have a look at it.

**Comment by marco44** [comment] 2019-11-20 12:48
That's right. Thanks a lot.

**Comment by dwsteele** [comment] 2019-11-21 19:38
@cmwshang I think it's OK to allow a standby to pass check if `backup-standby=n` (the default).  In this case there's about zero check can do (like test `archive-push`) but it should at least succeed.

**Comment by dwsteele** [comment] 2022-07-22 13:53
We've made a lot of improvements to configuration in this area so closing. If this can reproduced on a recent version please let us know.

**Closed by dwsteele** 2022-07-22 13:53 UTC
Labels: module [core], enhancement
