### ISSUE TITLE
Check command errors when run on a cluster with tablespaces

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#503] opened 2018-03-18 12:22 UTC
Hello, i ve been running v2 successfully against 10.3 for the last week - 
Fri 2018-03-16 18:42:14.039 P00   INFO: backup command end: completed successfully
Sat 2018-03-17 18:36:01.795 P00   INFO: backup command end: aborted with exception [056]
i ran a stanza-check and recieved the following

2018-03-18 08:20:55.512 P00  DEBUG:     Db->info=>: iDbCatalogVersion = 201707211, iDbControlVersion = 1002, strDbVersion = 10, ullDbSysId = 6521373438747668096
ASSERT [025]: : strSection 'backup:db', strKey 'db-catalog-version' is required but not defined
ERROR [025]: : Database: 10 6521373438747668096 strSection 'backup:db', strKey 'db-catalog-version' is required but not defined

the only change yesterday was an ldap config in pg_hba.conf
thanks

**Comment by dwsteele** [comment] 2018-03-19 01:31
Yeah, that doesn't look right, but we'll need more output to proceed.

In particular, we need the first info line in the log that shows all the options, and then about 10 lines before what you have given here for some context.

Thanks!

**Comment by seadba** [comment] 2018-03-19 03:42
thanks - sorry should have posted that earlier

-bash-4.2$ pgbackrest --stanza=btpg10  --log-level-console=debug check
2018-03-18 23:37:42.032 P00   INFO: check command begin 2.00: --log-level-console=debug --pg1-path=/opt/PostgreSQL/10/data --pg1-port=5432 --repo1-path=/instance1/postgres/10/backup --stanza=btpg10
2018-03-18 23:37:42.100 P00  DEBUG:     Db::dbObjectGet(): bMasterOnly = true
2018-03-18 23:37:42.100 P00  DEBUG:     Db->new(): iRemoteIdx = 1
2018-03-18 23:37:42.100 P00  DEBUG:     Db::dbObjectGet=>: iDbMasterIdx = 1, iDbStandbyIdx = [undef], oDbMaster = [object], oDbStandby = [undef]
2018-03-18 23:37:42.100 P00  DEBUG:     Db->info(): strDbPath = </opt/PostgreSQL/10/data>
2018-03-18 23:37:42.100 P00  DEBUG:     Db->info=>: iDbCatalogVersion = 201707211, iDbControlVersion = 1002, strDbVersion = 10, ullDbSysId = 6521373438747668096
ASSERT [025]: : strSection 'backup:db', strKey 'db-catalog-version' is required but not defined
ERROR [025]: : Database: 10 6521373438747668096 strSection 'backup:db', strKey 'db-catalog-version' is required but not defined
2018-03-18 23:37:42.670 P00  DEBUG:     Common::Exit::exitSafe(): iExitCode = 25, oException = [undef], strSignal = [undef]
2018-03-18 23:37:42.670 P00  DEBUG:     Protocol::Helper::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
2018-03-18 23:37:42.670 P00  DEBUG:     Protocol::Helper::protocolDestroy=>: iExitStatus = 0
2018-03-18 23:37:42.670 P00   INFO: check command end: completed successfully
2018-03-18 23:37:42.670 P00  DEBUG:     Common::Lock::lockRelease(): bFailOnNoLock = false
2018-03-18 23:37:42.670 P00  DEBUG:     Common::Exit::exitSafe=>: iExitCode = 25
-bash-4.2$

**Comment by dwsteele** [comment] 2018-03-19 12:45
I figured out what's causing the check error, but it doesn't appear to have anything to do with why the backup failed.

Your original backup failed with error 56 which is a database connection error.  So it looks like the postgres user is being refused when it connects to start the backup.  If you look in `btpg10-backup.log` from 3-17 you should see an error message with the cause.  Make sure postgres still has peer rights to connect to the db.

The problem with check is on account of a new check we added into v2 that is not being properly initialized to work with tablespaces.  This database has tablespaces, correct?

**Comment by seadba** [comment] 2018-03-19 12:47
sorry for delay - here is the run of the check

-bash-4.2$ pgbackrest --stanza=btpg10  --log-level-console=debug check

2018-03-18 23:37:42.032 P00   INFO: check command begin 2.00: --log-level-console=debug --pg1-path=/opt/PostgreSQL/10/data --pg1-port=5432 --repo1-path=/instance1/postgres/10/backup --stanza=btpg10
2018-03-18 23:37:42.100 P00  DEBUG:     Db::dbObjectGet(): bMasterOnly = true
2018-03-18 23:37:42.100 P00  DEBUG:     Db->new(): iRemoteIdx = 1
2018-03-18 23:37:42.100 P00  DEBUG:     Db::dbObjectGet=>: iDbMasterIdx = 1, iDbStandbyIdx = [undef], oDbMaster = [object], oDbStandby = [undef]
2018-03-18 23:37:42.100 P00  DEBUG:     Db->info(): strDbPath = </opt/PostgreSQL/10/data>
2018-03-18 23:37:42.100 P00  DEBUG:     Db->info=>: iDbCatalogVersion = 201707211, iDbControlVersion = 1002, strDbVersion = 10, ullDbSysId = 6521373438747668096
ASSERT [025]: : strSection 'backup:db', strKey 'db-catalog-version' is required but not defined
ERROR [025]: : Database: 10 6521373438747668096 strSection 'backup:db', strKey 'db-catalog-version' is required but not defined
2018-03-18 23:37:42.670 P00  DEBUG:     Common::Exit::exitSafe(): iExitCode = 25, oException = [undef], strSignal = [undef]
2018-03-18 23:37:42.670 P00  DEBUG:     Protocol::Helper::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
2018-03-18 23:37:42.670 P00  DEBUG:     Protocol::Helper::protocolDestroy=>: iExitStatus = 0
2018-03-18 23:37:42.670 P00   INFO: check command end: completed successfully
2018-03-18 23:37:42.670 P00  DEBUG:     Common::Lock::lockRelease(): bFailOnNoLock = false
2018-03-18 23:37:42.670 P00  DEBUG:     Common::Exit::exitSafe=>: iExitCode = 25
-bash-4.2$

**Comment by seadba** [comment] 2018-03-19 12:51
sorry. sat backup failure was due to another issue - i ran the check after i got the failed notice, saw the 25 errror and assumed it was connected

**Comment by seadba** [comment] 2018-03-19 12:52
yes, we have an additional tablespace

**Comment by dwsteele** [comment] 2018-03-19 12:53
OK, thanks.  We'll fix the check issue.

Meanwhile, your backups are running OK?

**Comment by seadba** [comment] 2018-03-19 12:57
absolutely - after some minor issues when we installed v2, backups have been running perfectly - i ran 3 restore/recovery tests during the week with no issues - fantastic product - thanks

**Comment by dwsteele** [comment] 2018-03-19 13:07
OK - I've updated the title of this issue and marked it as a bug.

How would you like your name to appear in the release notes?

**Comment by seadba** [comment] 2018-03-19 13:16
Thomas Flatley - thanks again for the fast response -

**Comment by dwsteele** [comment] 2018-03-20 00:37
Fixed at f0a4264f77a7d9cb1dc5434e3c76.  Thanks for the report!

**Closed by dwsteele** 2018-03-20 00:37 UTC
Labels: bug (code)
