### ISSUE TITLE
pgbackrest cannot clean up after detecting previous aborted backup

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#310] opened 2017-01-19 12:21 UTC
The following log output shows that pgbackrest couldnt cleanup its temporary directories from:
`/pgarchive/pgbackrest/temp/model.tmp/pg_data/base`

The technical reason is that it is trying to remove a directory and the command to remove applies to files only.

```
-------------------PROCESS START-------------------
2017-01-18 19:00:02.007 P00   INFO: backup command begin 1.12: --archive-check --buffer-size=8388608 --compress --compress-level=3 --db-host=msp0llexm021 --db-path=/pgdata/lenderx --db-port=5432 --db-user=postgres --log-level-file=info --log-path=/pgarchive/pgbackrest/log/model --process-max=10 --repo-path=/pgarchive/pgbackrest --retention-archive-type=diff --retention-diff=3 --retention-full=1 --stanza=model --start-fast --stop-auto --type=diff
2017-01-18 19:00:07.601 P00   INFO: last backup label = 20170114-073705F, version = 1.12
2017-01-18 19:00:10.350 P00   INFO: execute exclusive pg_start_backup() with label "pgBackRest backup started at 2017-01-18 19:00:02": backup begins after the requested immediate checkpoint completes
2017-01-18 19:00:24.919 P00   INFO: backup start archive = 0000000500002AAF000000BB, lsn = 2AAF/BB02C018
2017-01-18 19:00:55.342 P00   WARN: aborted backup of same type exists, will be cleaned to remove invalid files and resumed
2017-01-18 19:01:11.507 P00  ERROR: [116]: unable to remove /pgarchive/pgbackrest/temp/model.tmp/pg_data/base/106593901: Is a directory
2017-01-18 19:01:11.681 P00  ERROR: [116]: unable to remove /pgarchive/pgbackrest/temp/model.tmp/pg_data/base/106593901: Is a directory
2017-01-18 19:01:11.682 P00   INFO: backup command end: aborted with exception [116]
```

**Comment by dwsteele** [comment] 2017-01-23 00:36
I feel like this is some kind of numeric ordering issue.  I'll have a look.

**Comment by MichaelDBA** [comment] 2017-02-02 02:55
So is this fixed in a new release?  If not, can I just remove everything in the .../temp/<mystanza>.tmp directory?

**Comment by dwsteele** [comment] 2017-02-02 16:19
I haven't found the cause of this yet.  If you still have the directory around please send the results of:
```
ls -lahR /pgarchive/pgbackrest/temp/model.tmp
```
And go ahead and remove the directory manually.

**Comment by MichaelDBA** [comment] 2017-02-05 11:02
Sorry, I already deleted it, but it is the error you would get if you were trying to delete a directory with the "rm" command.  So pgbackrest is not expecting a directory under "/pgarchive/pgbackrest/temp/model.tmp"?

**Comment by dwsteele** [comment] 2017-02-05 16:06
Directories are certainly expected in the temp dir.

I'm not able to reproduce this and without more information there's not a lot I can do so I'll close it for now.  If you see the issue again, please send the directory listing with `ls -lahR`.

**Closed by dwsteele** 2017-02-05 16:06 UTC
Labels: bug (code)
