### ISSUE TITLE
Dont' use "localtime" for HTML-docs

### ISSUE THREAD

**Issue by disco-stu** [pgbackrest/pgbackrest#209] opened 2016-06-20 14:29 UTC
The doc build process uses localtime for the HTML footer
(Updated) (doc/manifest.xml:26). Which leads to unreprodrucible builds
in Debian [1].

Would it be possible to use e.g. "release date" for that?
Alternatively would it be possible to add a custom parameter
--updated-time or something?

https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/pgbackrest.html

**Comment by dwsteele** [comment] 2016-06-20 16:27
I can do something along those lines for the next release, but for now you can just add:
```
 --var="html-footer=Copyright &copy;2015-2016, The PostgreSQL Global Development Group."
```
To the doc.pl command to force the footer to be reproducible.

**Comment by disco-stu** [comment] 2016-06-20 17:48
Great! Thanks.

**Comment by dwsteele** [comment] 2016-06-28 12:40
In 1.03 you will be able to use `--var=release-date-static=y` to force a reproducible date in the footer instead of overriding `html-footer`.

**Comment by dwsteele** [comment] 2016-07-02 15:26
1.03 is out.  Do you get notified of that somehow?  I'm not sure how that works.

**Comment by disco-stu** [comment] 2016-07-04 11:20
No, I don't. I look into [1] once a week. The last column ("Watch") indicates if a new version is available. If you want to, you could trigger me on IRC (#postgresql-apt @ irc.freenode.net) or drop me a mail. 

[1] https://qa.debian.org/developer.php?email=adrian.vondendriesch%40credativ.de

**Comment by dwsteele** [comment] 2016-07-05 18:52
The 1.03 build is marked as unreproducible:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/pgbackrest.html
It's looks like the date is alternating between French/English?  Do I need to render months always in English?  Seems like it would be better to let Perl render based on locale.

**Comment by dwsteele** [comment] 2016-07-05 18:56
Perhaps set LANG=en_us?  Since the docs are written in English seems kind of silly to have French in the footer.

**Comment by disco-stu** [comment] 2016-07-06 09:19
How about using ISO 8601 format? I don't know if en_US is installed in every build environment. We could also use LC_ALL=C but I would prefer using a non locale specific format.

**Closed** 2016-07-26 21:40 UTC
Labels: enhancement (doc), Low Priority

**Comment by dwsteele** [comment] 2016-07-26 21:44
This should be fixed now (no changes are required on your side).  1.04 will be released as soon as regression tests have passed.  I'll ping you when it's ready.
