### ISSUE TITLE
serious performance issues with archive-get and large/huge archive-get-queue-max (with strace analyze)

### ISSUE THREAD

**Issue by MaximBoguk** [pgbackrest/pgbackrest#2275] opened 2024-02-06 00:11 UTC
1. pgBackRest version:
pgBackRest 2.50

2. PostgreSQL version:
postgres (PostgreSQL) 15.5 (Ubuntu 15.5-1.pgdg20.04+1)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Description:	Ubuntu 20.04.6 LTS

4. Did you install pgBackRest from source or from a package?
pgdg package

5. Please attach the following as applicable:
[global]
log-level-file=debug
log-path=/var/log/postgresql
spool-path=/mnt/nvme/spool/pgbackrest
compress-type=lz4
process-max=32
archive-async=y
archive-timeout=300
archive-get-queue-max=160GB

7. Describe the issue:
With large value of archive-get-queue-max I found that every call of archive-get took over 200ms on my very fast system with spool directory on the same local fast nvme fast system as the database. As a result wal replay slowed to 5-10x.

Strace analysis of wal replay show that pgbackrest during archive-get command calls the following syscall sequence for EVERY file in the spool directory (10k files in my case so 10k lstats+10k times read /etc/passwd and /etc/group):

3660827 23:34:53.489691 lstat("/mnt/nvme/spool/pgbackrest/archive/*****/in/0000000200123D5900000085", {st_mode=S_IFREG|0640, st_size=16777216, ...}) = 0
3660827 23:34:53.489724 openat(AT_FDCWD, "/etc/group", O_RDONLY|O_CLOEXEC) = 9
3660827 23:34:53.489753 lseek(9, 0, SEEK_CUR) = 0
3660827 23:34:53.489779 fstat(9, {st_mode=S_IFREG|0644, st_size=939, ...}) = 0
3660827 23:34:53.489805 read(9, "root:x:0:\ndaemon:x:1:\nbin:x:2:\ns"..., 4096) = 939
3660827 23:34:53.489835 close(9)        = 0
3660827 23:34:53.489861 openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 9
3660827 23:34:53.489890 lseek(9, 0, SEEK_CUR) = 0
3660827 23:34:53.489916 fstat(9, {st_mode=S_IFREG|0644, st_size=2035, ...}) = 0
3660827 23:34:53.489942 read(9, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 2035
3660827 23:34:53.489972 close(9)        = 0

of course for 10k files such loop require quite substantiation time. 

Is this behavior expected? Because it kills any practical applications of large archive-get-queue-max values.

**Comment by dwsteele** [comment] 2024-02-06 12:40
We are aware of this (https://github.com/pgbackrest/pgbackrest/projects/2#card-76111737) but it has not gotten priority because we are not convinced that large queues are helpful, and they may in fact be harmful if when there are a number of timeline switches.

The purpose of the queue is to stay ahead of PosgreSQL recovery and 4-8GiB seems to be more than enough for that purpose.

Any reason why you have `archive-get-queue-max` set so high?

**Comment by MaximBoguk** [comment] 2024-02-06 13:02
Mostly it was testing the performance effects of different archive-get-queue-max sizes for recovery/wal-replay on huge database with high wal traffic. 
I agree that the 4-8GiB usually enough for the task per my testing.

**Comment by dwsteele** [comment] 2024-02-06 13:05
It is something we are planning to address -- but we have a rather long list.

**Comment by dwsteele** [comment] 2024-02-06 14:31
I had a quick look at this to make sure I could close it and roll it into the project card mentioned above.

As it turns out, this was something a different caused by pretty old regression in the storage layer. This has been fixed in #2276. Feel free to test it out if you can.

**Closed by dwsteele** 2024-02-06 14:31 UTC
Labels: bug, module [core]
