### ISSUE TITLE
Uncaught ExecuteError: remote-0 process on 'xx.xx.xx.xx' did not exit when expected thrown at common/exec.c:101

### ISSUE THREAD

**Issue by maipeng** [pgbackrest/pgbackrest#917] opened 2020-01-27 10:31 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.19

2. PostgreSQL version: 10.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
repository host server: debian 9
database server : debian 9
4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest-1.txt](https://github.com/pgbackrest/pgbackrest/files/4116602/pgbackrest-1.txt)

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/4116609/postgresql.conf.txt)

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[pgbackrest.local.log](https://github.com/pgbackrest/pgbackrest/files/4116611/pgbackrest.local.log)

7. Describe the issue:
In order to implement replication streaming , I synchronize a slave by using a delta restore, launched on the database server:
pgbackrest --stanza=dbz --delta --type=standby restore --compress-level-network=6 --log-level-console=debug --log-level-file=trace --log-level-stderr=trace --log-subprocess --pg1-path=/var/lib/postgresql/10/main --process-max=6 --recovery-option=standby_mode=on --recovery-option="primary_conninfo=host=xx.xx.xx.xx user=xxxxx password=xxxx" --recovery-option=recovery_target_timeline=latest --recovery-option=trigger_file=/tmp/postgresql.trigger --repo1-host=xx.xx.xx.xx
at the end I have this error Uncaught ExecuteError: remote-0 process on 'xx.xx.xx.xx' did not exit when expected thrown at common/exec.c:101.
thank you

**Comment by dwsteele** [comment] 2020-01-28 15:04
The root cause here is the eof in the local log.  The next error is pgbackrest trying to shut down the local and failing.  The reporting on that second error needs to be improved.

Not sure what the root cause is -- is this reproducible?  It could be a network issue or, of course, and bug.  If a bug there's not really enough to work with.  Any errors in the remote log?

**Comment by maipeng** [comment] 2020-01-29 09:56
Hello David,
Yes it is reproductible. Here the log on the remote host
[pgbackrest_remotehost.log](https://github.com/pgbackrest/pgbackrest/files/4127268/pgbackrest_remotehost.log)
thanks a lot.

**Comment by dwsteele** [comment] 2020-01-29 15:02
It looks like the connection between the hosts is getting closed: `[064]: unable to write to remote-6: [32] Broken pipe`.  Does it run for the same amount of time before failing?  Sometimes firewall rules can cause connections to be closed.

**Comment by maipeng** [comment] 2020-01-30 13:31
Hello,
no it does not run for the same amount of time, but it always fails at this step, just after the waitTime.
2020-01-29 15:50:13.558 P00  TRACE:         common/exec::execWrite: => void
2020-01-29 15:50:13.558 P00  TRACE:         common/io/write::ioWriteFlush: => void
2020-01-29 15:50:13.558 P00  TRACE:         protocol/client::protocolClientWriteCommand: => void
2020-01-29 15:50:13.558 P00  TRACE:         protocol/client::protocolClientFreeResource: => void
2020-01-29 15:50:13.558 P00  TRACE:         common/exec::execFreeResource: (this: {Exec})
2020-01-29 15:50:13.558 P00  TRACE:         common/wait::waitNew: (waitTime: 10000)
2020-01-29 15:50:13.558 P00  TRACE:         common/wait::waitNew: => {Wait}
2020-01-29 15:50:13.558 P00  TRACE:         common/wait::waitMore: (this: {Wait})
2020-01-29 15:50:13.658 P00  TRACE:         common/wait::waitMore: => true
2020-01-29 15:50:13.658 P00  TRACE:         common/wait::waitMore: (this: {Wait})
2020-01-29 15:50:13.759 P00  TRACE:         common/wait::waitMore: => true
2020-01-29 15:50:13.759 P00  TRACE:         common/wait::waitMore: (this: {Wait})
2020-01-29 15:50:13.959 P00  TRACE:         common/wait::waitMore: => true
2020-01-29 15:50:13.959 P00  TRACE:         common/wait::waitMore: (this: {Wait})
2020-01-29 15:50:14.259 P00  TRACE:         common/wait::waitMore: => true
2020-01-29 15:50:14.259 P00  TRACE:         common/wait::waitMore: (this: {Wait})
2020-01-29 15:50:14.760 P00  TRACE:         common/wait::waitMore: => true
2020-01-29 15:50:14.760 P00  TRACE:         common/wait::waitMore: (this: {Wait})
2020-01-29 15:50:15.561 P00  TRACE:         common/wait::waitMore: => true
2020-01-29 15:50:15.561 P00  TRACE:         common/wait::waitMore: (this: {Wait})
2020-01-29 15:50:16.862 P00  TRACE:         common/wait::waitMore: => true
2020-01-29 15:50:16.862 P00  TRACE:         common/wait::waitMore: (this: {Wait})

**Comment by dwsteele** [comment] 2020-07-24 15:17
We're going to close this issue to consolidate it with #1112 .

Please let us know how you would like your name to appear in the release notes when we commit the fix.

**Closed by dwsteele** 2020-07-24 15:17 UTC
Labels: bug, duplicate, module [core]
