### ISSUE TITLE
how to speed up WAL archiving (is there a parallel execution option)?

### ISSUE THREAD

**Issue by sandrotosi** [pgbackrest/pgbackrest#317] opened 2017-02-01 16:57 UTC
Hello,
we configured pgbackrest to use 8 jobs for backup, and it is great, but the WAL archiving still seems to be a single job process, even when using --archive-async.

is there any way to run that as a multi-process job? or to speed the archiving up?

this db machine is extremely fast at generating WAL files that pgbackrest is not able to keep up them, leading to several disk full situations.

thanks!

**Comment by sandrotosi** [comment] 2017-02-01 17:06
haha just stumbled upon https://github.com/pgbackrest/pgbackrest/commit/43ada9fb33b51479b959ea6a93fcb53fa0803e25

how confident are you with that? are you planning to release a new version of pgbackrest with that included some time soon?

**Comment by MichaelDBA** [comment] 2017-02-01 17:09
wow, this affects me big time too with lagging WAL.  Great!

**Comment by dwsteele** [comment] 2017-02-01 18:46
I feel pretty good about the code and it passes all unit/regression tests.  The very latest I was planning on releasing 1.13 was Feb 8th or 9th.  It might be earlier than that, but I'd like to clean some items off the issues list before it goes out.

**Comment by dwsteele** [comment] 2017-02-01 18:50
BTW - it looks like you are both using async so that means you'll need to read the release notes carefully to avoid losing WAL in the old queue.  Here a preview of the instructions:
https://github.com/pgbackrest/pgbackrest/commit/43ada9fb33b51479b959ea6a93fcb53fa0803e25#diff-310776b2be9f303b3b8ef64c1f782d9d

**Comment by sandrotosi** [comment] 2017-02-01 19:08
thanks for the heads up! we switched to async archiving hoping to get better performances - is the parallel archiving something that will work only on async or also in the "normal"/synchronous method?

**Comment by dwsteele** [comment] 2017-02-01 19:53
The new method uses an async process to "look ahead" and archive WAL that is marked as ready to be archived before PostgreSQL actually calls archive_command.  So unlike now, the process is synchronous from PG's perspective, i.e. when archive-push returns success the WAL is already in the archive.  Another big advantage is that the WAL is no longer copied to a separate queue.

"Normal" archiving remains synchronous with no look ahead.

**Comment by MichaelDBA** [comment] 2017-02-01 21:14
Just to make sure I understand.  By "separate queue", I'm guessing you mean "spool-path" logic, correct?  If  so, I just gotta make sure my spool is empty before updating to newer version correct?  Also, is "spool-path" a deprecated parameter now in light of this?

**Comment by dwsteele** [comment] 2017-02-01 21:18
Yes, that's the basic idea.

No, the spool-path is used to maintain the state of the async process so you'll still need to keep it around.  However, it takes up very little space now since WAL is not copied there.

The spool-path will also be used to buffer WAL in the forthcoming parallel archive-get.

**Comment by MichaelDBA** [comment] 2017-02-01 23:32
Thanks for the feedback!

**Closed** 2017-02-03 01:47 UTC
Labels: question
