### ISSUE TITLE
WAL archiving fails with "ASSERT: check 'type == protocolMessageTypeCommand' failed" under heavy load

### ISSUE THREAD

**Issue by loop-evgeny** [pgbackrest/pgbackrest#1634] opened 2022-01-25 10:10 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.36

2. PostgreSQL version: 14.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? Package on apt.postgresql.org

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

pgbackrest.conf on repository host:

```
[global]
repo1-path=/backup/pg

lock-path=/var/run/pgbackrest
compress-type=zst
start-fast=y
log-level-file=info
log-subprocess=y
log-level-console=warn
```

/etc/pgbackrest/pgbackrest.conf on DB server (global config file):

```
[global]
repo1-host=(redacted)
repo1-host-user=postgres

lock-path=/var/run/pgbackrest
compress-type=zst
start-fast=y
log-level-file=info
log-subprocess=y
log-level-console=warn

[global:restore]
process-max=4

[global:archive-get]
process-max=4
```

/etc/pgbackrest/conf.d/behavior-pg14.conf on DB server (per-instance config file):

```
[behavior-pg14]
pg1-port=5434
pg1-path=/pgdata/behavior-pg14
```

postgresql.conf:

```
wal_level = replica
archive_mode = on
archive_timeout = 15min
archive_command = 'pgbackrest --stanza="behavior-pg14" archive-push "%p"'
```

postgresql.log:

```
2022-01-24 16:20:33.085 UTC [14185] LOG:  archive command failed with exit code 39
2022-01-24 16:20:33.085 UTC [14185] DETAIL:  The failed archive command was: pgbackrest --stanza="behavior-pg14" archive-push "pg_wal/000000010000004C000000A1"
```

pgbackrest.log on repository host

```
2022-01-24 16:19:03.912 P00   INFO: archive-push:remote command begin 2.36: --exec-id=16166-5f6d3857 --lock-path=/var/run/pgbackrest --log-level-console=off --log-level-file=info --log-level-stderr=error --log-subprocess --pg1-path=/pgdata/behavior-pg14 --pg2-path=/pgdata/behavior-pg14 --process=0 --remote-type=repo --repo=1 --repo1-path=/backup/pg --stanza=behavior-pg14
2022-01-24 16:20:32.989 P00 ASSERT: [025]: check 'type == protocolMessageTypeCommand' failed
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:
                                    
                                    version: 2.36
                                    command: archive-push:remote
                                    options: --exec-id=16166-5f6d3857 --lock-path=/var/run/pgbackrest --log-level-console=off --log-level-file=info --log-level-stderr=error --log-subprocess --pg1-path=/pgdata/behavior-pg14 --pg2-path=/pgdata/behavior-pg14 --process=0 --remote-type=repo --repo=1 --repo1-path=/backup/pg --stanza=behavior-pg14
                                    
                                    stack trace:
                                    protocol/server.c:protocolServerCommandGet:122:(trace log level required for parameters)
                                    protocol/server.c:protocolServerProcess:(debug log level required for parameters)
                                    command/remote/remote.c:cmdRemote:(debug log level required for parameters)
                                    main.c:main:(debug log level required for parameters)
```

[behavior-pg14-archive-push-remote-000.zip](https://github.com/pgbackrest/pgbackrest/files/7932608/behavior-pg14-archive-push-remote-000.zip)

7. Describe the issue:

I was inserting data into a PG 14 database as fast as possible (for a performance test). pgBackRest is configured to archive the WAL for that PG instance to a remote host. After running for about 6 hours the archive command first failed at 2022-01-24 16:12:35 and continued to fail after that:

```
2022-01-24 16:12:35.076 UTC [14185] LOG:  archive command failed with exit code 39
2022-01-24 16:12:35.076 UTC [14185] DETAIL:  The failed archive command was: pgbackrest --stanza="behavior-pg14" archive-push "pg_wal/000000010000004C000000A1"
```

pgbackrest.log on the repository host still reported success at the time (the clocks are in sync on the machines):

```
2022-01-24 16:12:36.370 P00   INFO: archive-push:remote command begin 2.36: --exec-id=20597-598394ea --lock-path=/var/run/pgbackrest --log-level-console=off --log-level-file=info --log-level-stderr=error --log-subprocess --pg1-path=/pgdata/behavior-pg14 --pg2-path=/pgdata/behavior-pg14 --process=0 --remote-type=repo --repo=1 --repo1-path=/backup/pg --stanza=behavior-pg14
2022-01-24 16:13:40.753 P00   INFO: archive-push:remote command end: completed successfully (64384ms)

-------------------PROCESS START-------------------
2022-01-24 16:13:42.348 P00   INFO: archive-push:remote command begin 2.36: --exec-id=15068-8c400761 --lock-path=/var/run/pgbackrest --log-level-console=off --log-level-file=info --log-level-stderr=error --log-subprocess --pg1-path=/pgdata/behavior-pg14 --pg2-path=/pgdata/behavior-pg14 --process=0 --remote-type=repo --repo=1 --repo1-path=/backup/pg --stanza=behavior-pg14
2022-01-24 16:14:45.991 P00   INFO: archive-push:remote command end: completed successfully (63644ms)
```

However from 16:20:32 it started logging the assertion failure above ("check 'type == protocolMessageTypeCommand' failed"). There were some success messages after that as well, but now it seems to fail all the time.

**Comment by loop-evgeny** [comment] 2022-01-25 10:14
Also, are the exit codes documented somewhere? I cannot find what "exit code 39" means.

**Comment by loop-evgeny** [comment] 2022-01-25 14:23
It turns out the repository host ran out of disk space around the time of the error, which is likely the cause, but the error message is certainly confusing!

**Comment by dwsteele** [comment] 2022-01-25 14:36
Yeah, I was about to suggest that it was a disk space issue. This is an area we are working on -- basically if a file transfer fails in the middle the protocol gets in a bad state and the original error can be lost. This is especially true for out of space conditions.

**Comment by dwsteele** [comment] 2022-01-25 15:02
What was the error in the `archive-push-async` log?

**Comment by dwsteele** [comment] 2022-01-25 15:36
It is on the pg host. The attached file is from the repo host. This is async archiving, right?

**Comment by loop-evgeny** [comment] 2022-01-25 15:52
Ah, no, we don't currently have async archiving enabled. (But I will try that after fixing the immediate disk space issue, because the WAL archiving was already not keeping up before running out of disk space.) I've edited the pgBackRest config from the PG server into the original issue.

**Comment by jurim76** [comment] 2022-03-26 18:21
Same issue for me
pgBackRest 2.37 / postgresql 13, db and repo are running as k8s statefulsets

On db host
[testdb]
pg1-path=/var/lib/postgresql/pgdata/13
pg1-host=testdb01
pg1-host-port=22
pg1-host-user=postgres

On repo host
[testdb]
pg1-path=/var/lib/postgresql/pgdata/13
repo1-path=/var/lib/pgbackrest/pgdata
repo1-host=pgbackup
repo1-host-user=postgres
repo1-host-port=22

On repo host
`pgbackrest --stanza=testdb check 
2022-03-26 18:12:10.575 P00   INFO: check command begin 2.37: --exec-id=806-602e32aa --log-level-console=info --log-level-file=info --pg1-host=
testdb01 --pg1-host-port=22 --pg1-host-user=postgres --pg1-path=/var/lib/postgresql/pgdata/13 --repo1-path=/var/lib/pgbackrest/pgdata --stanza=
testdb
2022-03-26 18:12:11.350 P00   INFO: check repo1 configuration (primary)
2022-03-26 18:12:11.856 P00   INFO: check repo1 archive for WAL (primary)
2022-03-26 18:12:12.057 P00   INFO: WAL segment 000000010000000000000007 successfully archived to '/var/lib/pgbackrest/pgdata/archive/testdb/13
-4/0000000100000000/000000010000000000000007-ad419ae13a2ffa155be0d3d899cd7ccbb137d2e7.gz' on repo1
2022-03-26 18:12:12.159 P00   INFO: check command end: completed successfully (1585ms)
`
`pgbackrest --stanza=testdb backup
2022-03-26 18:13:27.414 P00   INFO: backup command begin 2.37: --exec-id=816-bac4d10f --log-level-console=info --log-level-file=info --pg1-host
=testdb01 --pg1-host-port=22 --pg1-host-user=postgres --pg1-path=/var/lib/postgresql/pgdata/13 --repo1-path=/var/lib/pgbackrest/pgdata --repo1-
retention-diff=1 --repo1-retention-full=2 --stanza=testdb
WARN: no prior backup exists, incr backup has been changed to full
2022-03-26 18:13:28.292 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the next regular checkpoint completes
2022-03-26 18:13:29.402 P00   INFO: backup start archive = 000000010000000000000009, lsn = 0/9000060
2022-03-26 18:13:29.402 P00   INFO: check archive for prior segment 000000010000000000000008
`
After some timeout (about 15 min) got error "client state is 'data-get' but expected 'idle'" after a failed backup"
Not related with disk space and high I/O, because this db in idle state and very small (150m)

**Comment by mindrunner** [comment] 2022-04-04 18:47
I am in the same boat. I have two more or less identical k8s clusters with tsdb backup configured to an s3 endpoint via `minio` acting as an s3 gateway (indefinite storage). My `TEST` instance has no issues, but `PROD` always fails backups with above mentioned error.

**Comment by dwsteele** [comment] 2022-04-13 20:26
So I've been trying for a while to reproduce this with no luck. When out of space I just get a regular error.

One thing that occurs to me. We have seen multiple instances in the past where the OS writes messages to all active SSH connections. This happens more on production systems that are more likely to have alerts enabled. Any kind of noise on the SSH connection is destructive to the protocol state.

At this point I would recommend trying out TLS, which has been out for a few releases and is quite a bit faster than SSH. If the problem reproduces on TLS it will hopefully be easier to debug.

**Comment by loop-evgeny** [comment] 2022-04-14 07:28
It's only happened to me once, so I wouldn't know how to repro it, either.

**Comment by jurim76** [comment] 2022-04-18 15:05
in my case, pgbackrest waits 30 min. for query result and exit

pgbackrest 2.38
pgbackrest repo and testdb01 postgres database are running in k8s cluster as deployments

pgbackrest --log-level-console=debug --stanza=testdb backup 

`2022-04-18 14:22:47.660 P00  DEBUG:     storage/storage::storagePathSync: => void
2022-04-18 14:22:47.660 P00  DEBUG:     command/backup/backup::backupProcess: => void
2022-04-18 14:22:47.660 P00  DEBUG:     command/backup/backup::backupDbPing: (backupData: {BackupData}, force: true)
2022-04-18 14:22:47.660 P00  DEBUG:     db/db::dbPing: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'testdb01', state: i
dle}}, force: true)
2022-04-18 14:22:47.660 P00  DEBUG:     db/db::dbIsInRecovery: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'testdb01', 
state: idle}})
2022-04-18 14:22:47.660 P00  DEBUG:     db/db::dbQueryColumn: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'testdb01', s
tate: idle}}, query: {"select pg_catalog.pg_is_in_recovery()"})
2022-04-18 14:22:47.660 P00  DEBUG:     db/db::dbQuery: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'testdb01', state: 
idle}}, query: {"select pg_catalog.pg_is_in_recovery()"})
2022-04-18 14:53:17.758 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
ERROR: [039]: client state is 'data-get' but expected 'idle'
2022-04-18 14:53:17.859 P00   INFO: backup command end: aborted with exception [039]
2022-04-18 14:53:17.859 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2022-04-18 14:53:17.859 P00  DEBUG:     common/lock::lockRelease: => true
2022-04-18 14:53:17.859 P00  DEBUG:     common/exit::exitSafe: => 39
2022-04-18 14:53:17.859 P00  DEBUG:     main::main: => 39
`

Running the same query by hand
`pgbackrest@pgbackup-0:~$ ssh postgres@testdb01 "psql -Aqtn -c 'select pg_catalog.pg_is_in_recovery();'"
f
Time: 0.425 ms
`

**Comment by jurim76** [comment] 2022-05-06 16:21
Perhaps ssh warning "Warning: Permanently added '' (ECDSA) to the list of known hosts." produces this error, will check again

**Comment by dwsteele** [comment] 2022-05-06 17:15
Yes, the SSH connections should be setup before running pgBackRest, as shown here: https://pgbackrest.org/user-guide.html#repo-host/setup-ssh.

**Comment by woblerr** [comment] 2022-06-22 13:49
We have the same issue.

@dwsteele  
What additional information would be useful?

<details>
<summary>Tail of debug backrest log</summary>
    
    2022-06-22 15:47:29.944 P00  DEBUG:     command/backup/backup::backupJobResult: (manifest: {Manifest}, host: {"dev-host"}, storagePg: {type: remote, path: {"/data/project/postgresql/data"}, write: false}, fileRemove: {[]}, job: {state: done, key: {"pg_data/base/16385/70803"}, command: {command: bp-f}, code: 0, message: null, result: {depth: 0, idLast: 0, tagNextId: 0, tagNextType: 0, tagNextValue 0}}, bundle: false, sizeTotal: 74884591095, sizeProgress: *16106127360)
    2022-06-22 15:47:29.944 P01 DETAIL: backup file dev-host:/data/project/postgresql/data/base/16385/70803 (1GB, 22%) checksum c3c5e3bfcfbcae18f13f88927badcdbbc7940fc3
    2022-06-22 15:47:29.944 P00  DEBUG:     command/backup/backup::backupJobResult: => void
    2022-06-22 15:47:29.946 P00  DEBUG:     command/backup/backup::backupDbPing: (backupData: {BackupData}, force: false)
    2022-06-22 15:47:29.946 P00  DEBUG:     db/db::dbPing: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'dev-host', state: idle}}, force: false)
    2022-06-22 15:47:29.946 P00  DEBUG:     db/db::dbIsInRecovery: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'dev-host', state: idle}})
    2022-06-22 15:47:29.946 P00  DEBUG:     db/db::dbQueryColumn: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'dev-host', state: idle}}, query: {"select pg_catalog.pg_is_in_recovery()"})
    2022-06-22 15:47:29.946 P00  DEBUG:     db/db::dbQuery: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'dev-host', state: idle}}, query: {"select pg_catalog.pg_is_in_recovery()"})
    2022-06-22 15:47:30.054 P00  DEBUG:     db/db::dbQuery: => {VariantList}
    2022-06-22 15:47:30.054 P00  DEBUG:     db/db::dbQueryColumn: => {false}
    2022-06-22 15:47:30.054 P00  DEBUG:     db/db::dbIsInRecovery: => false
    2022-06-22 15:47:30.054 P00  DEBUG:     db/db::dbPing: => void
    2022-06-22 15:47:30.054 P00  DEBUG:     command/backup/backup::backupDbPing: => void
    2022-06-22 15:47:30.054 P00  DEBUG:     command/backup/backup::backupManifestSaveCopy: (manifest: {Manifest})
    2022-06-22 15:47:30.054 P00  DEBUG:     storage/storage::storageNewWrite: (this: {type: s3, path: {"/path"}, write: true}, fileExp: {"<REPO:BACKUP>/20220619-010007F_20220622-010014D/backup.manifest.copy"}, param.modeFile: 0000, param.modePath: 0000, param.user: null, param.group: null, param.timeModified: 0, param.noCreatePath: false, param.noSyncFile: false, param.noSyncPath: false, param.noAtomic: false, param.compressible: false)
    2022-06-22 15:47:30.054 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: (this: {StorageS3}, file: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"})
    2022-06-22 15:47:30.055 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: => {type: s3, name: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
    2022-06-22 15:47:30.055 P00  DEBUG:     storage/storage::storageNewWrite: => {type: s3, name: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
    2022-06-22 15:47:30.055 P00  DEBUG:     info/manifest::manifestSave: (this: {Manifest}, write: {IoWrite})
    2022-06-22 15:47:30.057 P00  DEBUG:     info/info::infoSave: (this: {Info}, write: {IoWrite}, callbackFunction: (function *), callbackData: *void)
    2022-06-22 15:47:30.236 P00  DEBUG:     common/io/http/request::httpRequestProcess: retry KernelError: TLS syscall error: [32] Broken pipe
    2022-06-22 15:47:30.482 P00  DEBUG:     info/info::infoSave: => void
    2022-06-22 15:47:30.482 P00  DEBUG:     info/manifest::manifestSave: => void
    2022-06-22 15:47:30.482 P00  DEBUG:     command/backup/backup::backupManifestSaveCopy: => void
    2022-06-22 15:47:38.112 P00  DEBUG:     command/backup/backup::backupJobResult: (manifest: {Manifest}, host: {"dev-host"}, storagePg: {type: remote, path: {"/data/project/postgresql/data"}, write: false}, fileRemove: {[]}, job: {state: done, key: {"pg_data/base/16385/95779"}, command: {command: bp-f}, code: 0, message: null, result: {depth: 0, idLast: 0, tagNextId: 0, tagNextType: 0, tagNextValue 0}}, bundle: false, sizeTotal: 74884591095, sizeProgress: *17179869184)
    2022-06-22 15:47:38.112 P06 DETAIL: match file from prior backup dev-host:/data/project/postgresql/data/base/16385/95779 (1GB, 24%) checksum d0b487162611bd44585a0c9fc5d5c2ed69c3ea0e
    2022-06-22 15:47:38.112 P00  DEBUG:     command/backup/backup::backupJobResult: => void
    2022-06-22 15:47:38.114 P00  DEBUG:     command/backup/backup::backupDbPing: (backupData: {BackupData}, force: false)
    2022-06-22 15:47:38.114 P00  DEBUG:     db/db::dbPing: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'dev-host', state: idle}}, force: false)
    2022-06-22 15:47:38.114 P00  DEBUG:     db/db::dbPing: => void
    2022-06-22 15:47:38.114 P00  DEBUG:     command/backup/backup::backupDbPing: => void
    2022-06-22 15:47:38.114 P00  DEBUG:     command/backup/backup::backupManifestSaveCopy: (manifest: {Manifest})
    2022-06-22 15:47:38.114 P00  DEBUG:     storage/storage::storageNewWrite: (this: {type: s3, path: {"/path"}, write: true}, fileExp: {"<REPO:BACKUP>/20220619-010007F_20220622-010014D/backup.manifest.copy"}, param.modeFile: 0000, param.modePath: 0000, param.user: null, param.group: null, param.timeModified: 0, param.noCreatePath: false, param.noSyncFile: false, param.noSyncPath: false, param.noAtomic: false, param.compressible: false)
    2022-06-22 15:47:38.115 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: (this: {StorageS3}, file: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"})
    2022-06-22 15:47:38.115 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: => {type: s3, name: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
    2022-06-22 15:47:38.115 P00  DEBUG:     storage/storage::storageNewWrite: => {type: s3, name: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
    2022-06-22 15:47:38.115 P00  DEBUG:     info/manifest::manifestSave: (this: {Manifest}, write: {IoWrite})
    2022-06-22 15:47:38.116 P00  DEBUG:     info/info::infoSave: (this: {Info}, write: {IoWrite}, callbackFunction: (function *), callbackData: *void)
    2022-06-22 15:47:38.367 P00  DEBUG:     info/info::infoSave: => void
    2022-06-22 15:47:38.367 P00  DEBUG:     info/manifest::manifestSave: => void
    2022-06-22 15:47:38.367 P00  DEBUG:     command/backup/backup::backupManifestSaveCopy: => void
    2022-06-22 15:47:59.915 P00  DEBUG:     command/backup/backup::backupJobResult: (manifest: {Manifest}, host: {"dev-host"}, storagePg: {type: remote, path: {"/data/project/postgresql/data"}, write: false}, fileRemove: {[]}, job: {state: done, key: {"pg_data/base/16385/95779.7"}, command: {command: bp-f}, code: 0, message: null, result: {depth: 0, idLast: 0, tagNextId: 0, tagNextType: 0, tagNextValue 0}}, bundle: false, sizeTotal: 74884591095, sizeProgress: *18253611008)
    2022-06-22 15:47:59.915 P02 DETAIL: match file from prior backup dev-host:/data/project/postgresql/data/base/16385/95779.7 (1GB, 25%) checksum b4d08784cfdf4e62c82192795e3e419a7fcdaca5
    2022-06-22 15:47:59.915 P00  DEBUG:     command/backup/backup::backupJobResult: => void
    2022-06-22 15:47:59.917 P00  DEBUG:     command/backup/backup::backupDbPing: (backupData: {BackupData}, force: false)
    2022-06-22 15:47:59.917 P00  DEBUG:     db/db::dbPing: (this: {client: null, remoteClient: {name: remote-0 ssh protocol on 'dev-host', state: idle}}, force: false)
    2022-06-22 15:47:59.917 P00  DEBUG:     db/db::dbPing: => void
    2022-06-22 15:47:59.917 P00  DEBUG:     command/backup/backup::backupDbPing: => void
    2022-06-22 15:47:59.917 P00  DEBUG:     command/backup/backup::backupManifestSaveCopy: (manifest: {Manifest})
    2022-06-22 15:47:59.917 P00  DEBUG:     storage/storage::storageNewWrite: (this: {type: s3, path: {"/path"}, write: true}, fileExp: {"<REPO:BACKUP>/20220619-010007F_20220622-010014D/backup.manifest.copy"}, param.modeFile: 0000, param.modePath: 0000, param.user: null, param.group: null, param.timeModified: 0, param.noCreatePath: false, param.noSyncFile: false, param.noSyncPath: false, param.noAtomic: false, param.compressible: false)
    2022-06-22 15:47:59.918 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: (this: {StorageS3}, file: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"})
    2022-06-22 15:47:59.918 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: => {type: s3, name: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
    2022-06-22 15:47:59.918 P00  DEBUG:     storage/storage::storageNewWrite: => {type: s3, name: {"/path/backup/stanza-name/20220619-010007F_20220622-010014D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
    2022-06-22 15:47:59.918 P00  DEBUG:     info/manifest::manifestSave: (this: {Manifest}, write: {IoWrite})
    2022-06-22 15:47:59.920 P00  DEBUG:     info/info::infoSave: (this: {Info}, write: {IoWrite}, callbackFunction: (function *), callbackData: *void)
    2022-06-22 15:48:00.223 P00  DEBUG:     info/info::infoSave: => void
    2022-06-22 15:48:00.223 P00  DEBUG:     info/manifest::manifestSave: => void
    2022-06-22 15:48:00.223 P00  DEBUG:     command/backup/backup::backupManifestSaveCopy: => void
    2022-06-22 15:54:26.719 P00  DEBUG:     command/backup/backup::backupJobResult: (manifest: {Manifest}, host: {"dev-host"}, storagePg: {type: remote, path: {"/data/project/postgresql/data"}, write: false}, fileRemove: {[]}, job: {state: done, key: {"pg_data/base/16385/95779.5"}, command: {command: bp-f}, code: 39, message: {"raised from local-5 protocol: client state is 'data-get' but expected 'idle'"}, result: null}, bundle: false, sizeTotal: 74884591095, sizeProgress: *19327352832)
    2022-06-22 15:54:26.734 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
    2022-06-22 15:54:26.734 P00  ERROR: [039]: raised from local-5 protocol: client state is 'data-get' but expected 'idle'
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:
                                    
                                    version: 2.38
                                    command: backup
                                    options: --archive-copy --archive-timeout=180 --compress-level=8 --delta --exec-id=15125-2717df3a --no-expire-auto --io-timeout=360 --log-level-console=debug --log-level-file=debug --log-path=/var/log/pathbackrest --pg1-host=dev-host --pg1-path=/data/project/postgresql/data --process-max=6 --repo1-path=/path --repo1-retention-diff=14 --repo1-retention-full=2 --repo1-s3-bucket=<redacted> --repo1-s3-endpoint=<redacted> --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=eu-west-3 --repo1-storage-port=443 --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=stanza-name --start-fast --type=diff
                                    
                                    stack trace:
                                    command/backup/backup.c:backupJobResult:1329:(manifest: {Manifest}, host: {"dev-host"}, storagePg: {type: remote, path: {"/data/project/postgresql/data"}, write: false}, fileRemove: {[]}, job: {state: done, key: {"pg_data/base/16385/95779.5"}, command: {command: bp-f}, code: 39, message: {"raised from local-5 protocol: client state is 'data-get' but expected 'idle'"}, result: null}, bundle: false, sizeTotal: 74884591095, sizeProgress: *19327352832)
                                    command/backup/backup.c:backupProcess:(backupData: {BackupData}, manifest: {Manifest}, lsnStart: {"218/D7050B30"})
                                    command/backup/backup.c:cmdBackup:(void)
                                    main.c:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------
</details>

**Comment by dwsteele** [comment] 2022-06-29 12:14
The only idea we have at this point is to use TLS instead of SSH. The SSH connection can be noisy because the system can write random message into it, which breaks the protocol exchange. TLS does not have this issue.

**Comment by mindrunner** [comment] 2022-07-12 10:44
> I am in the same boat. I have two more or less identical k8s clusters with tsdb backup configured to an s3 endpoint via `minio` acting as an s3 gateway (indefinite storage). My `TEST` instance has no issues, but `PROD` always fails backups with above mentioned error.

I switched to native azure storage for pgbackrest now to make sure it is not an `minio` issue. Problem still persists.


Posted a bug here as well: (Probably wrong location)
https://github.com/timescale/timescaledb-kubernetes/issues/393

**Comment by dwsteele** [comment] 2022-08-31 17:01
We believe that the errors being presented here are not the original error, but are generate during cleanup after the original error. 0f7b6a3344b6 should help with this by avoiding cleanup when an error will lead to an exit so that the original error will be reported.

Closing this for now, but please let us know if you see this error in >= 2.41.

**Closed by dwsteele** 2022-08-31 17:01 UTC
Labels: bug, module [core]
