### ISSUE TITLE
pgbackrest built with gcc-9 segfault

### ISSUE THREAD

**Issue by chrlange** [pgbackrest/pgbackrest#762] opened 2019-06-28 07:21 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.15 and 2.15dev

2. PostgreSQL version:
10.9

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu Linux 18.04.2 and Fedory 30

4. Did you install pgBackRest from source or from a package?
both

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

It seems that GCC-9 removes assignments of constants at the end of blocks under some circumstances. This leads to a segfault when pgbackrest is compiled with GCC-9.

In pgbackrest this happens at least in command/help/help.c, where the local variable `more` is assigned part of the help test in `helpRender()`, and in the configuration file parser with values assigned to ` dependValue` in function `configParse()`

I noticed the issue after updating a machine from Fedora 29 to 30 when the backup failed with a segfault. Postgresql and pgbackrest on that machine a installed from the postgresql repositories.

Investigating the issue I found that the output of pgbackrest without parameters shows 
`Use 'pgbackrest help (null)' for more information.'` as the last line. After noticing the (null) instead of [command] I compiled with `-fsanitize=address` which led me to the assignments in help.c. 

The default GCC on Fedora 30 is GCC-9, recompiling with clang-8 resulted in a functioning binary.  Disabling optimizations seems to solve this as well.

Running pgbackrest compiled on a machine running Ubuntu 18.04.2 with gcc-9 installed from the jonathonf PPA showed the same errors, so I suspect a compiler problem.

**Comment by dwsteele** [comment] 2019-06-28 13:50
> It seems that GCC-9 removes assignments of constants at the end of blocks under some circumstances. This leads to a segfault when pgbackrest is compiled with GCC-9.

I have confirmed this on Fedora 30.  Disabling optimizations or moving the assignment to the top of the block "fixes" the issue in `help.c`.

The `StringConst` struct gets created (shown after pre-processing):
```
more = ((const String *)&(const StringConst){.buffer = (char *)("[command]"), .size = (unsigned int)sizeof("[command]") - 1});
```
But `.buffer` is left NULL:
```
strCatFmt(result, "\nmore = %p, more.buffer = %p\n", more, ((StringConst *)more)->buffer);
> more = 0x7ffd2692c240, more.buffer = (nil)
```

This certainly seems like a compiler bug to me and it looks like we'll need to address it if PGDG is distributing binaries that segfault.

**Comment by crigler** [comment] 2019-06-28 15:18
The GCC folks say that this is not a compiler bug and that pgbackrest is invoking undefined behavior. See 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91031

**Comment by dwsteele** [comment] 2019-06-28 15:23
Yeah, we've figured that out on our own.  We were still trying to figure out why the code worked on any compiler, but this explains it.

**Comment by dwsteele** [comment] 2019-07-09 20:50
This has been fixed in fc2101352206a.  The good news is that valgrind will catch these errors under gcc9.  We were never intentionally depending on this "feature", just a few instances slipped through our testing since they were not being caught by valgrind.

We are not prepared to add gcc9 to our test suite at this point, so it's possible some errors like this could crop up again before we do.  We're happy to fix anything that gets reported, though.

@chrlange, if you would like your name in the release notes rather than "chrlange" just let us know.

**Closed by dwsteele** 2019-07-09 20:50 UTC
Labels: bug (code)

**Comment by chrlange** [comment] 2019-07-10 07:52
@dwsteele, yes, please use my name in the release notes. I finally managed to update at least that part of my profile.

**Comment by dwsteele** [comment] 2019-07-10 11:05
@chrlange updated, a22a6dc08c25a2af.  Thanks!

**Comment by dwsteele** [comment] 2019-10-09 19:29
gcc 9 has now been added to our test suite at 7f369006b5c.
