### ISSUE TITLE
Scheduling a backup in crontab writes to wrong log directory

### ISSUE THREAD

**Issue by fillesten** [pgbackrest/pgbackrest#2350] opened 2024-05-17 07:54 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.44

2. PostgreSQL version:
postgres (PostgreSQL) 15.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
cat /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    pgbackrest.conf file:

[global]
log-level-console=info

[infra12]
repo1-cipher-pass=repo1Cihperpassqwsddgxvc
repo1-cipher-type=aes-256-cbc
repo1-retention-full=2
repo1-retention-diff=15
pg1-path=/srv/pgsql/data
repo1-path=/srv/pgsql/pgbackrest

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_mode = on             
archive_command = 'test ! -f /srv/pgsql/archivedir/%f && cp %p /srv/pgsql/archivedir/%f; pgbackrest --stanza=infra12 archive-push %p'
archive_timeout = 7200
max_wal_senders = 10
listen_addresses = '*'
wal_level = replica 
#port = 5432

    - errors in the postgresql log file before or during the time you experienced the issue
No errors in postgres logs 
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
This is my issue: the log files write to /var/log/pgbackrest, more information below.

7. Describe the issue:
My current setup consists of scheduling a crontab job of a simple script which checks for potential errors and runs the command: 
pgbackrest --stanza=infra12 --type=diff backup

this is my crontab file, it runs the diff backup every 5 minutes
##### crontab #####
*/5     *       *       *       *               /home/postgres/scripts/backup/backup.sh diff 
##### crontab #####

everything executes without any errors.
However, I have manually set the destination for the log files, $ pgbackrest  help backup log-path
2024-05-17 09:47:43.793 P00   INFO: backup command begin 2.44: [log-path] --exec-id=32655-f724284d --log-level-console=info --log-path=/home/postgres/log/backup/pgbackrest
pgBackRest 2.44 - 'backup' command - 'log-path' option help

Path where log files are stored.

The log path provides a location for pgBackRest to store log files. Note that
if log-level-file=off then no log path is required.

current: /home/postgres/log/backup/pgbackrest
default: /var/log/pgbackrest
2024-05-17 09:47:43.798 P00   INFO: backup command end: completed successfully (6ms)

Now for the issue, whenever i manually run the command $ pgbackrest --stanza=infra12 --type=diff backup
using either the script or the command directly the logs get correctly placed in /home/postgres/log/backup/pgbackrest. 
But when the cron job runs the script it for some reason ignores the current log path and writes the logs to /var/log/pgbackrest

/var/log/pgbackrest $ ls -l
total 512
-rw-r--r-- 1 postgres postgres 314674 May 17 09:45 infra12-backup.log
-rw-r--r-- 1 postgres postgres 156128 May 17 09:45 infra12-expire.log

/var/log/pgbackrest $ ls -l
total 512
-rw-r--r-- 1 postgres postgres 316045 May 17 09:50 infra12-backup.log
-rw-r--r-- 1 postgres postgres 156810 May 17 09:50 infra12-expire.log

This gets updated from the cronjob but when i now run the script manually the correct logs will be updated 

## before backup ##
~/log/backup/pgbackrest $ ls -l
total 100
-rw-r----- 1 postgres postgres 54084 May 17 09:38 infra12-backup.log
-rw-r----- 1 postgres postgres 20844 May 17 09:38 infra12-expire.log
-rw-r----- 1 postgres postgres  4205 May  8 08:20 infra12-restore.log
-rw-r----- 1 postgres postgres  3770 May  2 12:14 infra12-stanza-create.log

##backup command ##
2024-05-17 09:52:05.814 P00   INFO: backup command begin 2.44: --exec-id=32971-0ee7f3e7 --log-level-console=info --log-path=/home/postgres/log/backup/pgbackrest --pg1-path=/srv/pgsql/data --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/srv/pgsql/pgbackrest --repo1-retention-diff=15 --repo1-retention-full=2 --stanza=infra12 --type=diff
2024-05-17 09:52:06.543 P00   INFO: last backup label = 20240517-090102F, version = 2.44
2024-05-17 09:52:06.543 P00   INFO: execute non-exclusive backup start: backup begins after the next regular checkpoint completes
2024-05-17 09:52:06.848 P00   INFO: backup start archive = 0000000500000007000000B2, lsn = 7/B2000028
2024-05-17 09:52:06.848 P00   INFO: check archive for prior segment 0000000500000007000000B1
2024-05-17 09:52:07.191 P00   INFO: execute non-exclusive backup stop and wait for all WAL segments to archive
2024-05-17 09:52:07.396 P00   INFO: backup stop archive = 0000000500000007000000B2, lsn = 7/B2000100
2024-05-17 09:52:07.398 P00   INFO: check archive for segment(s) 0000000500000007000000B2:0000000500000007000000B2
2024-05-17 09:52:07.541 P00   INFO: new backup label = 20240517-090102F_20240517-095206D
2024-05-17 09:52:07.592 P00   INFO: diff backup size = 249.3KB, file total = 1622
2024-05-17 09:52:07.592 P00   INFO: backup command end: completed successfully (1779ms)
2024-05-17 09:52:07.593 P00   INFO: expire command begin 2.44: --exec-id=32971-0ee7f3e7 --log-level-console=info --log-path=/home/postgres/log/backup/pgbackrest --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/srv/pgsql/pgbackrest --repo1-retention-diff=15 --repo1-retention-full=2 --stanza=infra12
2024-05-17 09:52:07.596 P00   INFO: repo1: expire diff backup 20240517-080102F_20240517-085502D
2024-05-17 09:52:07.599 P00   INFO: repo1: remove expired backup 20240517-080102F_20240517-085502D
2024-05-17 09:52:07.605 P00   INFO: repo1: 15-1 no archive to remove

## after backup ## 
 ls -l
total 100
-rw-r----- 1 postgres postgres 55503 May 17 09:52 infra12-backup.log
-rw-r----- 1 postgres postgres 21574 May 17 09:52 infra12-expire.log
-rw-r----- 1 postgres postgres  4205 May  8 08:20 infra12-restore.log
-rw-r----- 1 postgres postgres  3770 May  2 12:14 infra12-stanza-create.log

**Comment by pgstef** [comment] 2024-05-17 08:09
Hi,

>     1. pgBackRest version:
>        pgBackRest 2.44

That's more than 1 year old release. Does it reproduce on latest release?

> this is my crontab file, it runs the diff backup every 5 minutes
> ##### crontab
> 
> */5 * * * * /home/postgres/scripts/backup/backup.sh diff
> ##### crontab

Ouch. Why do you run it that often? Typically once every day is largely enough given you have the WAL archives for PITR.

> However, I have manually set the destination for the log files

How did you do that exactly? It is not in the config file.

> Now for the issue, whenever i manually run the command $ pgbackrest --stanza=infra12 --type=diff backup using either the script or the command directly the logs get correctly placed in /home/postgres/log/backup/pgbackrest. But when the cron job runs the script it for some reason ignores the current log path and writes the logs to /var/log/pgbackrest

It totally depends on how you've setup that parameter in the first place. Given it is not in your config file, if you don't force it on the command line, it might sound like you used environment variables for this (and cron usually doesn't load user profile, but that would be a SLES problem, not a pgBackRest one).

> 2024-05-17 09:52:05.814 P00 INFO: backup command begin 2.44: --exec-id=32971-0ee7f3e7 --log-level-console=info --log-path=/home/postgres/log/backup/pgbackrest --pg1-path=/srv/pgsql/data --repo1-cipher-pass= --repo1-cipher-type=aes-256-cbc --repo1-path=/srv/pgsql/pgbackrest --repo1-retention-diff=15 --repo1-retention-full=2 --stanza=infra12 --type=diff

I guess this output comes from a manual run. I'm pretty sure the log-path will be different if you look at the log from the cron run.

Ultimately I think it all depends on how you've configured that log path.

Regards

**Comment by pgstef** [comment] 2024-05-17 09:28
> I followed this guide: https://pgbackrest.org/user-guide-rhel.html#quickstart/configure-stanza where it exports PGBACKREST_LOG_PATH.

This was just an example: illustration that you have various possibilities to configure the settings. Ultimately, you have an order: command-line options override environment options which override config file options.

> Ok, so it is possible to set the log path in the config file. I assume i can set the log path under [global] but in case of multiple stanzas it is better to define the log path for each individually.

The logs will have the stanza name including in the file names. I tend to think it would be easier for maintenance to keep the log-path federated and in the `[global]` section. But that choice is up to you.

Anyway, I think we can close this issue now since it was related to the setting being defined in env variable :-)

**Closed** 2024-05-17 21:47 UTC
Labels: question
