### ISSUE TITLE
ERROR: [029]: raised from local-1 protocol: block map version must be zero

### ISSUE THREAD

**Issue by threenotrump** [pgbackrest/pgbackrest#2182] opened 2023-09-15 15:07 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.47

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos 7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[global]
repo1-path=/backups/repo
repo-cipher-pass=xyz
repo-cipher-type=aes-256-cbc
process-max=2
start-fast=y
backup-standby=y
compress-type=lz4
repo1-bundle=y
repo1-bundle-limit=10MiB
repo1-bundle-size=50MiB
repo1-block=y

[test_stanza]
pg1-host=1.1.1.1
pg1-path=/var/lib/pgsql/14/data
repo1-retention-full=15
repo1-retention-full-type=time
pg2-host=1.1.1.2
pg2-path=/var/lib/pgsql/14/data

7. Describe the issue: 
Hi 

First thank you for this awesome software. Unfortunately I get some errors while restoring database testing file bundling and block level incremental backups.

Here are the errors:

ASSERT: [025]: raised from local-1 protocol: cannot get index 10 from list with 6 value(s)
        --------------------------------------------------------------------
        If SUBMITTING AN ISSUE please provide the following information:

        version: 2.47
        command: restore
        options: --archive-mode=off --delta --exec-id=21046-429652e0 --log-level-console=detail --log-level-file=detail --pg1-path=/var/lib/pgsql/14/data --process-max=2 --repo1-host=1.1.1.1 --stanza=test_stanza --tablespace-map=xyz=/xyz

        stack trace:
        common/type/list.c:lstGet:150:(test build required for parameters)
            ... function(s) omitted ...
        command/restore/file.c:restoreFile:(debug log level required for parameters)
        command/restore/protocol.c:restoreFileProtocol:(debug log level required for parameters)
        protocol/server.c:protocolServerProcess:(debug log level required for parameters)
        command/local/local.c:cmdLocal:(debug log level required for parameters)
        main.c:main:(debug log level required for parameters)
        --------------------------------------------------------------------
2023-09-15 08:03:23.894 P00   INFO: restore command end: aborted with exception [025]

This is another error:

023-09-15 14:53:10.529 P00  DEBUG:     command/exit::exitSafe: (result: 0, error: true, signalType: 0)
ERROR: [029]: raised from local-1 protocol: block map version must be zero
       [FormatError] on retry after 3653ms: [same message]
       [FormatError] on retry after 19963ms: [same message]
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:

       version: 2.47
       command: restore
       options: --archive-mode=off --delta --exec-id=28717-451e89a4 --log-level-console=debug --log-level-file=detail --pg1-path=/var/lib/pgsql/14/data --process-max=2 --repo1-host=1.1.1.1 --stanza=uat --tablespace-map=xyz=/xyz

       stack trace:
       command/restore/restore.c:restoreJobResult:2244:(manifest: {Manifest}, job: {state: done, key: {4}, command: {name: rs-f}, result: nullcode: 29, message: {"raised from local-1 protocol: block map version must be zero
       [FormatError] on retry after 3653ms: [same message]
       [FormatError] on retry after 19963ms: [same message]"}}, zeroExp: null, sizeTotal: 122581670344, sizeRestored: 122115545544)
       command/restore/restore.c:cmdRestore:(void)
       main.c:main:(debug log level required for parameters)
       --------------------------------------------------------------------

If I run the restore command with delta second or third time sometimes restore is successful.

**Comment by dwsteele** [comment] 2023-09-15 17:02
Does the `verify` command report any errors on this repo?

**Comment by threenotrump** [comment] 2023-09-15 17:20
> Does the `verify` command report any errors on this repo?

This is a test repo so I deleted stanza and removed repo1-bundle,repo1-bundle-limit,repo1-bundle-size,repo1-block parameters and restore works as expected. I will try with these parameters this weekend and return to you.

**Comment by threenotrump** [comment] 2023-09-15 20:42
I rebuild the stanza with repo1-bundle,repo1-bundle-limit,repo1-bundle-size,repo1-block above and I had the error below:

ERROR: [029]: raised from local-2 protocol: block map version must be zero
       [FormatError] on retry after 59ms: [same message]
       [FormatError] on retry after 15077ms: [same message]
2023-09-15 20:37:31.948 P00   INFO: restore command end: aborted with exception [029]

Verify command output: 

```
pgbackrest --stanza=test_stanza verify --output=text --verbose=y
stanza: test_stanza
status: ok
  archiveId: 14-1, total WAL checked: 16, total valid WAL: 16
    missing: 0, checksum invalid: 0, size invalid: 0, other: 0
  backup: 20230915-175052F, status: valid, total files checked: 8228, total valid files: 8228
    missing: 0, checksum invalid: 0, size invalid: 0, other: 0
  backup: 20230915-175052F_20230915-180219I, status: valid, total files checked: 8228, total valid files: 8228
    missing: 0, checksum invalid: 0, size invalid: 0, other: 0
  backup: 20230915-175052F_20230915-180314I, status: valid, total files checked: 8228, total valid files: 8228
    missing: 0, checksum invalid: 0, size invalid: 0, other: 0
  backup: 20230915-175052F_20230915-180605I, status: valid, total files checked: 8228, total valid files: 8228
    missing: 0, checksum invalid: 0, size invalid: 0, other: 0
```

**Comment by dwsteele** [comment] 2023-09-15 21:01
Can you run the restore with `--log-level-console=debug` and provide the last 1000 lines or so?

**Comment by threenotrump** [comment] 2023-09-16 10:04
[debug.txt](https://github.com/pgbackrest/pgbackrest/files/12640375/debug.txt)

Hi Mr Steele

Last 1000 lines of log with log leve debug is attached

**Comment by dwsteele** [comment] 2023-09-16 14:21
I still can't see which file is causing the issue. Please add `--log-level-file=debug --log-subprocess` to the restore. When the error occurs look for the log file [stanza]-restore-local-XXX.log where XXX is the local process where the error occurred (001 in the error you posted). Send at least the last 10,000 lines of that log along with the last 1,000 lines of the main restore log (as you did before). Thanks!

**Comment by threenotrump** [comment] 2023-09-16 16:07
I get only one logfile but it is significantly bigger and at the end it say missing file maybe this one helps you.  This is the whole logfile.
[pg_debug.zip](https://github.com/pgbackrest/pgbackrest/files/12641102/pg_debug.zip)

**Comment by dwsteele** [comment] 2023-09-16 17:29
Two different errors, that's interesting...

Looks like you missed `--log-level-file=debug`. Can you try again with both: `--log-level-file=debug --log-subprocess`?  Then look for the log file [stanza]-restore-local-XXX.log where XXX is the local process where the error occurred (002 in the error you just posted)

Are all the hosts the same OS and architecture?

Also, can you send us `/backups/repo/backup/test_stanza/20230915-175052F_20230916-010002I/backup.manifest`?

**Comment by threenotrump** [comment] 2023-09-16 18:29
I used the command:

`pgbackrest --stanza=test_stanza  --delta   restore --log-level-console=debug --log-level-file=debug --log-subprocess --archive-mode=off --tablespace-map=bldata=/backups/bldata --process-max=2 &> pg_debug.txt`

And it only produced one file. Am I missing something?

I am having a hard time decrypting backup manifest. Could you help?

I use the command : 

` openssl enc -d -aes-256-cbc -nopad -in backup.manifest`

It produces unreadable file.

**Comment by dwsteele** [comment] 2023-09-16 20:55
> And it only produced one file. Am I missing something?

The process log file we are looking for will be located in `/var/log/pgbackrest`. Look for the log file [stanza]-restore-local-XXX.log where XXX is the local process where the error occurred 

> I am having a hard time decrypting backup manifest

You can do this with pgbackrest:
```
pgbackrest repo-get backup/test_stanza/20230915-175052F_20230916-010002I/backup.manifest > test-manifest
```

**Comment by threenotrump** [comment] 2023-09-17 13:27
Hi again sorry for my clumsiness. I found out logs and decrypt the manifes. They are attached.
[logs.zip](https://github.com/pgbackrest/pgbackrest/files/12642922/logs.zip)

I tried to restore to produce the error but at first attempt it was successful. Then I took an incremental backup and produced the error attached. I hop it helps.

**Comment by dwsteele** [comment] 2023-09-17 13:41
`test_stanza-restore-local-002_last10000.log` doesn't contain the info we need. I think maybe pgbackrest was run again after the `block map version must be zero` error happened. Can you just compress and send the entire `test_stanza-restore-local-002.log` file?

**Comment by threenotrump** [comment] 2023-09-17 16:08
[test_stanza-restore-local-002.zip](https://github.com/pgbackrest/pgbackrest/files/12643220/test_stanza-restore-local-002.zip)
Full log is attached.

**Comment by dwsteele** [comment] 2023-09-17 17:36
Thanks for that! This restore is based on a newer backup that we don't have a manifest for. Can we get the manifest for `20230917-010004F_20230917-074553I`:
```
pgbackrest repo-get backup/test_stanza/20230917-010004F_20230917-074553I/backup.manifest > test-manifest
```

**Comment by threenotrump** [comment] 2023-09-17 17:52
[test-manifest.zip](https://github.com/pgbackrest/pgbackrest/files/12643380/test-manifest.zip)
Attached.

**Comment by dwsteele** [comment] 2023-09-17 18:26
This is the `20230915-175052F_20230916-010002I` manifest, but we are looking for the `20230917-010004F_20230917-074553I` manifest:
```
pgbackrest repo-get backup/test_stanza/20230917-010004F_20230917-074553I/backup.manifest > 20230917-010004F_20230917-074553I.manifest
```

**Comment by threenotrump** [comment] 2023-09-17 18:45
[20230917-010004F_20230917-074553I.zip](https://github.com/pgbackrest/pgbackrest/files/12643479/20230917-010004F_20230917-074553I.zip)
Attached.

**Comment by dwsteele** [comment] 2023-09-17 19:28
OK -- now I have the log and the manifest matching up. I'd like to get a detailed report on the file that seems to be causing the issue:
```
pgbackrest --stanza=test_stanza manifest --set=20230917-010004F_20230917-074553I --filter=pg_tblspc/16385/PG_14_202107181/40663614/40670366_fsm
```
This might throw an error -- but just capture whatever output you get.

**Comment by threenotrump** [comment] 2023-09-17 19:32
output:
`ASSERT: [025]: unable to find 'pg_data/pg_tblspc/16385/PG_14_202107181/40663614/40670366_fsm' in manifest file list
        --------------------------------------------------------------------
        If SUBMITTING AN ISSUE please provide the following information:

        version: 2.47
        command: manifest
        options: --exec-id=25379-41e5b658 --filter=pg_tblspc/16385/PG_14_202107181/40663614/40670366_fsm --pg1-host=1.1.1.1 --pg2-host=1.1.1.2 --pg1-path=/var/lib/pgsql/14/data --pg2-path=/var/lib/pgsql/14/data --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/backups/repo --set=20230917-010004F_20230917-074553I --stanza=test_stanza

        stack trace:
        info/manifest.c:manifestFilePackFindInternal:3003:(test build required for parameters)
            ... function(s) omitted ...
        command/manifest/manifest.c:cmdManifestRender:(debug log level required for parameters)
        command/manifest/manifest.c:cmdManifest:(debug log level required for parameters)
        main.c:main:(debug log level required for parameters)
        --------------------------------------------------------------------`

**Comment by dwsteele** [comment] 2023-09-18 17:06
@threenotrump Thank you so much for working with me on this over the weekend. With the information you provided I was able to reproduce the issue and create a fix. See #2184.

This looks like a test env, so if you are able to test the fix that would be great, but I'm pretty sure this will address your issue.

Closing this issue since there is a PR, but feel free to respond in the PR or this issue.

**Comment by dwsteele** [comment] 2023-09-18 18:02
The branch is in my repo: https://github.com/dwsteele/pgbackrest/tree/dev-bi-bug

**Comment by dwsteele** [comment] 2023-09-18 18:03
Remember that you'll need to deploy this on the repo and pg hosts -- assuming non of these are production.

**Closed** 2023-09-18 19:10 UTC
Labels: bug, module [core]

**Comment by dwsteele** [comment] 2023-09-18 19:14
@threenotrump Also let us know how you would like your name to appear in the release notes (right now I have `threenotrump`, which is also fine).

**Comment by threenotrump** [comment] 2023-09-18 22:47
It would be nice if you would use "Burak Yurdakul".

I tried couple of restores with your branch and all are successful.

I have two questions:

Is there a timetable for 2.48 release?

If I would start without file bundling and block level incremental, enable these later with 2.48 release would this change create any problems?
