### ISSUE TITLE
Enhancement request:  Add support for S3-CMK (SSE-C)

### ISSUE THREAD

**Issue by udf2457** [pgbackrest/pgbackrest#2279] opened 2024-02-08 14:43 UTC
My understanding is that a present pgbackrest only supports SSE-S3 and SSE-KMS modes of encryption.

Please add support for SSE-C mode whereby the key can be provided client-side, i.e. by pgbackrest (https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html).

This is important for two reasons:

 1. sometimes regulatory or contractual reasons means that it is not possible to trust the cloud provider key management (or there are requirements for segregation of duties whereby the cloud provider cannot be both the data store and the key store)
 2. there are implementations of S3 out there that only support SSE-C mode, for example Exosale Simple Object Storage: https://community.exoscale.com/documentation/storage/encryption/

**Comment by dwsteele** [comment] 2024-02-09 15:03
It's hard to see how this is better than just using pgBackRest encryption: https://pgbackrest.org/user-guide.html#quickstart/configure-encryption.

It is probably not something that we'll work on (at least for now) but we would very likely accept a patch.

**Comment by udf2457** [comment] 2024-02-09 15:36
Fair enough.

Unfortunatley I don't speak C, otherwise I would. 😉

**Comment by dwsteele** [comment] 2024-02-11 12:45
> Unfortunatley I don't speak C, otherwise I would. 

Well, even if you just hacked it up that would be fine. The biggest barrier for us is setting up a test env that correctly reproduces what you want to do.

If you can hack up storage/s3/storage.c to do what you need, we can make it pretty and write unit tests, then have you retest the final result.

**Comment by udf2457** [comment] 2024-02-11 14:15
I know what you mean.  

In Go it's easy because you can just embed `minio` to mock up any S3 stuff.

The other thing that came to mind was `testcontainers` but looking at their website they don't have `c` integration.

I'll have a look at `storage.c` and see if it looks feasible.

**Comment by dwsteele** [comment] 2024-02-11 14:54
Basically, you need to put your parameters here: https://github.com/pgbackrest/pgbackrest/blob/main/src/storage/s3/storage.c#L491. Doesn't matter if you hard-code them -- we'll add the proper options later.

If you can get that to work, submit a PR with what you have (remember to redact the hard-coded key) and we'll have a look.

**Comment by dwsteele** [comment] 2024-02-11 14:57
> In Go it's easy because you can just embed minio to mock up any S3 stuff.

We have a way to mock up anything we want -- including features not supported by Minio. But first we need a working implementation.

**Comment by dwsteele** [comment] 2024-03-10 22:39
Closing this since there is PR #2282.

**Closed by dwsteele** 2024-03-10 22:39 UTC
Labels: module [core], enhancement

**Comment by udf2457** [comment] 2024-05-19 13:54
@dwsteele From a purely selfish self-interested perspective, is there a milestone for this to reach packaging ? 😉

**Comment by dwsteele** [comment] 2024-05-19 22:19
@udf2457 The next release is May 27.

**Comment by udf2457** [comment] 2024-05-20 17:39
Thanks @dwsteele I'm like the kid waiting for santa ! 🤣
