### ISSUE TITLE
Log Level INFO: backup file

### ISSUE THREAD

**Issue by jwpit** [pgbackrest/pgbackrest#1277] opened 2021-01-18 11:36 UTC
Hi David,
please consider to move the _INFO: backup file_ log into log level detail.
It heavily bloats the logs.
Rgds, Jens

**Comment by cmwshang** [comment] 2021-01-19 13:43
Thank you for the suggestion. Is there a specific reason for you request? Maybe you had trouble finding something in the log or some other reason?

**Comment by dwsteele** [comment] 2021-01-19 13:50
He is likely just concerned about how much space is uses. There is valuable data at the INFO level but the per-file messages might be too much for that level, esp if you have a cluster with a lot of files.

I have considered this before. My only concern is that we have been logging this way for a long time so it might come as a shock to some people.

**Comment by pgstef** [comment] 2021-01-19 14:05
I usually set console level to info and file level to debug. Then I have to `|grep P00` in command line to avoid spamming the console output. In that case, disk space isn't really a concern.

So moving this info to detail would be handy in the console output and offer a disk space log reduction too for people using file level to info.

I'm not sure it would be a big problem if announced properly in the release notes... Personally, I would appreciate this modification but I can still live with my `grep` too ;-)

**Comment by sfrost** [comment] 2021-01-19 17:25
Having this information has actually been pretty valuable when debugging issues, so I'm not really sure that I agree with having it not be included by default and it seems a bit odd that it would really be a disk space concern to me...

If everyone else feels that we don't need it then I suppose we could move it to detail.  I get that the information could be pulled from other files in the repo but that's not always as easy or simple to get at when trying to help someone figure out an issue as "send the pgbackrest log files"...

**Comment by pgstef** [comment] 2021-01-20 06:59
Very good point indeed @sfrost. And we probably don't want to set log-level-file to detail by default.

Perhaps we could adjust `LOG_INFO_PID_FMT` or `LOG_DETAIL_PID_FMT` according to how the user configured log-level-file. I mean keep info if log-level-file is info, switch to detail if log-level-file is detail or higher ? But this seems overly complicated when a simple `|grep P00` is enough in command-line. 

I probably miss the initial ambition of this request though.

**Comment by dwsteele** [comment] 2021-01-21 13:25
I'm not sure how useful this information is for debugging (without additional debug messages). With any degree of parallelism you won't know which file generated an error unless the error message provides that info (it generally does).

@jwpit hasn't really said whether the issue is disk space used, difficult searching the logs, or both.

**Comment by jwpit** [comment] 2021-01-21 14:11
It's disk space usage.
It's not really an issue but i had the idea that the log level might be just set wrong by mistake.

**Comment by dwsteele** [comment] 2021-01-21 15:48
It's not a mistake. Files *actually* copied during a backup or restore are logged at info level. Files linked to prior backups, checksum delta'd etc., are logged at detail level.

**Comment by turnstep** [comment] 2021-07-02 18:42
Came here to suggest a similar issue. Having the `INFO: backup file ...` is just a little too noisy for regular use, but there is so much useful other INFO information. Maybe some other new log-level that's just a little less verbose than info is?

**Comment by dwsteele** [comment] 2021-07-07 14:32
@turnstep `detail` is the lower log level we use for other messages like this. I'm fine with making the change. Personally, I have my backups send an email once a week when the full backup is made and I'd be happy for that to be smaller.

Should we also do the same for `restore` while we are at it?

**Comment by turnstep** [comment] 2021-07-07 20:36
To be clear, you mean moving the "backup file" lines from INFO to DETAIL? I'm fine with that too, if so.

**Comment by dwsteele** [comment] 2021-07-07 20:47
My proposal is to move `backup file ...` and `restore file ...` lines to `detail` level.

**Comment by pgstef** [comment] 2021-07-08 06:49
> My proposal is to move `backup file ...` and `restore file ...` lines to `detail` level.

Behavior consistency between both commands seems indeed nice to have to me. So +1 for your proposal :-)

The INFO output will become way less verbose and way more interesting to enable by default. Couldn't we consider raising defaults `log-level-console` to info and `log-level-file` to detail then ? If warned properly in the release notes, users who specifically want to reduce log verbosity can adjust their configs, but it will be much more user-friendly for new-comers imho

**Comment by dwsteele** [comment] 2021-07-08 16:20
> Couldn't we consider raising defaults log-level-console to info and log-level-file to detail then?

I would rather not. File-level logging for async archive-get and archive-push are already at detail level so that would make those logs more noisy. In any case I think that should be considered as a separate change.

I have created PR #1455 to reduce the log level for backup/restore file message. All are welcome to review/comment.

**Closed by dwsteele** 2021-07-08 16:20 UTC
Labels: enhancement, module [core]
