### ISSUE TITLE
invalid block header in 1.25

### ISSUE THREAD

**Issue by mydimension** [pgbackrest/pgbackrest#447] opened 2017-11-20 19:20 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 1.25

2. PostgreSQL version: 9.4.14

3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each:

backup server: Ubuntu 16.04.3
database server: Ubuntu 16.04.3

4. Did you install pgBackRest from source or from a package? yes

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

database server `/etc/pgbackrest.conf`:
```
[global]
backup-host=backup.server

[global:restore]
process-max=8

[kb_spider]
db-path=/var/lib/postgresql/9.4/main
```
backup server `/etc/pgbackrest.conf`:
```
[global]
repo-path=/var/lib/pgbackrest
log-level-file=detail
process-max=8
hardlink=y
start-fast=y
stop-auto=y
compress=n
retention-full=2
retention-diff=1

[kb_spider]
backup-standby=y
db1-path=/var/lib/postgresql/9.4/main
db1-host=master-db.server
db2-path=/var/lib/postgresql/9.4/main
db2-host=replica-db.server
```

[kb_spider-restore.log](https://github.com/pgbackrest/pgbackrest/files/1488812/kb_spider-restore.log)

7. Describe the issue:
In restoring the backup to a dev machine, the attached log file is produced (with debug logging enabled). I've tried several permutations of this, all ending in the outcome:

1. doing a `--force` restore
2. doing a regular restore to an empty pg_data directory
3. doing a `--delta` to a partial directory
4. with and without `--buffer-size=16777216` (borrowed suggestion from #442)
5. with and without `--protocol-timeout=36000` (borrowed suggestion from #408)

the log file attached is the result of the last attempted permutation.

Using a longer protocol timeout only delayed the failure. The local side threw an error right away while the remote side just sat idle for the specified time.

**Comment by dwsteele** [comment] 2017-11-20 20:59
This is almost certainly caused by the same issue as #442.  Unfortunately, changing the buffer size will not always work because it depends on how much each file gets compressed.  It's a bit unusual to be running with `compress=n`.  Is your repo file system compressed?

The 1.26 release should be out by Wednesday.  Meanwhile, taking a compressed back should allow you to restore if you can't wait that long.

**Comment by mydimension** [comment] 2017-11-20 23:17
yes, our nfs device compresses and dedupes behind the scenes. my IT group has asked that we don't compress the files ourselves.

**Comment by dwsteele** [comment] 2017-11-21 13:39
Try setting `--compress-level-network=0` for your restore.  This disables the protocol compression and should resolve the buffering issue.

**Comment by mydimension** [comment] 2017-11-21 18:29
no luck. same error as before

**Comment by dwsteele** [comment] 2017-11-21 23:19
I'm going to close this because I'm 99% sure that 1.26 will fix the issue (and it will be released in about an hour).  If you still see issues with 1.26 then let us know and we'll reopen the issue.

**Closed by dwsteele** 2017-11-21 23:19 UTC
Labels: question
