### ISSUE TITLE
Pgbackrest archiving failing

### ISSUE THREAD

**Issue by alexislychine** [pgbackrest/pgbackrest#2434] opened 2024-08-30 18:57 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.49

2. PostgreSQL version:15.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Rhel8.10

4. Is this a patroni environment? Yes
5. We are using a different user which is neither postgres nor pgbackrest 

6. Did you install pgBackRest from source or from a package?
Installed from a package 

7. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

8. Describe the issues 
Archiving is failing since we configured pgbackrest in a patroni cluster 
 Error logs: 
ERROR: [072] archive-push command must be run on the PostgreSQL host
INFO: archive-push command end: aborted with exception [072]
LOG: archive command failed with exit code 72
DETAIL: The failed archive command was: pgbackrest —stanza=Splunk_soar_sit archive-push pg_wal/0000002B.history 

when running pgbackrest check, it’s failing with the following error 
pgbackrest—stanza=Splunk_soar_sit —log-level-console=info check 

INFO: check repo1 configuration (primary)

INFO: check repo1 archive for WAL (primary)

ERROR: [082] WAL segment 0000003500000007000000CD was not archived before the 60000ms timeout 
HINT: check the archive_command to ensure that all options are correct (especially—stanza).
HINT: check PostgreSQL log for errors.
HINT: run the ‘start’ command if the stanza was previously stopped 
INFO: check command end: aborted with exception [082]

I’ve checked the logs and can’t find any useful information. I’ve executed the start command but nothing was previously stopped.

I will appreciate help from anyone familiar with this error. Before we setup pgbackrest, archiving was working. If you replace archive_command to not use pgbackrest and reload your cluster, it woks.

pgbackrest.conf
repo1-path=/pgdbbackup/pgbackrest

[Splunk_soar_sit]
pg1-host=ip_address
pg1-path=/data/postgresql/15
pg1-user=my_user
pg1-port=5432
pg1-socket-path=/var/run/postgresql

pg2-host=ip_address
pg2-path=/data/postgresql/15
pg2-user=my_user
pg2-port=5432
pg2-socket-path=/var/run/postgresql

pg3-host=ip_address
pg3-path=/data/postgresql/15
pg3-user=my_user
pg3-port=5432
pg3-socket-path=/var/run/postgresql

archive_command= 'pgbackrest --stanza=Splunk_soar_sit archive-push %p'
archive_mode=on
listen_addresses=server's ip (since we use Patroni)
max_wal_senders=10
wal_level=replica
port=5432

Thanks,

**Comment by pgstef** [comment] 2024-08-30 19:50
`HINT: check PostgreSQL log for errors.` you should have errors in the PostgreSQL logs. And it's probably linked to #2432 if you fail to create the stanza, the archiving command won't work.

**Comment by dwsteele** [comment] 2024-08-31 05:59
Closing since it is likely caused by #2432.

**Closed by dwsteele** 2024-08-31 05:59 UTC
Labels: question
