### ISSUE TITLE
Differential/Incremental backup errors

### ISSUE THREAD

**Issue by dtown17** [pgbackrest/pgbackrest#335] opened 2017-03-22 19:19 UTC
During my testing of pgBackRest (v1.17) on a demo PostgreSQL cluster I am receiving the errors below.  The errors occur when performing an Incremental or Differential backup after a Full backup has been completed and I have inserted, updated or deleted data for a table.  The error stack is the same whether it's an Incremental or Differential backup

I can successfully perform a Full backup at all times and successful Differential and Incremental backups after the Full backup if no DML has been completed for a table.

```
2017-03-22 13:55:28.228 P01   INFO: backup file /app/data/xxxxxxxxx/global/pg_control (8KB, 99%) checksum dd7ae49879aa58480b7e019c3d885f9251d57bc7
ERROR [199]: remote process terminated on local-1 host: unknown error: Undefined subroutine &pgBackRest::BackupFile::pageChecksumBufferTest called at /usr/share/perl5/pgBackRest/BackupFile.pm line 116.
 at /usr/bin/pgbackrest line 15
        main::__ANON__('Undefined subroutine &pgBackRest::BackupFile::pageChecksumBuf...') called at /usr/share/perl5/pgBackRest/BackupFile.pm line 116
        pgBackRest::BackupFile::backupChecksumPage('HASH(0x3223410)', 'SCALAR(0x2a01488)', 8192, 0, 'HASH(0x321f280)') called at /usr/share/perl5/pgBackRest/Protocol/Common.pm line 504
        pgBackRest::Protocol::Common::binaryXfer('pgBackRest::Protocol::Common=HASH(0x2c38608)', 'GLOB(0x321eed8)', 'GLOB(0x2c37ff0)', 'out', 0, 1, 0, 'CODE(0x31a4040)', 'HASH(0x3223410)', ...) called at /usr/share/perl5/pgBackRest/File.pm line 1366
        pgBackRest::File::copy(undef, 'db:absolute', '/app/data/xxxxxxxxx/base/13241/16415', 'backup:tmp', 'pg_data/base/13241/16415.gz', 0, 1, 1, 1490204938, ...) called at /usr/share/perl5/pgBackRest/BackupFile.pm line 229
        pgBackRest::BackupFile::backupFile('pgBackRest::File=HASH(0x2c38428)', '/app/data/xxxxxxxxx/base/13241/16415', 'pg_data/base/13241/16415', 8192, undef, 1, 1, 1490204938, 1, ...) called at /usr/share/perl5/pgBackRest/Protocol/LocalMinion.pm line 76
        pgBackRest::Protocol::LocalMinion::__ANON__('ARRAY(0x32234a0)') called at /usr/share/perl5/pgBackRest/Protocol/CommonMinion.pm line 174
        eval {...} called at /usr/share/perl5/pgBackRest/Protocol/CommonMinion.pm line 198
        eval {...} called at /usr/share/perl5/pgBackRest/Protocol/CommonMinion.pm line 206
        pgBackRest::Protocol::CommonMinion::process('pgBackRest::Protocol::LocalMinion=HASH(0x2c38068)') called at /usr/bin/pgbackrest line 118
        eval {...} called at /usr/bin/pgbackrest line 292
2017-03-22 13:55:28.239 P00  DEBUG:     Common::Exit::exitSafe(): iExitCode = [undef], oException = [object], strSignal = [undef]
2017-03-22 13:55:28.239 P00  DEBUG:     Protocol::Protocol::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
2017-03-22 13:55:28.240 P00  DEBUG:     Protocol::Protocol::protocolDestroy=>: iExitStatus = 0
2017-03-22 13:55:28.240 P00  DEBUG:     Common::Lock::lockRelease(): bFailOnNoLock = false
2017-03-22 13:55:28.241 P00   INFO: backup command end: aborted with exception [199]
2017-03-22 13:55:28.241 P00  DEBUG:     Common::Exit::exitSafe=>: iExitCode = 199
```

**Comment by dwsteele** [comment] 2017-03-22 22:35
Do you have page checksums enabled on the target cluster?  You can use `show data_checksums` in psql to check.

Was this a manual install or did you install from packages? Also, what's your OS/version?

**Comment by dtown17** [comment] 2017-03-23 01:39
This was a manual installation using the source.

The OS/Version are:
```
postgres> lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-ia32:base-4.0-noarch:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.8 (Santiago)
Release:        6.8
Codename:       Santiago
```
```
postgres>uname -a
Linux 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Oct 26 10:25:23 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I did not have data_checksums enabled on the first demo cluster, however, I recreated the cluster with data_checksums enabled.  I performed the same test and experienced the same error stack as previously posted.
```
postgres=# show data_checksums;
 data_checksums
----------------
 on
(1 row)

Time: 1.174 ms
postgres=#
```

**Comment by dwsteele** [comment] 2017-03-23 03:09
One thing you can try is to specify `--no-checksum-page` on the command line or `checksum-page=n` in `pgbackrest.conf`.  This will force page checksums off.  It seems that somehow page checksums are being enabled even though the required C library is not present.  Currently this library is only provided via packages.

It would also be helpful if you could provide the `backup.manifest` file from a successful full backup.  You can find this in `$REPO_PATH/backup/$STANZA/latest`.

Thanks!

**Comment by dtown17** [comment] 2017-03-23 14:22
I have attached a backup.manifest from $REPO_PATH/backup/$STANZA/latest for a successful Full backup.
[backup.manifest.zip](https://github.com/pgbackrest/pgbackrest/files/864979/backup.manifest.zip)

I ran a Differential and Incremental backup using ```--no-checksum-page``` on the command line and a Differential and Incremental backup with ```checksum-page=n ``` in ```pgbackrest.conf```  They all failed with the error stack from my first comment.

I also see the warning below during the Differential or Incremental backup indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```.  This warning is only present during Differential and Incremental backups.  This warning is present during Differential and Incremental backups even when using ```--no-checksum-page``` on the command line or ```checksum-page=n ``` in ```pgbackrest.conf```

```
I2017-03-23 09:59:45.557 P00   INFO: backup start archive = 000000010000000000000                                     01A, lsn = 0/1A000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-090619F
2017-03-23 09:59:46.593 P01   INFO: backup file /app/data/xxxxxxxxx/gprof/21219/gmon.out (2MB, 25%) checksum e1635116a981e03b36e9ca288b9e9887c53ba7be
```

**Comment by dwsteele** [comment] 2017-03-23 19:14
The warning above does not reference the same backup.manifest you sent (`20170323-090619F` in warning above, `20170323-100655F` in manifest).

Can you check the `20170323-100655F` manifest and see if `option-checksum-page=true`.

To use the `--no-checksum-page` option successfully, I think you will need to start using it from the full backup.  It looks like you may have done that in the later backup?

**Comment by dtown17** [comment] 2017-03-23 21:31
The warning was just one of the few I received while executing a some tests this morning with your recommendations.  I did run the backups Full, Differential and Incremental consistently with either checksum enabled or disabled from start to finish.

For clarity and completeness I have performed 6 tests which are outlined below.  I have also included the backup.manifest for the Full Backup from each of the tests.

I did notice in the backup.manifest for all tests, the [backup:option] section contained the same boolean value for each option.  _**option-checksum-page**_ was always _**false.**_

Tests 1-3 are with checksum enabled and Tests 4-6 are with checksum disabled.

Overall, whether I disabled or enabled checksum, the results were the same.  I could not perform a successful Differential or Incremental backup after inserting data into a table after the successful Full backup and successful Differential backup or Incremental backup.

Full Backups as in previous tests were all successful.


**Test 1 - BACKUP checksum - Full, Differential, Incremental, Insert Data, Differential, Incremental**

Successful Full backup with checksum enabled.  backup.manifest from $REPO_PATH/backup/$STANZA/latest for this successful Full backup

[backup.manifest.Test1.FullBackup.zip](https://github.com/pgbackrest/pgbackrest/files/866226/backup.manifest.Test1.FullBackup.zip)

Successful Differential backup with checksum enabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 15:32:43.090 P00   INFO: backup start archive = 000000010000000000000022, lsn = 0/22000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-152816F
2017-03-23 15:32:44.619 P01   INFO: backup file /app/data/ppgolot30/gprof/29700/gmon.out (2MB, 50%) checksum 795aa28afe8bcaf4d2175ff1739577530299fd81
```

Successful Incremental backup with checksum enabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 15:36:02.129 P00   INFO: backup start archive = 000000010000000000000024, lsn = 0/24000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-152816F_20170323-153245D
2017-03-23 15:36:03.606 P01   INFO: backup file /app/data/ppgolot30/gprof/30372/gmon.out (2MB, 50%) checksum 00ce735cff961a1460f99b2d60e2ca93a959e4f6
```

**_Insert Data into table_**


Failed Differential backup with checksum enabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 15:38:51.617 P00   INFO: backup start archive = 000000010000000000000026, lsn = 0/26000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-152816F
2017-03-23 15:38:52.598 P01   INFO: backup file /app/data/ppgolot30/gprof/30807/gmon.out (2MB, 20%) checksum f4ff686fe43435dafbced706279813491ea1663e
```

Failed Incremental backup with checksum enabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```.  Warning message indicating an aborted backup exists which does not match the new backup type.
```
2017-03-23 15:41:04.266 P00   INFO: backup start archive = 000000010000000000000028, lsn = 0/28000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-152816F_20170323-153604I
WARN: aborted backup exists, but cannot be resumed (new backup-type 'incr' does not match aborted backup-type 'diff') - will be dropped and recreated
```




**Test 2 - BACKUP checksum - Full, Differential, Insert Data, Differential**

Successful Full backup with checksum enabled.  backup.manifest from $REPO_PATH/backup/$STANZA/latest for this successful Full backup

[backup.manifest.Test2.FullBackup.zip](https://github.com/pgbackrest/pgbackrest/files/866229/backup.manifest.Test2.FullBackup.zip)

Successful Differential backup with checksum enabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:23:35.206 P00   INFO: backup start archive = 00000001000000000000002D, lsn = 0/2D000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-161548F
2017-03-23 16:23:36.628 P01   INFO: backup file /app/data/ppgolot30/gprof/3122/gmon.out (2MB, 50%) checksum 6504d9b434cfcfc6bfab240c8ac8b6345383ec48
```

**_Insert Data into table_**


Failed Differential backup with checksum enabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:25:26.528 P00   INFO: backup start archive = 00000001000000000000002F, lsn = 0/2F000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-161548F
2017-03-23 16:25:27.639 P01   INFO: backup file /app/data/ppgolot30/gprof/4211/gmon.out (2MB, 25%) checksum 02379d3e32215953b4361774759d9c076d49b76e
```



**Test 3 - BACKUP checksum - Full, Incremental, Insert Data, Incremental**

Successful Full backup with checksum enabled.  backup.manifest from $REPO_PATH/backup/$STANZA/latest for this successful Full backup

[backup.manifest.Test3.FullBackup.zip](https://github.com/pgbackrest/pgbackrest/files/866230/backup.manifest.Test3.FullBackup.zip)

Successful Incremental backup with checksum enabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:33:04.738 P00   INFO: backup start archive = 000000010000000000000033, lsn = 0/33000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-162757F
2017-03-23 16:33:06.620 P01   INFO: backup file /app/data/ppgolot30/gprof/4838/gmon.out (2MB, 50%) checksum c83163faecf3e932450e2ef2216f1ab0171bbc3c
```

**_Insert Data into table_**


Failed Incremental backup with checksum enabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:34:35.691 P00   INFO: backup start archive = 000000010000000000000035, lsn = 0/35000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-162757F_20170323-163307I
2017-03-23 16:34:37.648 P01   INFO: backup file /app/data/ppgolot30/gprof/5449/gmon.out (2MB, 33%) checksum f9c323151d16b9cee29d100ec457e66b1b2bd7b3
```


**Test 4 - BACKUP nochecksum - Full, Differential, Incremental, Insert Data, Differential, Incremental**

Successful Full backup with checksum disabled.  backup.manifest from $REPO_PATH/backup/$STANZA/latest for this successful Full backup

[backup.manifest.Test4.FullBackup.zip](https://github.com/pgbackrest/pgbackrest/files/866231/backup.manifest.Test4.FullBackup.zip)

Successful Differential backup with checksum disabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:43:35.168 P00   INFO: backup start archive = 000000010000000000000039, lsn = 0/39000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-163954F
2017-03-23 16:43:36.626 P01   INFO: backup file /app/data/ppgolot30/gprof/6251/gmon.out (2MB, 50%) checksum 8c82858531e68ddc35ac9670fe94e77b9edfb06a
```

Successful Incremental backup with checksum disabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:45:19.415 P00   INFO: backup start archive = 00000001000000000000003B, lsn = 0/3B000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-163954F_20170323-164337D
2017-03-23 16:45:20.621 P01   INFO: backup file /app/data/ppgolot30/gprof/6679/gmon.out (2MB, 50%) checksum 028451a8d10d584f8ce8a7ed2f0b2e10c9671192
```

**_Insert Data into table_**


Failed Differential backup with checksum disabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:47:58.413 P00   INFO: backup start archive = 00000001000000000000003D, lsn = 0/3D000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-163954F
2017-03-23 16:47:59.597 P01   INFO: backup file /app/data/ppgolot30/gprof/6903/gmon.out (2MB, 20%) checksum 3fdd76289458c7b5e1a3995f89ad6a8d298c4df0
```

Failed Incremental backup with checksum disabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```.  Warning message indicating an aborted backup exists which does not match the new backup type
```
2017-03-23 16:49:26.746 P00   INFO: backup start archive = 00000001000000000000003F, lsn = 0/3F000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-163954F_20170323-164521I
WARN: aborted backup exists, but cannot be resumed (new backup-type 'incr' does not match aborted backup-type 'diff') - will be dropped and recreated
2017-03-23 16:49:28.789 P01   INFO: backup file /app/data/ppgolot30/gprof/6903/gmon.out (2MB, 20%) checksum 3fdd76289458c7b5e1a3995f89ad6a8d298c4df0
```



**Test 5 - BACKUP nochecksum - Full, Differential, Insert Data, Differential**

Successful Full backup with checksum disabled.  backup.manifest from $REPO_PATH/backup/$STANZA/latest for this successful Full backup

[backup.manifest.Test5.FullBackup.zip](https://github.com/pgbackrest/pgbackrest/files/866232/backup.manifest.Test5.FullBackup.zip)

Successful Differential backup with checksum disabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```
```
2017-03-23 16:54:49.303 P00   INFO: backup start archive = 000000010000000000000043, lsn = 0/43000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-165149F
2017-03-23 16:54:50.652 P01   INFO: backup file /app/data/ppgolot30/gprof/7666/gmon.out (2MB, 50%) checksum 4a40502d972e731a888d830ca15b4b2c06d63a41
```

**_Insert Data into table_**


Failed Differential backup with checksum disabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```.
```
2017-03-23 16:56:54.977 P00   INFO: backup start archive = 000000010000000000000045, lsn = 0/45000028
WARN: diff backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-165149F
2017-03-23 16:56:56.667 P01   INFO: backup file /app/data/ppgolot30/gprof/8056/gmon.out (2MB, 25%) checksum 175ae6407f8892cfaee01f5de4ee8729ff763575
```



**Test 6 - BACKUP nochecksum - Full, Incremental, Insert Data, Incremental**

Successful Full backup with checksum disabled.  backup.manifest from $REPO_PATH/backup/$STANZA/latest for this successful Full backup

[backup.manifest.Test6.FullBackup.zip](https://github.com/pgbackrest/pgbackrest/files/866233/backup.manifest.Test6.FullBackup.zip)

Successful Incremental backup with checksum disabled.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```

```
2017-03-23 17:01:39.703 P00   INFO: backup start archive = 000000010000000000000049, lsn = 0/49000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-165917F
2017-03-23 17:01:41.629 P01   INFO: backup file /app/data/ppgolot30/gprof/8564/gmon.out (2MB, 50%) checksum 0b68c94ddba1cdc38d0df66ccf788e65444b0d96
```

**_Insert Data into table_**


Failed Incremental backup with checksum disabled with the error stack from my first comment.  Warning message indicating ```checksum-page``` cannot be altered to ```false``` so it is reset to ```true```.
```
2017-03-23 17:03:01.323 P00   INFO: backup start archive = 00000001000000000000004B, lsn = 0/4B000028
WARN: incr backup cannot alter 'checksum-page' option to 'false', reset to 'true' from 20170323-165917F_20170323-170142I
2017-03-23 17:03:02.629 P01   INFO: backup file /app/data/ppgolot30/gprof/8899/gmon.out (2MB, 33%) checksum b64d6109a7f17b3e4e03a10de0f52a38cb12f2e0
```

**Comment by dwsteele** [comment] 2017-03-24 18:19
Thanks for the very detailed tests.  I have not been able to determine the cause of the error, but I was able to eliminate a lot of possibilities.

Somehow, `option-checksum-page` is being reported as `true` even though it is clearly `false` in `backup.manifest`.  I can't reproduce this and tests around this code all work as expected.

Is there any chance you have an older copy of pgBackRest that was not property removed?  The libraries migrated around a bit earlier on so it might not be in the same location.  See removal instructions here: http://www.pgbackrest.org/user-guide.html#installation

You might also try `perl -v` and make sure that some strange Perl was not installed on your system.  You should have `5.10`.

You could also try installing from packages.  I know yum.postgresql.org has RHEL 7 packages but I'm not sure about RHEL 6.

Of course, this may still be a bug, but currently I'm not seeing it.  If it's as pervasive as your tests indicate this should be blowing up all over the place.  I'm hoping that it's environmental, or caused by some old libraries lying around.

**Comment by dtown17** [comment] 2017-03-24 20:09
It looks like there may have been a previous version installed as some of the file timestamps were from 1 year ago.

I performed the steps outlined in online documentation http://www.pgbackrest.org/user-guide.html#installation to remove pgBackRest.

I then performed an installation as outlined in the same documentation.

The version of Perl installed is 5.10.1 as indicated from the output below.

 ```
postgres> perl -v

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

Copyright 1987-2009, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

I executed 2 tests, performing a Full Backup, Differential Backup, Insert Data and a Differential Backup.  I performed 1 test with checksum enabled and 1 test with checksum disabled.  As with all the prior tests, the Final Differential Backup failed.

I'll try to install using packages, however, this may not be possible due to restrictions of internet access to most machines.  I'll perform an uninstall before installing via packages.

**Comment by dtown17** [comment] 2017-03-24 21:39
Looking again at the error below from the error stack, its seems to indicate subroutine pageChecksumBufferTest cannot be found.

It seems to exist in the extracted source within file pageChecksum.c in ~/pgbackrest-release-1.17/libc.  I do not see where this directory or file is copied in the installation instructions.  Could this be the reason it is not found?
```
ERROR [199]: remote process terminated on local-1 host: unknown error: Undefined subroutine &pgBackRest::BackupFile::pageChecksumBufferTest called at /usr/share/perl5/pgBackRest/BackupFile.pm line 116. at /usr/bin/pgbackrest line 15
```

**Comment by dwsteele** [comment] 2017-03-24 22:11
Yes, there are no instructions for compiling the C library manually.  It is only distributed with packages at the moment.

However, the C library only hit the packages recently and the code has been around since December.  It should gracefully handle a missing C library and has up until now.  I ran it for months without the C library present on many systems.

Building the C Library might fix your immediate problem, but might also mask others.

**Comment by dtown17** [comment] 2017-03-27 14:33
I installed pgBackRest from source on a different server which did not have a previous installation of pgBackRest.

I executed 2 tests, performing a Full Backup, Differential Backup, Insert Data and a Differential Backup. I performed 1 test with checksum enabled and 1 test with checksum disabled. As with all the prior tests on the previous server, the Final Differential Backup failed.

I'm trying to determine if it will be possible to install via package but have not yet received an answer from my colleagues.

It seems odd that subroutine pageChecksumBufferTest is always being referenced, and the error not being handled as you previously mentioned, whether or not I'm using --no-checksum-page.

**Comment by dwsteele** [comment] 2017-03-27 16:29
We are still unable to reproduce the error. The only thing we can think of at this point is to get debug output.  Can you with run with `--log-level-file=debug` for the successful full, successful diiff, and failed diff and attach the resulting log file?

In a default install you'll find the log files at `/var/log/pgbackrest`.  Probably best to clear out any existing logs before running the tests.

Thanks!

**Comment by dtown17** [comment] 2017-03-27 17:10
I have attached debug logs with tests for checksum enabled(**POC-backup-checksum.log**) and checksum disabled(**POC-backup-nochecksum**).

[POC-backup.zip](https://github.com/pgbackrest/pgbackrest/files/873202/POC-backup.zip)

**Comment by dtown17** [comment] 2017-03-27 18:19
I have attached logs with tests for checksum enabled and checksum disabled.

[POC-backup-debug.zip](https://github.com/pgbackrest/pgbackrest/files/873375/POC-backup-debug.zip)

The debug output was not placed in the logs located in /var/logs/pgbackrest, therefore, I redirected STDOUT and STDERR to logs named POC-backup-checksum-debug* and POC-backup-nochecksum-debug*

The logs created by pgBackRest have been named POC-backup-checksum.log and POC-backup-nochecksum.log

**Comment by dtown17** [comment] 2017-03-27 20:31
I uninstalled the installation via source and installed pgBackRest from pgbackrest-1.17-1.rhel6.noarch.rpm which was downloaded from https://yum.postgresql.org/9.5/redhat/rhel-6-x86_64/

I am still experiencing the error stack posted in my initial comment if I perform a Full Backup, Differential Backup, Insert Data and Differential Backup.

**Comment by dtown17** [comment] 2017-03-27 21:13
One final test was to install version 1.09 and perform a Full Backup, Differential Backup, Insert Data, Differential Backup.

All backups completed successfully and did not encounter the initial posted error after inserting data and performing a Differential Backup.

**Comment by dwsteele** [comment] 2017-04-03 22:04
Sorry for the late reply.  I have been through the logs but don't see anything unusual.  There's not a lot of logging around the manifest primitives since they have always performed reliably.

I have an open item to document how to manually build the C library.  You can see the steps here: https://github.com/pgbackrest/pgbackrest/blob/master/test/test.pl#L446

It boils down to:
```
cd libc
perl Makefile.PL INSTALLMAN1DIR=none INSTALLMAN3DIR=none
make
make test
make install
```
Of course, you'll need to have various build packages installed: `gcc make perl-ExtUtils-MakeMaker perl-Test-Simple`.

The reason I haven't written the docs yet is I don't think it's appropriate to install these tools on a prod server and moving the the binaries to another server depends a lot on the OS/Version.  It's complex enough that I feel like working from packages is best, but the RHEL/CentOS packages do not provide the C Library yet.  This is out of my control but I'm hoping it will happen soon.

**Comment by dtown17** [comment] 2017-04-04 17:37
Thank you for your reply.  I performed the test to complete a Full Backup, Differential Backup, Insert Data and Differential Backup using source versions 1.09 through 1.17.

The test was successful for versions 1.09 through 1.11, however, the test failed for versions 1.12 through 1.17 with the error in my original post.

I'll continue to do more testing with version 1.11 in my environment and wait for the C libraries to be  included with the RHEL/CentOS package.

I may do some additional testing with versions newer than 1.11 after building the C libraries if time is approved for my environment to test this configuration.

**Comment by dwsteele** [comment] 2017-04-04 19:05
v1.11 is a perfectly good release to test with.  However, I would hold off on using asynchronous archiving until you are able to use the improved implementation introduced in v1.13.

**Comment by dwsteele** [comment] 2017-04-25 15:59
I haven't had any inspiration on this issue so I'm going to close it.  I still believe it is environmental as this is the only field report of the issue and I have not been able to reproduce it.

I think the solution is to build the C library or use a package the provides it.  In the not-to-distant future the C library will be required anyway.

**Closed by dwsteele** 2017-04-25 15:59 UTC
Labels: question
