### ISSUE TITLE
[Feature Request] Have backups poke the archive.info file to allow safe cloud bucket lifecycle expiration

### ISSUE THREAD

**Issue by alex-richman-onesignal** [pgbackrest/pgbackrest#1853] opened 2022-08-30 14:16 UTC
pgBackRest version: 2.40

When archiving to a cloud bucket (GCS/AWS), it's convenient to configure lifecycle rules [1] to handle expiration of old backups/archived WAL based on an object Age.  This is a compelling alternative to the built-in expiration functionality because execution of lifecycle rules is free where pgbackrest's expiry has to issue a bunch of costed DELETEs, and using lifecycle rules is much faster/reduces load on the database server itself.

This works fine for all files in the repo except for the archive.info files.  All other files have a up-to-date Age which we can key the lifecycle rule on to safely expire them, but the archive.info files are only updated sporadically (on timeline changes or something?), this means that a naive lifecycle rule would expire them too soon and make the archives unrecoverable.

I expect having the archive.info files updated on every archive-push would be too expensive, but perhaps they could be updated after a successful backup?  This would give them an up-to-date age at least once a day (or w/e backup schedule) and allow lifecycle rules to be configured easily to handle expiration.

[1] https://cloud.google.com/storage/docs/lifecycle

**Comment by dwsteele** [comment] 2022-08-31 17:23
I have mixed feelings about this -- I think it would be good to prevent unintentional deletions but I don't think bucket lifecycles are a very good way to do retention. At the least it will make the info command inaccurate and also there will often be a backup that appears to be valid but would actually fail on restore. This means verify will also get very upset.

A better way to make verify more efficient is to use file bundling to reduce the number of files being written in the backup (see https://pgbackrest.org/user-guide.html#backup/bundle).

So, I think this is probably worth doing (I had already been thinking about it) but I don't think we'll be recommending this is a way to do retention just yet. In order to do this property, I think pgbackrest would need to know what the delete horizon is so we could make intelligent decisions about how to treat missing files.

I have created a project card for this feature (https://github.com/pgbackrest/pgbackrest/projects/2#card-85372718) so closing this issue.

**Closed by dwsteele** 2022-08-31 17:23 UTC
Labels: question

**Comment by dwsteele** [comment] 2022-08-31 19:21
PR #1855 has been created the update the archive.info timestamp.

Again, this should not be considered a replacement for using the expire commands as there may well be other effects we have not considered.

**Comment by alex-richman-onesignal** [comment] 2022-09-01 12:10
Thanks, this change looks great :+1:

We had an existing native expiry policy to retain 3 days [1], and when I scanned through the bucket prior to implementing the lifecycle rules I could only find the archive.info files which were older than 3 days.  We only take full backups, no incr backups so there should be no inter-dependency between the backups.

I see the backup.info contains a list of current backups, and I suppose if the lifecycle rules take the backup files away without a native pgbackrest expire that list will be out of date, but will that affect making new backups / restoring the 3 current backups, or just confuse pgbackrest on info/verify because it has records for the backups that no longer exist?



> A better way to make verify more efficient is to use file bundling to reduce the number of files being written in the backup (see https://pgbackrest.org/user-guide.html#backup/bundle).

Our testing shows the issue is not really with expiration of the backups, but rather expiration of the archived WAL.  For reference a mid-sized shard in our cluster takes ~1hr to backup, ~20 minutes to expire the old backup and ~3 hours to expire the old archive that backup was holding onto.

Implementing the expiration via lifecycle rules takes our total backup+expire time (now just backup) to 1hr, from ~4.5 hours, and means we save some 100s of dollars a day in list+delete operations.  Having pgbackrest officially support expiration via lifecycle rules would be a very useful feature for owners of large databases.

Cheers,
- Alex.


[1] 
```
repo1-retention-full-type=count
repo1-retention-full=3
repo1-retention-archive-type=full
repo1-retention-archive=3
```

**Comment by dwsteele** [comment] 2022-09-02 14:19
> We only take full backups, no incr backups so there should be no inter-dependency between the backups.

This is the crux of the issue. Expiration will not follow normal rules implemented by backup systems in general. For instance, it is common to have diff backups expiring before fulls.

Our general plan here is to deal with this (officially) as part of implementing read-only repos, since lifecycle expiration will be the only choice in that case.

> but will that affect making new backups / restoring the 3 current backups, or just confuse pgbackrest on info/verify because it has records for the backups that no longer exist

The problem is not with backups that don't exist at all (these will be removed from info and a warning logged) but with backups that *partially exist*. Let's say a backup takes six hours to complete. That means it will take six hours to be completely removed from the repo with lifecycle rules (IIUC). Since the manifest file indicates if a backup is valid and it gets written last, the backup will appear to be valid but actually be broken for some period of time.

Our plan to handle this for read-only repos is to write a canary file *first* and when this is removed we know the backup is no longer valid.

There are more potential effects that I will not go into here, which is why we can't officially support this even if the PR gets things working for your needs. In any case, if you attempt a restore of a backup that has been partially deleted, you *will* get an error rather than an invalid restore. So I believe what you are doing is safe in that sense.
