### ISSUE TITLE
PITR should fail and exit when the requested time target cannot be reached

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#1582] opened 2021-12-02 17:28 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.36

2. PostgreSQL version: 13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS8

4. Did you install pgBackRest from source or from a package? rpm

6. Describe the issue:

When attempting a time-based PITR and the requested target time cannot be found in the repo (`WARN: unable to find backup set with stop time less than XXX`) it currently proceeds and does a PITR to the _latest available_ point in time. This seems contradictory to the user's stated intent. Instead, the WARN should be an ERROR and the restore _should not proceed_  (if I'm trying to restore to this past Monday there's a reason for that and I do not want it to restore to today).

```
2021-12-02 17:11:58.237 P00   INFO: restore command begin 2.36: --archive-mode=off --delta --exec-id=6218-312e6915 --log-level-console=info --log-level-file=info --pg1-path=/var/lib/pgsql/13/eppricing/data --process-max=3 --repo1-host=192.168.122.14 --repo1-host-user=postgres --spool-path=/var/lib/pgsql/13/eppricing/spool --stanza=eppricing --target="2021-12-02 11:30:00.00000+00" --target-action=promote --type=time
2021-12-02 17:11:58.704 P00   INFO: repo1: restore backup set 20211202-151223F, recovery will start at 2021-12-02 15:12:23
2021-12-02 17:12:01.027 P00   INFO: write updated /var/lib/pgsql/13/eppricing/data/postgresql.auto.conf
2021-12-02 17:12:01.044 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
2021-12-02 17:12:01.047 P00   INFO: restore size = 31.5MB, file total = 1252
2021-12-02 17:12:01.050 P00   INFO: restore command end: completed successfully (2814ms) | stderr: WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/var/lib/pgsql/13/eppricing/data' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
WARN: unable to find backup set with stop time less than '2021-12-02 11:30:00.00000+00', repo1: latest backup set will be used
```

**Comment by dwsteele** [comment] 2021-12-07 14:45
This is by design, though I admit it is not great. The reason is that this was the original behavior before we added the logic to automatically find the best backup, and we were reluctant to have restore start throwing errors where it did not before since the user might have another way to check their target after recovery.

It has been almost two years, though, so I'm not against making a change. Thoughts @sfrost, @pgstef, @jreidthompson?

**Comment by pgstef** [comment] 2021-12-07 14:54
> It has been almost two years, though, so I'm not against making a change. Thoughts @sfrost, @pgstef, @jreidthompson?

There's a change about this in PG 13 too if I remember correctly: _Generate an error if recovery does not reach the specified recovery target_. I would find consistent with PG to not perform the restore if we know beforehand that the target-time is too old.

I've always felt this being a bit counterintuitive too. And if we document this change correctly enough in the release notes, "old" users won't be that affected imo. So I would be in favor of making that change :+1:

**Comment by dwsteele** [comment] 2021-12-07 15:19
> There's a change about this in PG 13 too if I remember correctly: Generate an error if recovery does not reach the specified recovery target.

Postgres does not guarantee that behavior will remain the same between major versions, but we really try to in pgbackrest. So it's not exactly the same, though this is the behavior that users are expecting these days.

**Comment by SemiNomadic** [comment] 2021-12-07 15:51
$0.02 worth of opinion, at best:

- For my part, I could easily miss the WARN and think I'd restored to the desired PITR.  Then comes the wasted time before discovering something is amiss and trying to figure out what happened.
- Even if I did catch the WARN, it comes at the end.  I would have potentially just wasted hours restoring something that was not useful (which could be exacerbated further if this was an emergency situation).

I'd much rather see pgbackrest fail on me up front, letting me know I'm potentially/likely screwed because I don't have that target time in the repo.

**Comment by dwsteele** [comment] 2021-12-07 16:23
> Even if I did catch the WARN, it comes at the end. I would have potentially just wasted hours restoring something that was not useful (which could be exacerbated further if this was an emergency situation).

The warning comes at the beginning -- not sure what is up with the output above. By default the INFO goes to stdout and WARN to stderr so that might what is going on there.

But either way you make an excellent point that time (perhaps a lot) is wasted by restoring the wrong backup.

**Comment by dwsteele** [comment] 2021-12-07 18:50
> I'm of a mind that if we know the requested target can't be met, that we warn the user and do not do the restore.

We currently warn the user, so this change would upgrade that to an error. See https://github.com/pgbackrest/pgbackrest/blob/release/2.36/src/command/restore/restore.c#L367. Looks like we would also need to update: https://github.com/pgbackrest/pgbackrest/blob/release/2.36/src/command/restore/restore.c#L170.

**Comment by dwsteele** [comment] 2021-12-07 22:08
Created PR #1586 for this change so closing the issue.

**Comment by dwsteele** [comment] 2021-12-07 22:09
Please review if you are able.

**Closed by dwsteele** 2021-12-07 22:08 UTC
Labels: module [core], enhancement

**Comment by dwsteele** [comment] 2021-12-07 22:56
I just remembered there was another reason we did not want to do this originally. Before PG10 It could be many hours before pg_stop_backup() returned and we recorded a stop time because pg_stop_backup() would wait for all WAL to be archived.

We added an option in PG10 (https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=017e4f2588a7fc6f2d1fbb6fff8afa1ff6e31f2b) for pg_stop_backup() to return with checking WAL (since we do that) so we could get an accurate stop time. Since PG10 is now the oldest supported version I'm more comfortable that stop times will be accurate for most users.
