### ISSUE TITLE
ERROR: [029]: raised from local-2 protocol: invalid xml

### ISSUE THREAD

**Issue by vidierr** [pgbackrest/pgbackrest#1638] opened 2022-01-26 08:45 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 10.15, 11.x 13.x

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: pgbackrest server : RHEL8, postgresql servers : RHEL7 and RHEL8

4. Did you install pgBackRest from source or from a package?
Package from PGDG

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
After an update from pgbackrest 2.34 to 2.37 somes servers have error "[029]: raised from local-2 protocol: invalid xml"
Somes others servers haven't this error (same pgbackrest server).
The postgresql servers are both RHEL7 and RHEL8 and postgresql 10, 11 and 13.

**Comment by vidierr** [comment] 2022-01-26 08:48
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/7940162/pgbackrest.conf.txt)

**Comment by vidierr** [comment] 2022-01-27 14:54
I have the same issue when i do backup with pgbackrest 2.36.
The backup begin and backup 3 files before having this issue.
Do you know which xml file is invalid ?

**Comment by dwsteele** [comment] 2022-01-27 19:36
Is this AWS S3 or a clone? This error happens when the XML received from the server is invalid.

You can increase the log level `--log-level-file=debug` so we can get an idea of where this is happening, but there's probably not much we can do if the server is handing us bad XML.

**Comment by vidierr** [comment] 2022-01-27 19:40
it's a clone. But it's the same S3 service for all our stanza and somes are good.
When i clean (remove all the line) the file /etc/pgbackrest.conf on Postgresql Servers the backup go to the end, but failed when archiving the wals.
Whend i put the configuration in this file, the archiving is good but the error "xml file" appear.

**Comment by vidierr** [comment] 2022-01-27 19:45
[Debug.txt](https://github.com/pgbackrest/pgbackrest/files/7953363/Debug.txt)

**Comment by vidierr** [comment] 2022-01-28 15:25
I'd just compile pgbackrest 2.34 and deploy it on all servers, now it's work fine.
I'm in vacation next week, so if you want more informations i'll answer you asap.

**Comment by dwsteele** [comment] 2022-02-23 15:44
And I think I may have found the commit that caused this change in behavior: https://github.com/pgbackrest/pgbackrest/commit/8e1807cdbe08a6e059ff79220247cf4b3c058979. It was introduced in 2.35 but there should not be any issues unless the S3 clone is returning bogus results sometimes.

Of course, it's still possible that it's a pgBackRest bug but I'm not seeing what it might be.

The only thing I can think to do is dump the XML with the error message. Error messages are limited to 8K but that should be enough for this case.

**Comment by vidierr** [comment] 2022-02-23 15:54
Hello,
Can you tell where is the XML file to dump and how to make a proper dump ?
Best regards

**Comment by dwsteele** [comment] 2022-02-23 16:05
This is XML being returned from the server. There's not way for you to get to it in pgBackRest. We'll need new code for that, which will need to be done for 2.38.

**Comment by dwsteele** [comment] 2022-02-23 17:11
OK, I add the XML content to the error at 67bdf07e6969f8.

**Comment by vidierr** [comment] 2022-02-24 16:15
I compiled pgbackrest "2.38" and try a backup with debug.
Attached the log
[Debug_2.txt](https://github.com/pgbackrest/pgbackrest/files/8134044/Debug_2.txt)
.

**Comment by dwsteele** [comment] 2022-02-25 00:15
This is what I was expecting. It appears CompleteMultipartUpload is returning no content, which violates the API. See https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html#API_CompleteMultipartUpload_ResponseSyntax, specifically:
```
    Root level tag for the CompleteMultipartUploadResult parameters.

    Required: Yes
```
Probably a good idea to check with your vendor to see why this result is not returned as required. We can't just ignore it as we have plans for the ETag in the near future and this result is the only way to get it.

There's still a chance this is a bug in pgbackrest. To eliminate that possibility, we'd need to see a run with `--log-level-file=trace --log-subprocess`. Then we'd need the log for the local process where the error was thrown. So, for example, if the error was `raised from local-2` we'd need the `[stanza]-backup-local-002.log` file. It is going to be big, so let's start with the last 1000 lines. *Please be aware that trace level logs can leak secrets, though we try to prevent this as much as possible*. Basically, I want to verify that the server is sending us `content-length: 0` and this should be pretty clear from the logs.

If it turns out the server is sending `content-length: 0` in the response there is nothing we can do. You'll need to contact your vendor.

**Comment by vidierr** [comment] 2022-02-25 11:02
I will investigate that with the storage team.
It seems that the storage is not to the last update.
[debug_local-002_last1000.log](https://github.com/pgbackrest/pgbackrest/files/8140604/debug_local-002_last1000.log)

**Comment by dwsteele** [comment] 2022-02-25 15:20
Thanks for getting that log. It turns out that the server is sending:

**Comment by dwsteele** [comment] 2022-02-25 15:31
Thanks for sending the logs. It turns out the server is sending `Connection: CLOSE`, which causes problems for us because we are expecting the more normal `Connection: close`. Digging into the HTTP specs, however, it does appear that `Connection` values are case-insensitive, probably a legacy of `HTTP/1.0`: https://www.rfc-editor.org/rfc/rfc7230#section-6.1.

Further, this pattern of omitting `content-size` and forcing read to EOF to get the content is incredibly archaic. But, it is allowed by the spec..

We'll fix this for the 2.38 release. How would you like your name to appear in the release notes?

**Comment by vidierr** [comment] 2022-02-25 15:58
Thanks a lot for the correction, and pgbackrest.
You can use "Rémi Vidier"

**Comment by dwsteele** [comment] 2022-02-25 16:21
Create PR #1675 for this so closing.

**Closed by dwsteele** 2022-02-25 16:21 UTC
Labels: bug, module [core]

**Comment by dwsteele** [comment] 2022-02-25 17:20
Committed at b33cabe08c. It would be good if you could test this to see if it really fixes the problem. Our release is in one week.

**Comment by vidierr** [comment] 2022-02-28 16:29
With this version, it's work fine.
I will investigate with the storage team and watch if update/upgarde is possible.

**Comment by dwsteele** [comment] 2022-02-28 20:13
We have implemented something that reduces the scope of treating these unexpected EOFs as a regular TLS close. None of us are very happy about this, but it's a problem that previously working installations no longer work after 2.35.

Our testing here is not adequate yet, but writing the tests is going to be pretty hard. Can you test and see if this works in your environment?

**Comment by vidierr** [comment] 2022-03-01 10:07
I try this morning the "master" version of pgbackrest whith an up to date bucket on our storage, and we have the same error.
I try the actual version of branch https://github.com/dwsteele/pgbackrest/tree/dev-tls-err-eof-cig and it works fine.
If you need more informations/tests, i'm here.

**Comment by dwsteele** [comment] 2022-03-01 13:57
Just to check -- you pulled a new version of https://github.com/dwsteele/pgbackrest/tree/dev-tls-err-eof-cig this morning? I made significant changes after you tested the first version. Make sure that you checked out and tested 2917e1a8ca560a.

**Comment by vidierr** [comment] 2022-03-01 14:43
Which branch or tag do i test ?
I'm newbie to use git, so i don't know how to apply a commit on an other branch like master for exemple.

**Comment by dwsteele** [comment] 2022-03-01 14:46
What you want to do is:

**Comment by vidierr** [comment] 2022-03-01 15:38
Thanks for the command.
I confirme, it works fine.

**Comment by dwsteele** [comment] 2022-03-01 15:42
Excellent, thank you! I have added some additional tests to make sure this keeps working as expected. It's a bit of a hack, so I'm worried that it would be easy to have a regression.
