### ISSUE TITLE
Error when restoring backup

### ISSUE THREAD

**Issue by fishermd13** [pgbackrest/pgbackrest#418] opened 2017-10-02 15:09 UTC
After performing a full backup last night, part of the process is to do a restore to ensure everything works as expected.  While no errors were reported in any of the backup logs, the restores of 3 out of 6 DB servers failed.  This has been happening after successful incremental backups as well, and it's not always the same DB content.

This is some of the more common error output:
```
-------------------PROCESS START-------------------
2017-10-02 09:10:54.648 P00   INFO: restore command begin 1.24: --backup-host=10.138.0.66 --backup-user=pgbackrest "--cmd-ssh=/usr/bin/ssh -p 22000" --db1-path=/var/lib/postgresql/9.3/main --force --log-level-console=info --process-max=4 --repo-path=/var/lib/pgbackrest --stanza=lists
2017-10-02 09:10:55.375 P00   INFO: restore backup set 20171002-004342F
2017-10-02 09:10:56.303 P00   INFO: remove invalid files/paths/links from /var/lib/postgresql/9.3/main
2017-10-02 09:11:30.263 P03   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925577.3 (1GB, 0%) checksum fc7ef3069a6305e8c6a5f22ec57915b7c711916d
2017-10-02 09:11:33.829 P02   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925577.4 (1GB, 0%) checksum f3c3b3a58e7f47d8b6907446b2d9a0423bca79ff
2017-10-02 09:11:33.836 P04   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925577.2 (1GB, 0%) checksum 817cccb0eed8cacef82a359435b0e185a7f538b4
2017-10-02 09:11:33.921 P01   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925577.5 (1GB, 0%) checksum e0db5932891cec19063dc1377b3127a5fd2aaf04
2017-10-02 09:11:56.763 P03   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925577.1 (1GB, 0%) checksum a4548c5db5cb7a390576f6f529c0d77e57c8e263
2017-10-02 09:12:01.718 P01   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925576.4 (1GB, 0%) checksum ec0315b616ac9c52eb003cce0543aa95ace86dcf
2017-10-02 09:12:01.718 P04   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925576.5 (1GB, 0%) checksum 397d4049aa560d50aa9e2b82da5f387b6c05ba35
2017-10-02 09:12:02.786 P02   INFO: restore file /var/lib/postgresql/9.3/main/base/28561651/65925577 (1GB, 0%) checksum bf63e0a05536cfa293ac732a42131ff94c3e6377
2017-10-02 09:12:16.750 P00  ERROR: [064]: raised on 'local-1' host: unable to inflate '/var/lib/postgresql/9.3/main/base/28561651/65925576.2': invalid distance code
2017-10-02 09:12:16.750 P00  ERROR: [064]: raised on 'local-1' host: unable to inflate '/var/lib/postgresql/9.3/main/base/28561651/65925576.2': invalid distance code
2017-10-02 09:13:06.126 P00  ERROR: [042]: process '10.138.0.66 remote' terminated unexpectedly [000]
2017-10-02 09:13:06.128 P00   WARN: unable to shutdown protocol [042]: process '10.138.0.66 remote' terminated unexpectedly [000]
2017-10-02 09:13:06.128 P00  ERROR: [063]: terminated on signal [SIGINT]
2017-10-02 09:13:06.129 P00   INFO: restore command end: terminated on signal [SIGINT]
```
And
```
-------------------PROCESS START-------------------
2017-10-02 09:21:13.595 P00   INFO: restore command begin 1.24: --backup-host=10.138.0.66 --backup-user=pgbackrest "--cmd-ssh=/usr/bin/ssh -p 22000" --db1-path=/var/lib/postgresql/9.3/main --force --log-level-console=info --process-max=4 --repo-path=/var/lib/pgbackrest -
-stanza=leads
2017-10-02 09:21:14.277 P00   INFO: restore backup set 20171002-060046F
2017-10-02 09:21:15.110 P00   INFO: remove invalid files/paths/links from /var/lib/postgresql/9.3/main
2017-10-02 09:21:16.126 P00   INFO: cleanup removed 1054 files, 3 paths
2017-10-02 09:21:41.213 P02   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/72277080 (1GB, 0%) checksum cfef9c3b2c76f276b2b60547ff9a26d67b9ada66
2017-10-02 09:21:44.427 P04   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/69498344.8 (1GB, 0%) checksum 8c795c4167ba4d5b46165a9c790c2abeb8883c0d
2017-10-02 09:21:46.566 P01   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/73500277 (1GB, 0%) checksum be959ec29555e5193e99404df73105e891c6c6d7
2017-10-02 09:21:46.641 P03   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/69498344.9 (1GB, 1%) checksum a66cdd11e1377135569046aa8d3d442063a5fb84
2017-10-02 09:22:09.960 P02   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/69498344.7 (1GB, 1%) checksum d7598f14f3e76a5839887447701e334314a6fcc7
2017-10-02 09:22:11.829 P03   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/69498344.4 (1GB, 1%) checksum 946b6c65facc2245f9a4ae64eaabf16a8961ab4c
...
2017-10-02 09:28:52.817 P01   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/69497207.16 (1GB, 20%) checksum 54d8e2e4f62c51a630974b0efd1c7f667b58982c
2017-10-02 09:28:56.507 P02   INFO: restore file /var/lib/postgresql/9.3/main/base/31435562/69497207.15 (1GB, 20%) checksum 234273f5f055887c93a71512b5b2d9e9f09d3023
2017-10-02 09:29:13.032 P00  ERROR: [064]: raised on 'local-4' host: unable to inflate '/var/lib/postgresql/9.3/main/base/31435562/69497207.13': invalid stored block lengths
2017-10-02 09:29:13.033 P00  ERROR: [064]: raised on 'local-4' host: unable to inflate '/var/lib/postgresql/9.3/main/base/31435562/69497207.13': invalid stored block lengths
2017-10-02 09:30:33.373 P00  ERROR: [042]: process '10.138.0.66 remote' terminated unexpectedly [000]
2017-10-02 09:30:33.375 P00   WARN: unable to shutdown protocol [042]: process '10.138.0.66 remote' terminated unexpectedly [000]
2017-10-02 09:30:33.375 P00  ERROR: [063]: terminated on signal [SIGINT]
2017-10-02 09:30:33.376 P00   INFO: restore command end: terminated on signal [SIGINT]
```

Pgbackrest version: 1.24 (although this happens in 1.18 as well)
Fully updated Ubuntu 16.04 x64
The command used to perform the backups vary slightly:
/usr/bin/pgbackrest --stop-auto --stanza=lists --type=full backup
Relevant sections of pgbackrest.conf:
[lists]
db1-host=xxxx.xxxxx.com
db1-path=/var/lib/postgresql/9.3/main
db1-user=postgres
db2-host=xxxx.xxxxx.com
db2-path=/var/lib/postgresql/9.3/main
db2-user=postgres

[leads]
db1-host=xxxx.xxxxx.com
db1-path=/var/lib/postgresql/9.3/main
db1-user=postgres
db2-host=xxxx.xxxxx.com
db2-path=/var/lib/postgresql/9.3/main
db2-user=postgres

[global]
backup-standby=y
repo-path=/var/lib/pgbackrest
retention-full=2
cmd-ssh=/usr/bin/ssh -p 22000
process-max=4

Supplemental information:
This problem *seems* to have become more pronounced after performing updates on 9/19.  The packages updated at that time (from the history file) are
```
Commandline: apt-get dist-upgrade
Install: linux-image-4.4.0-96-generic:amd64 (4.4.0-96.119, automatic), linux-headers-4.4.0-96:amd64 (4.4.0-96.119, automatic), linux-headers-4.4.0-96-generic:amd64 (4.4.0-96.119, automatic)
Upgrade: cryptsetup-bin:amd64 (2:1.6.6-5ubuntu2, 2:1.6.6-5ubuntu2.1), libdns-export162:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), cloud-init:amd64 (0.7.9-153-g16a7302f-0ubuntu1~16.04.2, 0.7.9-233-ge586fe35-0ubuntu1~16.04.1), libisccfg140:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), libcups2:amd64 (2.1.3-4, 2.1.3-4ubuntu0.3), pollinate:amd64 (4.23-0ubuntu1~16.04.1, 4.25-0ubuntu1~16.04.1), update-manager-core:amd64 (1:16.04.7, 1:16.04.9), linux-headers-generic:amd64 (4.4.0.89.95, 4.4.0.96.101), python-samba:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.9, 2:4.3.11+dfsg-0ubuntu0.16.04.10), update-notifier-common:amd64 (3.168.4, 3.168.5), libwbclient0:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.9, 2:4.3.11+dfsg-0ubuntu0.16.04.10), git-man:amd64 (1:2.7.4-0ubuntu1.1, 1:2.7.4-0ubuntu1.2), python3-jwt:amd64 (1.3.0-1, 1.3.0-1ubuntu0.1), tcpdump:amd64 (4.9.0-1ubuntu1~ubuntu16.04.1, 4.9.2-0ubuntu0.16.04.1), snapd:amd64 (2.25, 2.27.5), bind9-host:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), dnsutils:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), libpython3.5:amd64 (3.5.2-2ubuntu0~16.04.1, 3.5.2-2ubuntu0~16.04.2), python3.5:amd64 (3.5.2-2ubuntu0~16.04.1, 3.5.2-2ubuntu0~16.04.2), git:amd64 (1:2.7.4-0ubuntu1.1, 1:2.7.4-0ubuntu1.2), python3.5-minimal:amd64 (3.5.2-2ubuntu0~16.04.1, 3.5.2-2ubuntu0~16.04.2), libisc160:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), grub-legacy-ec2:amd64 (0.7.9-153-g16a7302f-0ubuntu1~16.04.2, 0.7.9-233-ge586fe35-0ubuntu1~16.04.1), libpq5:amd64 (9.5.7-0ubuntu0.16.04, 9.5.8-0ubuntu0.16.04.1), libapparmor1:amd64 (2.10.95-0ubuntu2.6, 2.10.95-0ubuntu2.7), lxd:amd64 (2.0.10-0ubuntu1~16.04.1, 2.0.10-0ubuntu1~16.04.2), samba-libs:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.9, 2:4.3.11+dfsg-0ubuntu0.16.04.10), libapparmor-perl:amd64 (2.10.95-0ubuntu2.6, 2.10.95-0ubuntu2.7), libisc-export160:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), do-agent:amd64 (0.5.0, 0.5.1), python3-update-manager:amd64 (1:16.04.7, 1:16.04.9), linux-virtual:amd64 (4.4.0.89.95, 4.4.0.96.101), libmspack0:amd64 (0.5-1, 0.5-1ubuntu0.16.04.1), samba-common:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.9, 2:4.3.11+dfsg-0ubuntu0.16.04.10), liblwres141:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), ubuntu-core-launcher:amd64 (2.25, 2.27.5), libcryptsetup4:amd64 (2:1.6.6-5ubuntu2, 2:1.6.6-5ubuntu2.1), libsmbclient:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.9, 2:4.3.11+dfsg-0ubuntu0.16.04.10), smbclient:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.9, 2:4.3.11+dfsg-0ubuntu0.16.04.10), samba-common-bin:amd64 (2:4.3.11+dfsg-0ubuntu0.16.04.9, 2:4.3.11+dfsg-0ubuntu0.16.04.10), linux-headers-virtual:amd64 (4.4.0.89.95, 4.4.0.96.101), libdns162:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), libxml2:amd64 (2.9.3+dfsg1-1ubuntu0.2, 2.9.3+dfsg1-1ubuntu0.3), logrotate:amd64 (3.8.7-2ubuntu2.16.04.1, 3.8.7-2ubuntu2.16.04.2), apparmor:amd64 (2.10.95-0ubuntu2.6, 2.10.95-0ubuntu2.7), libisccc140:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), linux-image-virtual:amd64 (4.4.0.89.95, 4.4.0.96.101), libpython3.5-stdlib:amd64 (3.5.2-2ubuntu0~16.04.1, 3.5.2-2ubuntu0~16.04.2), libbind9-140:amd64 (1:9.10.3.dfsg.P4-8ubuntu1.7, 1:9.10.3.dfsg.P4-8ubuntu1.8), libpython3.5-minimal:amd64 (3.5.2-2ubuntu0~16.04.1, 3.5.2-2ubuntu0~16.04.2), cryptsetup:amd64 (2:1.6.6-5ubuntu2, 2:1.6.6-5ubuntu2.1), lxd-client:amd64 (2.0.10-0ubuntu1~16.04.1, 2.0.10-0ubuntu1~16.04.2)
```
Thanks, and let me know if there is any additional information I can provide.

Matthew

**Comment by dwsteele** [comment] 2017-10-03 13:44
Hi Matthew,

I don't think we are seeing corruption here, even though that's what it looks like.  Can you check the files in question with `gzip -t` to verify that?  You should be able to find the file from the second log at `/var/lib/pgbackrest/backup/leads/20171002-060046F/pg_data/base/31435562/69497207.13.gz`

What I think is happening is the remote is terminating unexpectedly and maybe throwing some output to `stdout`.

Before we look at that can you verify that the files are OK?

**Comment by fishermd13** [comment] 2017-10-03 14:46
That's definitely the source of the restore failure.  I tested that particular file (and a few others mentioned in the restore logs) and pretty much consistently saw "invalid compressed data--format violated".

I forced a filesystem check to see if there were any problems on that level, but everything came back clean.  I'm in the process of doing a surface scan as well--but I don't anticipate anything different.

I've not seen any problems reported in any of the backup logs, but if an error was encountered writing, compressing or closing the archive, wouldn't there be some indication?

**Comment by dwsteele** [comment] 2017-10-04 12:03
The only thing on your package list that jumps out at me is libapparmor-perl.  What mode are you running in?  Any policies?

**Comment by fishermd13** [comment] 2017-10-04 12:56
Aside from what is baked into the default 16.04 install (and appended by non-apparmor packages), I haven't configured or enabled anything that should affect this.  aa-status indicates 13 profiles are loaded and in enforce mode--but nothing manually set, nor warnings generated as a result of pgbackrest illegal access.

```
13 profiles are loaded.
13 profiles are in enforce mode.
   /sbin/dhclient
   /usr/bin/lxc-start
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/lxd/lxd-bridge-proxy
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/sbin/tcpdump
   lxc-container-default
   lxc-container-default-cgns
   lxc-container-default-with-mounting
   lxc-container-default-with-nesting
0 profiles are in complain mode.
0 processes have profiles defined.
0 processes are in enforce mode.
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
```

**Comment by dwsteele** [comment] 2017-10-05 21:03
I'm not sure where to go next.  It doesn't look like this is a growing file issue like we saw a while back and I just haven't been seeing this kind of corruption in other installations.

The only thing I can think of is to try some backups with `compress=n` if you have the space.  Compression is still used over the network but the data is decompressed on the destination side before being written to disk.  This would give us some idea if the corruption is happening during the backup, or later somehow.

**Comment by fishermd13** [comment] 2017-10-06 12:56
I agree that it looks like a completely different problem.  I'll do a bit more testing over the next few days (including backing up one of the smaller databases without compressions) and follow up if anything proves noteworthy.

Thank you again.

**Comment by dwsteele** [comment] 2017-10-16 13:01
Were you able to run some of those smaller backups?  Any results?

**Comment by fishermd13** [comment] 2017-10-16 13:31
I was only able to attempt a backup/restore of one of the databases without compression and that failed as well (although not from a corrupted compressed file).  Unfortunately, I don't have the output of that particular error to pass on.

As a last ditch effort, however, I built up a completely new backup server using Debian 9 (as opposed to Ubuntu 16.04) with the latest version of pgbackrest.  After a full backup,  I tested the compressed files, and saw the same kinds of errors with the gzipped data.

Unfortunately, we don't have any of those installations any more, so I won't be able to provide any additional details--but I did check the version of the compression libraries and they were not the same--so that probably isn't the source of the problem.

**Comment by slardiere** [comment] 2017-10-16 16:19
I've got the same problem on 2 differents systems : Debian 9.2, up to date, pgbackrest 1.24-1.pgdg90+1  
The restore terminate with the following message : 

~~~
DEBUG: Protocol::Local::Process->hostConnect: start local process: iHostConfigIdx = 1, iHostIdx = 0, iHostProcessIdx = 0, iProcessId = 1, strHostType = backup
DEBUG: Protocol::Local::Master->new(): iProcessIdx = 1, strCommand = /usr/bin/pgbackrest --command=restore --db1-path=/home/postgres/10/restore/ --host-id=1 --process=1 --repo-path=/home/backrest --stanza=nkaal10 --type=backup local
DEBUG: Protocol::Command::Master->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 1830, strCommand = /usr/bin/pgbackrest --command=restore --db1-path=/home/postgres/10/restore/ --host-id=1 --process=1 --repo-path=/home/backrest --stanza=nkaal10 --type=backup local, strId = 'local-1', strName = local
DEBUG: Protocol::Local::Process->hostConnect=>: bResult = true
DEBUG: Protocol::Local::Process->init: init local process: iDirection = 1, iHostIdx = 0, iProcessId = 1, iQueueIdx = 0, iQueueLastIdx = 0
DEBUG: Protocol::Local::Process->init=>: bResult = true
DEBUG: Protocol::Local::Process->process: get job from queue: iHostIdx = 0, iProcessId = 1, strKey = pg_data/base/28493/29416, strQueueIdx = 0
ERROR [042]: : process 'local-1' terminated unexpectedly [000]
DEBUG: Common::Exit::exitSafe(): iExitCode = [undef], oException = [object], strSignal = [undef]
DEBUG: Protocol::Helper::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
DEBUG: Protocol::Helper::protocolDestroy=>: iExitStatus = 0
DEBUG: Common::Lock::lockRelease(): bFailOnNoLock = false
INFO: restore command end: aborted with exception [042]
DEBUG: Common::Exit::exitSafe=>: iExitCode = 42
~~~
HtH
Sébastien

**Comment by dwsteele** [comment] 2017-10-17 13:02
Hi Sébastien,

Can you provide the first line in the log for the above output?  Should start with `INFO: restore command begin 1.24`.

**Comment by slardiere** [comment] 2017-10-17 21:08
See attached file : [pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/1392645/pgbackrest.log)

**Comment by slardiere** [comment] 2017-11-29 16:04
to me, the problem is still here, and as i'm still unable to restore, i think it's actually a bug. Is there some news ? Do I need to test something else ?

**Comment by slardiere** [comment] 2017-11-30 09:39
Do I have to open a new issue, then ?

**Comment by dwsteele** [comment] 2017-11-30 13:56
That would be best.  I'm still working on the OP's issue but I don't think you are having the same problem.  We should work it separately.

**Comment by dwsteele** [comment] 2017-12-27 23:27
Hi,

We have been trying for a while to reproduce this error but have not been successful.  It hasn't been reported by anyone else and has not shown up in any systems that we administer.

I'm closing this issue because there's no new information to help identify the problem.  Please feel free to respond with any new information if you are still experiencing this issue.

Regards,
-David

**Closed by dwsteele** 2017-12-27 23:27 UTC
Labels: question
