### ISSUE TITLE
timestampFormat calls sprintf with redundant parameters

### ISSUE THREAD

**Issue by disco-stu** [pgbackrest/pgbackrest#196] opened 2016-05-20 22:29 UTC
The behavior of sprintf was changed somewhere in perl 5.2x.x [1]. sprintf throws a warning if more arguments are given then taken by the format string.

For example:
> perl -wle 'use warnings FATAL => qw(all); printf("%s%s\n", "foo", "bar")' 
> foobar

works as expected, but

> perl -wle 'use warnings FATAL => qw(all); printf("%s\n", "foo", "bar")' 
> Redundant argument in printf at -e line 1.

doesn't.

This will lead to errors when calling pgbackrest backup:
> sudo -u postgres pgbackrest backup --stanza 9.5-main
> 2016-05-20 21:58:12.961 T00   WARN: no prior backup exists, incr backup has been changed to full
> 2016-05-20 21:58:14.229 T00   WARN: aborted backup of same type exists, will be cleaned to remove invalid files and resumed
> 2016-05-20 21:58:17.834 T00  ERROR: [140]: process terminated due to an unhandled exception
> Redundant argument in sprintf at /usr/share/perl5/pgBackRest/Common/String.pm line 175.
>  at /usr/bin/pgbackrest line 14.
> 	main::__ANON__("Redundant argument in sprintf at /usr/share/perl5/pgBackRest/"...) called at /usr/share/perl5/pgBackRest/Common/String.pm line 175
> 	pgBackRest::Common::String::timestampFormat("%4d", 1463774297) called at /usr/share/perl5/pgBackRest/Backup.pm line 908
> 	pgBackRest::Backup::process(pgBackRest::Backup=HASH(0x1a2f4a8)) called at /usr/bin/pgbackrest line 201
> 	eval {...} called at /usr/bin/pgbackrest line 32
>  at /usr/bin/pgbackrest line 237.
>  at /usr/bin/pgbackrest line 14.
> 	main::__ANON__("Redundant argument in sprintf at /usr/share/perl5/pgBackRest/"...) called at /usr/share/perl/5.22/Carp.pm line 167
> 	Carp::confess("Redundant argument in sprintf at /usr/share/perl5/pgBackRest/"...) called at /usr/bin/pgbackrest line 237

[1] https://rt.perl.org/Public/Bug/Display.html?id=121025

**Comment by disco-stu** [comment] 2016-05-20 22:41
I've prepared a possible fix: https://github.com/pgbackrest/pgbackrest/pull/197.

**Comment by dwsteele** [comment] 2016-05-23 14:43
Interesting, this seems distinctly un-Perl-like.  I'm going to get a version of Perl into my regression suite that breaks in this way then apply your patch.

**Comment by dwsteele** [comment] 2016-05-24 12:36
OK, I have a fix prepared for this (bd3c74a1055b9492ed1b335101f810a4e47565e0) but can't commit it yet since it will require starting a new release cycle.  I have a series of doc changes to commit first but will do this (hopefully) tomorrow.

**Comment by dwsteele** [comment] 2016-05-24 12:42
BTW, I like to set --author when committing submissions but your credativ address does not seem to be associated with your github accoount.  Do you want to associate that or should I use another address?

**Comment by disco-stu** [comment] 2016-05-24 15:56
Please use my credativ address. Thanks.

**Comment by dwsteele** [comment] 2016-05-26 15:26
Fixed in 3d437d9278488d25b30da828a.

**Closed by dwsteele** 2016-05-26 15:26 UTC
Labels: bug (code)
