### ISSUE TITLE
Instability of allTest.c

### ISSUE THREAD

**Issue by KnightMurloc** [pgbackrest/pgbackrest#2463] opened 2024-10-11 09:41 UTC
I have investigated the frequent test failures in the allTest.c file and found the reason for their instability.
The following confluence of circumstances leads to a fail:
1. After restoring the Postgres instance, the recovery process starts. Which calls the asynchronous archive-get.
2. After archive-get checks the existence of the queue directory, but before writing the WAL file, there are restores in the next test is begun. Which leads to the deletion of the queue directory.
3. Since the directory no longer exists, writing the WAL file will fail, and archive-get will write the error file to the queue.
4. A new Postgres instance will start, and the recovery process will begin, which requests the WAL file.
5. The new archive-get looks into the queue directory, finds the error file, and throws out the error, after which the Postgres recovery fails. Because the previous archive-get background process has not finished yet.

I managed to reproduce this problem manually on the main branch. A recent patch (https://github.com/pgbackrest/pgbackrest/commit/1020bc117ab2e116abb41eebd40216726a3d2561) may have masked the problem.
It seems that the problem is not related to the Postgres version, so it may be worth making more general fix. Would you be interested in accepting such a patch?
Perhaps it is also worth prohibiting the simultaneous work of archive-get and restore on the same stanza?

**Comment by dwsteele** [comment] 2024-10-11 09:52
I've been trying for forever to reproduce this in a test env and finally just gave up and shuffled versions around so it would work -- guessing (wrongly it sounds) that new postgres on older Debian was causing some timing issues.

> It seems that the problem is not related to the Postgres version, so it may be worth making more general fix. Would you be interested in accepting such a patch?

I would definitely be interested in a patch.

> Perhaps it is also worth prohibiting the simultaneous work of archive-get and restore on the same stanza?

Maybe -- but we would need a lock and we don't currently lock on read-only ops. For this we'd need a different lock architecture I think, since it would be valid to do multiple restores from a single stanza as long as the target paths are different.

**Comment by dwsteele** [comment] 2024-11-11 15:53
Closing since there is a PR.

**Closed by dwsteele** 2024-11-11 15:53 UTC
Labels: enhancement, module [test]
