### ISSUE TITLE
How can I change archive location from /pgbackup/vhr_test/archive/Vehiclereport to /pgarchive ?

### ISSUE THREAD

**Issue by nikhilchandra-kulkarni** [pgbackrest/pgbackrest#273] opened 2016-10-18 13:05 UTC
I have successfully configured pgbackrest on server. Thanks for nice documentation.
Now I want to change archive location as I have different file systems for backup and archive.

**Comment by dwsteele** [comment] 2016-10-18 14:56
Currently there is no way to specify the archive directory, but you can mount the archive file system at [repo-path]/archive or symlink it at that path.

**Comment by nikhilchandra-kulkarni** [comment] 2016-10-18 15:13
Thanks for quick response !  I was using pigz for archive_command parameter i.e. pigz < %p > /pgarchive/%f Can I use same command for archive-push ?

**Comment by dwsteele** [comment] 2016-10-18 20:26
You can't use pigz with archive-push, but async archiving will support parallel compression (like backup and restore) sometime this fall/winter.

**Comment by MichaelDBA** [comment] 2016-10-18 20:38
Wow, im lookin forward to that since I've had problems with pgbackrest 
archiving not keeping up with heavy update activity, ie, pgxlog location 
gets filled up quickly before  .ready files are removed

**Comment by nikhilchandra-kulkarni** [comment] 2016-10-19 06:14
Hi David,

We also had same issue in past mentioned by Michael, to handle that we had started using PIGZ. Can we exclude achieving section and take only backup using PGBACKREST ?

**Comment by dwsteele** [comment] 2016-10-19 08:28
You can use `archive-check=n` to disable the archive checks in backup.  This cripples restore, of course, but you can write your own recovery.conf files and use `type=preserve` when doing a restore.  I would recommend trying async archiving with a lower compression level first to see if it keeps up.

**Comment by nikhilchandra-kulkarni** [comment] 2016-10-19 12:18
Hi David,

I am getting below error,
-bash-4.2$ pgbackrest --stanza=Vehiclereport --log-level-console=info --no-archive-check check
2016-10-19 08:11:44.519 P00   INFO: check start 1.09: --no-archive-check --db-path=/var/lib/pgsql/data --log-level-console=info --repo-path=/pgbackup/vhr_test --stanza=Vehiclereport
2016-10-19 08:11:45.044 P00   INFO: switch xlog 00000001000000000000009E
ERROR [157]: could not find WAL segment 00000001000000000000009E after 60 second(s)
ERROR [157]: could not find WAL segment 00000001000000000000009E after 60 second(s)
WARN: WAL segment 00000001000000000000009E did not reach the archive:
HINT: Check the archive_command to ensure that all options are correct (especialy --stanza).
HINT: Check the PostreSQL server log for errors.
2016-10-19 08:12:45.055 P00   INFO: check stop

I have changed the archive_command argument to normal.

Seems like it is still searching for log to PGBACKREST created location.

Regards,
Nikhilchandra Kulkarni

**Comment by dwsteele** [comment] 2016-10-19 22:41
The `--no-archive-check` option is not valid with the `check` command.  The primary purpose of the `check` command is to make sure archiving is working so they are not really compatible.

However, you should get an error for specifying that option (and you clearly aren't).  It's also possible that the check command could do the rest of its checks and skip the archive checks in this case.

Even though the `check` command doesn't work an actual backup still should.  Please give that a try and let me know how it goes.  We'll look at improving the `check` command on our side.

**Comment by nikhilchandra-kulkarni** [comment] 2016-10-20 12:42
Yep it went fine thanks.  :-)

**Comment by nikhilchandra-kulkarni** [comment] 2016-10-26 10:47
Hi David,

It went fine but didn't perform well. Please look into it and suggest me what is going wrong here.
We are testing pgbackrest tool on test server and nothing is running on server except pgbackrest.
I have done 3 test run-
1) First run took 9 hours for 80GB with compress level 9
database size=80GB
Backup size: 18GB
pgbackrest --stanza=zabbix_test --log-level-console=info --no-archive-check --compress  --compress-level=9 backup
VCPU:8	Memory:16GB
CentOS Linux release 7.2.1511 (Core)
maintenance_work_mem= 500MB

2) Second run took 36 minutes with default compress level
database size=80GB
Backup size: 19GB
VCPU:8	Memory:16GB
CentOS Linux release 7.2.1511 (Core)
maintenance_work_mem= 2GB
pgbackrest --stanza=zabbix_test --log-level-console=info --no-archive-check --compress  backup 

3) Third run took 78 minutes with same configuration as 2nd run.

**Comment by dwsteele** [comment] 2016-10-27 14:09
Nothing out of the ordinary here.  You can expect performance to vary on virtual machines and `compress-level=9` is horribly slow.  You may have also used up your CPU allowance.

Seeing as you have 8 VCPUs you will probably want to run in parallel mode using the `process-max` option.  I generally wouldn't used more than 25% of available CPUs so `process-max=2` would probably be fine.

**Comment by dwsteele** [comment] 2016-11-01 18:02
I'm going to close this issue, but I've opened #276 and #277 to look at the some of the issues you ran into.  We may leave the check command as it is, since it's main purpose it to make sure *archiving* is working, but we may also change the ERROR to a WARN.  Feel free to subscribe to those issues if you are interested in the outcome.

**Closed by dwsteele** 2016-11-01 18:02 UTC
Labels: question

**Comment by nikhilchandra-kulkarni** [comment] 2016-11-03 05:29
Hi David,
It is working fine for 80GB database, took 17 min to backup and 34 min for restore using process-max option. Next, I will apply it on around 500GB database and let you know about it.
Thanks for your support.

**Comment by dwsteele** [comment] 2016-11-03 09:49
Restore should generally be faster than backup.  If you want multi-processing for restore, though, you'll need to specify `process-max` in `pgbackrest.conf` on the db server where the restore happens.

**Comment by nikhilchandra-kulkarni** [comment] 2016-11-07 10:41
Thanks David, Your suggestion worked for me. Now restore completed in 9 min. :-)
Now I am trying for backup for 500GB and getting below error,
2016-11-07 01:59:01.303 P00   INFO: backup start archive = 00000003000018D6000000E8, lsn = 18D6/E8000020
ERROR [145]: link /var/lib/pgsql/data/pg_tblspc/166286 (/zabbix_partition10) references a subdirectory of or the same directory as link /var/lib/pgsql/data/pg_tblspc/92546 (/zabbix_partition1)
2016-11-07 01:59:05.077 P00   INFO: backup stop 
I am using multiple file system and table partitioning.

**Comment by dwsteele** [comment] 2016-11-07 10:53
This may be a variation of a bug that I thought I had squashed before.  I'll look into it and get back to you.

**Comment by dwsteele** [comment] 2016-11-07 12:38
Yeah, it's a bug.  I have fixed at: https://github.com/pgbackrest/pgbackrest/commit/dcdc11455dfb45316c90f96ba19024c3aacaa3f9#diff-9b7d8139e3a384c26558352aa6999ac3

It's running through regression now and I will commit to mater and release tomorrow (expect packages on Wednesday).  Can I get your full name for the release notes?

**Comment by nikhilchandra-kulkarni** [comment] 2016-11-07 12:48
Thank you for your help, We will test it once package is available.
Regards,
Nikhilchandra Kulkarni

**Comment by dwsteele** [comment] 2016-11-07 14:39
Committed to master at dd621081b95e5dcf737807053346b7c89e9f962d.

**Comment by dwsteele** [comment] 2016-11-08 11:02
This has been released https://github.com/pgbackrest/pgbackrest/releases/tag/release/1.10.  If you are using packages you'll need to wait for the maintainers to update the repos.

**Comment by nikhilchandra-kulkarni** [comment] 2016-11-09 11:05
Hi David,

Thanks for fixing issue. I had downloaded and configure new version 1.10 and it went fine.
Took 2 hrs for backup approx. 500 GB database using 4 max process.

Regards,
Nikhilchandra Kulkarni

**Comment by dwsteele** [comment] 2016-11-09 11:13
I glad it worked for you, and thank you for reporting the issue.

**Comment by dwsteele** [comment] 2016-12-04 16:09
The issue with invalid options not throwing an error was fixed in f823a25ac20fac867038a4797d96c26e27f8388b and will go out with v1.12.
