### ISSUE TITLE
Error while running full backup - ERROR: [057]: raised from remote process on 'smoermspgdbp04p.jhaerms.com': server closed the connection unexpectedly

### ISSUE THREAD

**Issue by rtammineni** [pgbackrest/pgbackrest#719] opened 2019-05-01 01:41 UTC
pgBackRest version:
pgBackRest 2.12

PostgreSQL version:
9.4

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.6.1810 (Core)

Did you install pgBackRest from source or from a package?
source

Please attach the following as applicable:

postgresql.conf:
archive_mode = on
archive_command = 'pgbackrest --stanza=cluster04 archive-push %p && cp %p /pg_archive/pgsql-9.4/data/%f'
wal_level = hot_standby
max_wal_senders = 20
listen_addresses = '*'
port = 5432

pgbackrest.conf:
[cluster04]
pg1-host=smoermspgdbp04p.jhaerms.com
pg1-path=/pg_data/pgsql-9.4/data
pg2-host=smoermspgdbs04p.jhaerms.com
pg2-path=/pg_data/pgsql-9.4/data
repo1-path=/pg_backup/ERMS/SMOERMSPGDB-04

[global]
backup-standby=y
repo1-retention-diff=2
repo1-retention-full=1
repo1-retention-archive=1
process-max=4
repo1-cipher-type=none
start-fast=y
stop-auto=y
log-level-console=info
log-level-file=detail

[global:archive-push]
compress-level=3

Describe the issue:

I am getting the following error during full backup.

2019-04-30 18:48:47.860 P00   INFO: full backup size = 368.3GB
2019-04-30 18:48:47.861 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2019-04-30 18:48:47.866 P00  ERROR: [057]: raised from remote process on 'smoermspgdbp04p.jhaerms.com': server closed the connection unexpectedly
                                                This probably means the server terminated abnormally
                                                before or while processing the request.:
                                        select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn
2019-04-30 18:48:47.885 P00   INFO: backup command end: aborted with exception [057]

========

**Comment by dwsteele** [comment] 2019-05-01 11:30
It looks like the Postgres backend crashed.  Are you up to date on 9.4 minor versions?

**Comment by rtammineni** [comment] 2019-05-01 14:47
Hi David,

Database did not crash.  Both primary and standby databases are running fine.  Yes, we are up to date with Postgres version.  Its working fine with other cluster.  But the other cluster database size is smaller than this one.

==== Standby database log details around that time
2019-04-30 18:43:14 CDT  @ 8677 sql_error_code = 00000LOG:  restartpoint complete: wrote 9 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 2 recycled; write=0.817 s, sync=0.
003 s, total=0.865 s; sync files=7, longest=0.001 s, average=0.000 s
2019-04-30 18:43:14 CDT  @ 8677 sql_error_code = 00000LOG:  recovery restart point at 8A4/38000060
2019-04-30 18:43:14 CDT  @ 8677 sql_error_code = 00000DETAIL:  last completed transaction was at log time 2019-04-30 18:37:44.656295-05
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 14909 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] postgres@postgres 14909 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 17345 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] postgres@postgres 17345 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 17362 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] postgres@postgres 17362 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 17442 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] care_user@pg_care 17442 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 17449 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] postgres@postgres 17449 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 17480 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] postgres@postgres 17480 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 17493 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] postgres@postgres 17493 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:45:07 CDT [local] [unknown]@[unknown] 17502 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:45:07 CDT [local] postgres@postgres 17502 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:45:17 CDT 10.222.126.9(35484) [unknown]@[unknown] 17505 sql_error_code = 00000LOG:  connection received: host=10.222.126.9 port=35484
2019-04-30 18:45:17 CDT 10.222.126.9(35484) care_user@pg_care 17505 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-04-30 18:50:04 CDT [local] [unknown]@[unknown] 32016 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:50:04 CDT [local] postgres@postgres 32016 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 18:50:04 CDT [local] [unknown]@[unknown] 32018 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:50:04 CDT [local] care_user@pg_care 32018 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-04-30 18:50:17 CDT 10.222.126.9(35572) [unknown]@[unknown] 32051 sql_error_code = 00000LOG:  connection received: host=10.222.126.9 port=35572
2019-04-30 18:50:17 CDT 10.222.126.9(35572) care_user@pg_care 32051 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-04-30 18:53:29 CDT  @ 8677 sql_error_code = 00000LOG:  restartpoint starting: time
2019-04-30 18:53:34 CDT  @ 8677 sql_error_code = 00000LOG:  restartpoint complete: wrote 52 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 2 recycled; write=5.123 s, sync=0
.007 s, total=5.137 s; sync files=15, longest=0.001 s, average=0.000 s
2019-04-30 18:53:34 CDT  @ 8677 sql_error_code = 00000LOG:  recovery restart point at 8A4/3A04A660
2019-04-30 18:53:34 CDT  @ 8677 sql_error_code = 00000DETAIL:  last completed transaction was at log time 2019-04-30 18:49:44.405003-05
2019-04-30 18:55:04 CDT [local] [unknown]@[unknown] 10982 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 18:55:04 CDT [local] care_user@pg_care 10982 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-04-30 18:55:12 CDT 10.222.126.9(35670) [unknown]@[unknown] 10996 sql_error_code = 00000LOG:  connection received: host=10.222.126.9 port=35670
2019-04-30 18:55:12 CDT 10.222.126.9(35670) care_user@pg_care 10996 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-04-30 19:00:11 CDT [local] [unknown]@[unknown] 8164 sql_error_code = 00000LOG:  connection received: host=[local]
2019-04-30 19:00:11 CDT [local] postgres@postgres 8164 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-04-30 19:00:12 CDT [local] [unknown]@[unknown] 13008 sql_error_code = 00000LOG:  connection received: host=[local]

===== Other cluster (05) backup log.  This back is successfully completed. 
2019-04-30 13:57:01.949 P00   INFO: full backup size = 74.5GB
2019-04-30 13:57:01.950 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2019-04-30 13:57:03.056 P00   INFO: backup stop archive = 000000020000340C00000004, lsn = 340C/4024488
2019-04-30 13:57:05.260 P00   INFO: new backup label = 20190430-134501F
2019-04-30 13:57:05.845 P00   INFO: backup command end: completed successfully (724903ms)
2019-04-30 13:57:05.846 P00   INFO: expire command begin
2019-04-30 13:57:05.873 P00   INFO: expire command end: completed successfully (27ms)

thanks
ravi

**Comment by dwsteele** [comment] 2019-05-01 17:56
Looks like the backend crashed to me (or somebody terminated it -- or the connection died):
```
2019-04-30 18:48:47.866 P00 ERROR: [057]: raised from remote process on 'smoermspgdbp04p.jhaerms.com': server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.:
select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn
2019-04-30 18:48:47.885 P00 INFO: backup command end: aborted with exception [057]
```
Doesn't mean your entire cluster went down.  Check the postgres logs and your version of 9.4.

**Comment by rtammineni** [comment] 2019-05-01 22:49
We are encountering the same problem on another server.  The size of this database is 1.6TB.  We did not see any issues in the database logs.  I have posted the logs from both servers. According to my observation, if database size is less than 500GB then no issues but if its greater than 500GB then we are seeing this issue.

This is our Postgres version.
 PostgreSQL 9.4.19 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit

We cannot change our version because they are so many components depend on it.


2019-05-01 17:25:07.657 P09   INFO: backup file smoermspgdbp03p.jhaerms.com:/pg_data/pgsql-9.4/data/base/1/12825 (0B, 100%)
2019-05-01 17:25:09.116 P00   INFO: full backup size = 1540.6GB
2019-05-01 17:25:09.118 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2019-05-01 17:25:09.126 P00  ERROR: [057]: raised from remote process on 'smoermspgdbs03p.jhaerms.com': server closed the connection unexpectedly
                                                This probably means the server terminated abnormally
                                                before or while processing the request.:
                                        select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn
2019-05-01 17:25:09.233 P00   INFO: backup command end: aborted with exception [057]


############>>>>>>>>> Standby server logs
2019-05-01 17:20:05 CDT [local] [unknown]@[unknown] 16475 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:20:05 CDT [local] care_user@pg_care 16475 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-05-01 17:20:06 CDT  @ 27136 sql_error_code = 00000LOG:  restartpoint starting: time
2019-05-01 17:20:19 CDT  @ 27136 sql_error_code = 00000LOG:  restartpoint complete: wrote 137 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 2 recycled; write=13.670 s, sync=0.037 s,
 total=13.720 s; sync files=90, longest=0.002 s, average=0.000 s
2019-05-01 17:20:19 CDT  @ 27136 sql_error_code = 00000LOG:  recovery restart point at 34EE/43029BC8
2019-05-01 17:20:19 CDT  @ 27136 sql_error_code = 00000DETAIL:  last completed transaction was at log time 2019-05-01 17:19:46.033697-05
2019-05-01 17:20:23 CDT 10.222.126.20(53312) [unknown]@[unknown] 16759 sql_error_code = 00000LOG:  connection received: host=10.222.126.20 port=53312
2019-05-01 17:20:23 CDT 10.222.126.20(53312) care_user@pg_care 16759 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-05-01 17:25:04 CDT [local] [unknown]@[unknown] 27665 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:25:04 CDT [local] care_user@pg_care 27665 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-05-01 17:25:17 CDT 10.222.126.20(53434) [unknown]@[unknown] 27962 sql_error_code = 00000LOG:  connection received: host=10.222.126.20 port=53434
2019-05-01 17:25:17 CDT 10.222.126.20(53434) care_user@pg_care 27962 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-05-01 17:30:08 CDT [local] [unknown]@[unknown] 24890 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:30:08 CDT [local] postgres@postgres 24890 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-05-01 17:30:08 CDT [local] [unknown]@[unknown] 30127 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:30:08 CDT [local] postgres@postgres 30127 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-05-01 17:30:08 CDT [local] [unknown]@[unknown] 30164 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:30:08 CDT [local] postgres@postgres 30164 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-05-01 17:30:08 CDT [local] [unknown]@[unknown] 30230 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:30:08 CDT [local] postgres@postgres 30230 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres
2019-05-01 17:30:08 CDT [local] [unknown]@[unknown] 30264 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:30:08 CDT [local] postgres@postgres 30264 sql_error_code = 00000LOG:  connection authorized: user=postgres database=postgres

############>>>>>>>>> Primary server logs
2019-05-01 17:24:47 CDT 10.222.126.85(47236) [unknown]@[unknown] 23103 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47236
2019-05-01 17:24:47 CDT 10.222.126.85(47236) testfipgadmin@testfi 23103 sql_error_code = 00000LOG:  connection authorized: user=testfipgadmin database=testfi
2019-05-01 17:24:56 CDT 10.222.126.85(47240) [unknown]@[unknown] 23116 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47240
2019-05-01 17:24:56 CDT 10.222.126.85(47240) fi2244pgadmin@fi2244 23116 sql_error_code = 00000LOG:  connection authorized: user=fi2244pgadmin database=fi2244
2019-05-01 17:24:56 CDT 10.222.126.85(47242) [unknown]@[unknown] 23117 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47242
2019-05-01 17:24:56 CDT 10.222.126.85(47242) fi25741pgadmin@fi25741 23117 sql_error_code = 00000LOG:  connection authorized: user=fi25741pgadmin database=fi25741
2019-05-01 17:24:57 CDT 10.222.126.85(47244) [unknown]@[unknown] 23118 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47244
2019-05-01 17:24:57 CDT 10.222.126.85(47244) fi14289pgadmin@fi14289 23118 sql_error_code = 00000LOG:  connection authorized: user=fi14289pgadmin database=fi14289
2019-05-01 17:24:58 CDT 10.222.126.85(47246) [unknown]@[unknown] 23119 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47246
2019-05-01 17:24:58 CDT 10.222.126.85(47246) fi55435pgadmin@fi55435 23119 sql_error_code = 00000LOG:  connection authorized: user=fi55435pgadmin database=fi55435
2019-05-01 17:24:58 CDT 10.222.126.85(47248) [unknown]@[unknown] 23120 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47248
2019-05-01 17:24:58 CDT 10.222.126.85(47248) fi25741pgadmin@fi25741 23120 sql_error_code = 00000LOG:  connection authorized: user=fi25741pgadmin database=fi25741
2019-05-01 17:24:58 CDT 10.222.126.85(47250) [unknown]@[unknown] 23121 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47250
2019-05-01 17:24:58 CDT 10.222.126.85(47250) fi57089pgadmin@fi57089 23121 sql_error_code = 00000LOG:  connection authorized: user=fi57089pgadmin database=fi57089
2019-05-01 17:24:58 CDT 10.222.126.85(47252) [unknown]@[unknown] 23122 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47252
2019-05-01 17:24:58 CDT 10.222.126.85(47252) testfipgadmin@testfi 23122 sql_error_code = 00000LOG:  connection authorized: user=testfipgadmin database=testfi
2019-05-01 17:24:59 CDT 10.222.126.85(47254) [unknown]@[unknown] 23124 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47254
2019-05-01 17:24:59 CDT 10.222.126.85(47254) demofipgadmin@demofi 23124 sql_error_code = 00000LOG:  connection authorized: user=demofipgadmin database=demofi
2019-05-01 17:25:00 CDT 10.222.126.85(47256) [unknown]@[unknown] 23125 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47256
2019-05-01 17:25:00 CDT 10.222.126.85(47256) fi3226pgadmin@fi3226 23125 sql_error_code = 00000LOG:  connection authorized: user=fi3226pgadmin database=fi3226
2019-05-01 17:25:02 CDT 10.222.126.85(47258) [unknown]@[unknown] 24282 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47258
2019-05-01 17:25:02 CDT 10.222.126.85(47258) fi57089pgadmin@fi57089 24282 sql_error_code = 00000LOG:  connection authorized: user=fi57089pgadmin database=fi57089
2019-05-01 17:25:03 CDT 10.222.126.85(47260) [unknown]@[unknown] 27954 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47260
2019-05-01 17:25:03 CDT 10.222.126.85(47260) salesfipgadmin@salesfi 27954 sql_error_code = 00000LOG:  connection authorized: user=salesfipgadmin database=salesfi
2019-05-01 17:25:03 CDT 10.222.126.85(47262) [unknown]@[unknown] 28353 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47262
2019-05-01 17:25:03 CDT 10.222.126.85(47262) fi3226pgadmin@fi3226 28353 sql_error_code = 00000LOG:  connection authorized: user=fi3226pgadmin database=fi3226
2019-05-01 17:25:04 CDT [local] [unknown]@[unknown] 32688 sql_error_code = 00000LOG:  connection received: host=[local]
2019-05-01 17:25:04 CDT [local] care_user@pg_care 32688 sql_error_code = 00000LOG:  connection authorized: user=care_user database=pg_care
2019-05-01 17:25:10 CDT 10.222.126.85(47264) [unknown]@[unknown] 480 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47264
2019-05-01 17:25:10 CDT 10.222.126.85(47264) fi57089pgadmin@fi57089 480 sql_error_code = 00000LOG:  connection authorized: user=fi57089pgadmin database=fi57089
2019-05-01 17:25:10 CDT 10.222.126.85(47266) [unknown]@[unknown] 481 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47266
2019-05-01 17:25:10 CDT 10.222.126.85(47266) fi57089pgadmin@fi57089 481 sql_error_code = 00000LOG:  connection authorized: user=fi57089pgadmin database=fi57089
2019-05-01 17:25:10 CDT 10.222.126.85(47268) [unknown]@[unknown] 482 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47268
2019-05-01 17:25:10 CDT 10.222.126.85(47268) demofipgadmin@demofi 482 sql_error_code = 00000LOG:  connection authorized: user=demofipgadmin database=demofi
2019-05-01 17:25:10 CDT 10.222.126.85(47270) [unknown]@[unknown] 483 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47270
2019-05-01 17:25:10 CDT 10.222.126.85(47270) demofipgadmin@demofi 483 sql_error_code = 00000LOG:  connection authorized: user=demofipgadmin database=demofi
2019-05-01 17:25:10 CDT 10.222.126.85(47272) [unknown]@[unknown] 484 sql_error_code = 00000LOG:  connection received: host=10.222.126.85 port=47272
2019-05-01 17:25:10 CDT 10.222.126.85(47272) fi3226pgadmin@fi3226 484 sql_error_code = 00000LOG:  connection authorized: user=fi3226pgadmin database=fi3226

**Comment by dwsteele** [comment] 2019-05-02 12:04
Moving to 9.4.21 shouldn't cause any compatibility issues and it's always best to stay up to date on minor releases.

That said, I don't see anything in the release notes about bug fixes in this area.  There's nothing to go on in the postgres logs so I think we'll need to try running stop backup manually.

Start a psql connection as postgres and start a backup:
```
select pg_start_backup('test', true);
```
Then stop it:
```
select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn;
```

Try these one after the other and if that works then separate them by the length of a backup.

**Comment by rtammineni** [comment] 2019-05-02 14:53
Did not understand clearly.  Do you want me to follow these steps from backup server?  

select pg_start_backup('test', true);
pgbackrest --stanza=cluster04 --type=full --log-level-console=info backup 
select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn;

What about these parameters?
start-fast=y
stop-auto=y

**Comment by dwsteele** [comment] 2019-05-02 16:36
Run these in a `psql` connected to the primary as `postgres`.  The error appears to be in Postgres so I want to see if we can reproduce it without pgBackRest in the loop.

**Comment by rtammineni** [comment] 2019-05-02 16:54
I ran one after another and its working fine.  Now i am separating them and running.

postgres=# select pg_start_backup('test', true);
 pg_start_backup
-----------------
 3519/9F0000C8
(1 row)

postgres=# select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn;
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
            to_char             |     pg_xlogfile_name     |      lsn      | labelfile | spcmapfile
--------------------------------+--------------------------+---------------+-----------+------------
 2019-05-02 11:52:29.540030 CDT | 00000002000035190000009F | 3519/9F033EA0 |           |
(1 row)

postgres=# select pg_is_in_backup();
 pg_is_in_backup
-----------------
 f
(1 row)

**Comment by dwsteele** [comment] 2019-05-02 17:18
Cool.  pgBackRest actually holds the connection open for the entire backup so be sure to keep the psql connection open for that long.

That makes me wonder if you have some code somewhere to terminate "idle" connections.  That might be what is going on here.

**Comment by rtammineni** [comment] 2019-05-02 20:48
Ran the same command on the problematic node and its completely disconnected from the host(my ssh window was closed) and i ran the same command from another host and it ran without any issues.  We have idle connection kill script but the same script is running on all nodes.  Looks like there is a problem with that node.  Do you think we have to change any timeout settings at system level?

**Comment by dwsteele** [comment] 2019-05-02 20:57
What's the timeout on your script?  Larger backups will take longer so they might be exceeding the limit.

**Comment by rtammineni** [comment] 2019-05-02 21:00
i set it 1hr 40mins.  Something wrong with that host. I ran again and window was abruptly closed.

**Comment by dwsteele** [comment] 2019-05-02 21:31
That could be an external firewall.  I'd try a local `screen` session and see how that goes.

**Comment by rtammineni** [comment] 2019-05-03 14:42
Issue got resolved after changing /etc/ssh/sshd_config file.  SA team did not configure that file properly and after fixing that file everything is working fine.  We have one more production database close to 3TB and we are deploying PGBackrest next week and hoping that everything goes well there. 
Thank you so much for your help!!

**Comment by dwsteele** [comment] 2019-05-03 15:05
Glad you got it working!

**Closed by dwsteele** 2019-05-03 15:05 UTC
Labels: question
