### ISSUE TITLE
ASSERT: [025]: raised from local-2 protocol: cannot get index 0 from list with 0 value(s)

### ISSUE THREAD

**Issue by sekrause** [pgbackrest/pgbackrest#2271] opened 2024-02-02 08:12 UTC
Backup created with pgBackRest 2.48 (full + differential) for PostgreSQL 14 using an S3 compatible service.

Restore tested with pgBackRest 2.50, it aborts with the following error:

```
ASSERT: [025]: raised from local-2 protocol: cannot get index 0 from list with 0 value(s)
--------------------------------------------------------------------
If SUBMITTING AN ISSUE please provide the following information:

version: 2.50
command: restore
options:
    --delta
    --exec-id=44849-a6a890f8
    --log-level-console=detail
    --pg1-path=/var/lib/postgresql/14/main
    --process-max=2
    --repo1-cipher-pass=<redacted>
    --repo1-cipher-type=aes-256-cbc
    --repo1-path=/pgbackrest
    --repo1-s3-bucket=<redacted>
    --repo1-s3-endpoint=obs.eu-de.otc.t-systems.com
    --repo1-s3-key=<redacted>
    --repo1-s3-key-secret=<redacted>
    --repo1-s3-region=eu-de
    --repo1-type=s3
    --stanza=main

stack trace:
common/type/list.c:lstGet:150:(test build required for parameters)
    ... function(s) omitted ...
command/restore/blockChecksum.c:blockChecksumResult:(trace log level required for parameters)
common/io/filter/group.c:ioFilterGroupClose:(trace log level required for parameters)
common/io/read.c:ioReadClose:(trace log level required for parameters)
command/restore/file.c:restoreFile:(debug log level required for parameters)
command/restore/protocol.c:restoreFileProtocol:(debug log level required for parameters)
protocol/server.c:protocolServerProcess:(debug log level required for parameters)
command/local/local.c:cmdLocal:(debug log level required for parameters)
main.c:main:(debug log level required for parameters)
--------------------------------------------------------------------
```

pgBackRest was installed in Debian from the [PostgreSQL Apt Repository](https://www.postgresql.org/download/linux/debian/).

**Comment by dwsteele** [comment] 2024-02-02 12:39
Interesting. Looks a bit like it is try to calculate block checksums for a zero-length file. 

Please run again with `--log-level-console=debug` and provide the last 10,000 lines of the log. Thanks!

**Comment by dwsteele** [comment] 2024-02-02 13:07
Since this is in a subprocess you'd actually need to add `--log-level-file=debug --log-subprocess`, but unfortunately this is probably not going to give us the information we need.

I have been able to reproduce this but it would also be good to confirm on your side. I'll let you know if I find a way to get the file name out in the logs.

I appears what is happening is you have a file that has been truncated to zero in PGDATA but it is not zero in the backup. This is messing up the delta code.

Quick fix is to remove the `--delta` option (you'll need to manually remove files from PGDATA).

**Comment by dwsteele** [comment] 2024-02-02 13:43
The error is not in this log -- it would have been printed to stderr, so probably ended up on the console.

Looks like these files are not bundled, so we have a chance to capture the file causing the error in the log. Please try again with `--log-level-file=debug --log-subprocess` and this time just send the error. We'll get the log later if we need it.

**Comment by dwsteele** [comment] 2024-02-02 14:32
Closing this since we now have a fix in PR #2272.

It would still be good to verify that this is exactly the error you are experiencing, so please do provide those logs.

**Closed as completed by dwsteele** 2024-02-02 14:32 UTC
Labels: bug, module [core]

**Comment by dwsteele** [comment] 2024-02-02 15:46
Can you try removing `PGDATA/base/16401/4102480397` and then rerunning the delta? I'm curious to know if this is an outlier or if there are number of these files.

**Comment by dwsteele** [comment] 2024-02-02 16:41
No way from the logs to tell exactly which file that is, as far as I can tell. But the main thing is we know this is not a one off.

I noticed the relfileid (4102480397) is extremely large. You are either doing a large number of table creations or truncates?

Also, how would you like your name to appear in the release notes?

**Comment by sekrause** [comment] 2024-02-02 16:51
I've compiled your PR https://github.com/pgbackrest/pgbackrest/pull/2272 and with that build I was able to successfully delta restore again.

> I noticed the relfileid (4102480397) is extremely large. You are either doing a large number of table creations or truncates?

Yeah, it's a database for an application with a "schema per tenant" multi-tenant design, so there are a lot of tables...

> Also, how would you like your name to appear in the release notes?

Sure, why not.

**Comment by dwsteele** [comment] 2024-02-02 18:03
> Sure, why not.

I meant, what name would you like us to use?

**Comment by sekrause** [comment] 2024-02-02 18:06
> I meant, what name would you like us to use?

Sorry, I missed the "how"? :) The full name from profile (Sebastian Krause).

**Comment by rhl-jfm** [comment] 2024-02-20 09:05
FWIW, we ran into the same bug on a delta restore with pgBackRest 2.50. The patch from PR #2272 fixes the problem for us.
