### ISSUE TITLE
invalid range for s3 backup

### ISSUE THREAD

**Issue by tvernick** [pgbackrest/pgbackrest#637] opened 2018-12-14 17:55 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.07

2. PostgreSQL version: 10.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Centos 7.5.1804
Primary and 3 standbys

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[data]
db-user=postgres
db-path=/var/lib/pgsql/10/data
db-port=5432
process-max=8
resume=y
protocol-timeout=35000
db-timeout=30000
buffer-size=4194304
db-socket-path=/tmp
[global]
process-max=4
archive-async=y
spool-path=/var/lib/pgsql/10/walarchive
compress=y
compress-level=3
retention-full=7
retention-diff=12
retention-archive-type=diff
log-level-file=debug
start-fast=y
stop-auto=y
repo-path=/
repo-s3-bucket=xxxx
repo-s3-endpoint=xxxxx
repo-s3-host=xxxx
repo-s3-key=xxxx
repo-s3-key-secret=xxxxxx
repo-s3-region=default
repo-s3-verify-ssl=n
repo-type=s3

7. Describe the issue:
Here is debug log output. Getting an InvalidRange error.

`pgBackRest::Backup::Backup::processManifest(undef, '/var/lib/pgsql/10/data', '/var/lib/pgsql/10/data', 'diff', 10, 1, 0, 'pgBackRest::Manifest=HASH(0x3a01f50)', '20181202-063002F_20181210-063001D', ...) called at /loader/0x2527fa8/pgBackRest/Backup/Backup.pm line 945
                                   	pgBackRest::Backup::Backup::process('pgBackRest::Backup::Backup=HASH(0x2da41b8)') called at /loader/0x2527fa8/pgBackRest/Main.pm line 263
                                   	eval {...} called at /loader/0x2527fa8/pgBackRest/Main.pm line 286
                                   	pgBackRest::Main::main('backup') called at (eval 269) line 1
                                   	eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'backup\')
                                   ;' called at (eval 269) line 0

                                   2018-12-14 17:50:42.769 P00  ERROR: [039]: raised from local-1 process: S3 request error [416] Requested
                                        *** request header ***
                                        POST /backup/data/20181202-063002F_20181210-063001D/pg_data/pg_log/postgresql.csv-20181214.gz?uploads= HTTP/1.1
                                        authorization: AWS4-HMAC-SHA256 Credential=N74UM8XQ7RMX1DPD2M2W/20181214/default/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=184e16c8873cc1d433a63a29d0074e2cc4dab0b0632044ca090afd5d7c44843c
                                        content-length: 0
                                        host: redacted
                                        x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
                                        x-amz-date: 20181214T175042Z
                                        *** response header ***
                                        Content-Length: 239
                                        x-amz-request-id: tx0000000000000008ac124-005c13ed72-6fcb4a-us-east-2
                                        Accept-Ranges: bytes
                                        Content-Type: application/xml
                                        Date: Fri, 14 Dec 2018 17:50:42 GMT
                                        *** response body ***
                                        <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidRange</Code><BucketName>staging-orders-postgres</BucketName><RequestId>tx0000000000000008ac124-005c13ed72-6fcb4a-us-east-2</RequestId><HostId>6fcb4a-us-east-2-stage</HostId></Error>
 at /loader/0x2527fa8/pgBackRest/Common/Log.pm line 586.
                                   	pgBackRest::Common::Log::logException('pgBackRest::Common::Exception=HASH(0x3bc73a8)') called at /loader/0x2527fa8/pgBackRest/Protocol/Local/Process.pm line 349
                                   	pgBackRest::Protocol::Local::Process::process('pgBackRest::Protocol::Local::Process=HASH(0x3998f20)') called at /loader/0x2527fa8/pgBackRest/Backup/Backup.pm line 449
                                   	pgBackRest::Backup::Backup::processManifest(undef, '/var/lib/pgsql/10/data', '/var/lib/pgsql/10/data', 'diff', 10, 1, 0, 'pgBackRest::Manifest=HASH(0x3a01f50)', '20181202-063002F_20181210-063001D', ...) called at /loader/0x2527fa8/pgBackRest/Backup/Backup.pm line 945
                                   	pgBackRest::Backup::Backup::process('pgBackRest::Backup::Backup=HASH(0x2da41b8)') called at /loader/0x2527fa8/pgBackRest/Main.pm line 263
                                   	eval {...} called at /loader/0x2527fa8/pgBackRest/Main.pm line 286
                                   	pgBackRest::Main::main('backup') called at (eval 269) line 1
                                   	eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'backup\')
                                   ;' called at (eval 269) line 0

                                   2018-12-14 17:50:43.738 P00  DEBUG:     Protocol::Command::Master->close=>: iExitStatus = 0
2018-12-14 17:50:43.742 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
2018-12-14 17:50:43.742 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2018-12-14 17:50:43.742 P00  DEBUG:     common/lock::lockRelease: => true
2018-12-14 17:50:43.742 P00  DEBUG:     Main::mainCleanup(): iExitCode = 39
2018-12-14 17:50:43.742 P00  DEBUG:     Protocol::Helper::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
2018-12-14 17:50:43.742 P00  DEBUG:     Protocol::Helper::protocolDestroy=>: iExitStatus = 0
2018-12-14 17:50:43.743 P00   INFO: backup command end: aborted with exception [039]
2018-12-14 17:50:43.743 P00  DEBUG:     common/exit::exitSafe: => 39
2018-12-14 17:50:43.743 P00  DEBUG:     main::main: => 39`

**Comment by dwsteele** [comment] 2018-12-17 17:08
This is a pretty unusual filename for a Postgres cluster: `postgresql.csv-20181214.gz?uploads=`

Looks like a problem with our escaping, but I'd try without that file and see what happens.

**Comment by tvernick** [comment] 2018-12-19 18:16
That's just a log rotated file. The postgres log currently in use just called postgresql.csv, which I believe is default.

**Comment by tvernick** [comment] 2018-12-19 18:19
I did try removing those rotated files and it seems to run the backup without error now.

**Comment by dwsteele** [comment] 2018-12-19 20:46
Ah, yeah, not sure what I was thinking about the ? mark.  That's obviously part of the query we write.

This is pretty odd.  Looking at the code, this is where we request an upload id for multi-part upload.  This error makes zero sense in that context.

This error was persistent until you deleted the file?

**Comment by tvernick** [comment] 2018-12-19 20:57
Yes, when I ran a diff backup it would fail with that error. When I removed the log files with the date added it completed successfully. The other odd part is we have other hosts running backups fine that have those log files, and using the same pgbackrest version 2.04

**Comment by dwsteele** [comment] 2018-12-19 21:13
Did you mean 2.07 (as you reported above)?  If you mean 2.04 you should definitely upgrade.  There have been a number of S3 fixes since then.

Or maybe we introduced this bug since 2.04?  Can you verify versions?

**Comment by dwsteele** [comment] 2018-12-20 10:09
OK, so at least it does not look like a regression.

I'll play around with this filename and see if I can figure out what is going on.

**Comment by dwsteele** [comment] 2019-01-26 15:22
I've been trying to reproduce this without success.  Have you seen it again?  Is this against AWS or an S3 gateway?

**Comment by dwsteele** [comment] 2019-02-18 16:46
Closing this issue since we have not been able to reproduce and there has not been any response for a while.

Please let us know if you are still seeing the issue or see it again.  Hopefully then we can gather some more information.

**Closed by dwsteele** 2019-02-18 16:46 UTC
Labels: question
