### ISSUE TITLE
Timeout Using S3 - ERROR: [064]

### ISSUE THREAD

**Issue by jordanenglish** [pgbackrest/pgbackrest#2214] opened 2023-11-01 17:12 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
`2.48-1`
2. PostgreSQL version:
`14.9`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

```
$ uname -r
3.10.0-1160.102.1.el7.x86_64
$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```

4. Did you install pgBackRest from source or from a package?

Package via yum:
```
$ sudo yum info pgbackrest | grep "From repo"
From repo   : pgdg-common
```

5. Please attach the following as applicable:

<details>
  <summary>pgbackrest.conf</summary>

```
[global]
repo1-path=/our/path
repo1-s3-bucket=our-bucket
repo1-s3-endpoint=our-bucket.s3.us-east-1.vpce.amazonaws.com
repo1-s3-region=us-east-1
repo1-s3-key=<redacted>
repo1-s3-key-secret=<redacted>
repo1-cipher-pass=<redacted>
repo1-cipher-type=aes-256-cbc
repo1-retention-full-type=count
repo1-retention-full=4
repo1-retention-diff=6
repo1-type=s3
start-fast=y
spool-path=/var/lib/pgsql/14/data/pg_wal/spool
log-level-console=detail
log-level-file=detail
archive-async=y
archive-timeout=15s
archive-get-queue-max=50G
backup-standby=y

[global:restore]
process-max=24

[global:backup]
process-max=12

[global:archive-get]
process-max=8

[global:archive-push]
process-max=4

[warehouse-data]
pg1-path=/var/lib/pgsql/14/data
pg2-path=/var/lib/pgsql/14/data
pg2-host=data-11.ourdomain.com
```
</details>

<details>
  <summary>postgresql.conf</summary>

```
$ sudo grep "archive_command\|archive_mode\|listen_addresses\|max_wal_senders\|wal_level\|port" /var/lib/pgsql/14/data/postgresql.conf
archive_command = 'pgbackrest --stanza=data archive-push %p'
archive_mode = 'on'
listen_addresses = '*'
max_wal_senders = 2
port = 5432
wal_level = 'logical'
```
</details>

6. Describe the issue:

When running the following backup command(s) it fails:
```
pgbackrest --type=diff --stanza=data backup
pgbackrest --type=full --stanza=data backup
```

Error:
```
2023-11-01 15:14:05.019 P00  ERROR: [064]: timeout after 60000ms waiting for write to 'ourbucket-s3.us-east-1.vpce.amazonaws.com:443'
```

We've increased the timeout via `--io-timeout` to various values but continues to fail.

We've had to rollback to `2.47` to fix.

Snip from trace log (full log attached):
```
       If SUBMITTING AN ISSUE please provide the following information:
       
       version: 2.48
       command: backup
       options: --archive-timeout=15s --backup-standby --exec-id=24595-6e82218e --log-level-console=trace --log-level-file=detail --pg2-host=data-11.ourdomain.com --pg1-path=/var/lib/pgsql/14/data --pg2-path=/var/lib/pgsql/14/data --process-max=12 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/our-data --repo1-retention-diff=6 --repo1-retention-full=4 --repo1-retention-full-type=count --repo1-s3-bucket=pgbackrest-production-bd7be6 --repo1-s3-endpoint=ourbucket.s3.us-east-1.vpce.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --repo1-type=s3 --stanza=our-data --start-fast --type=diff
       
       stack trace:
       common/io/http/request.c:httpRequestProcess:168:(this: {verb: PUT, path: /our-data/backup/our-data/20231031-125906F_20231101-150742D/backup.manifest.copy, contentSize: 2010544, query: null, header: {content-length: '2010544', content-md5: 'EEVXIyo2qtu0iSLmaojdQA==', x-amz-content-sha256: '6512997d206fb8e644aee5169a0e010ba2babc289a24812caf4b45cb96204750', x-amz-date: <redacted>, host: 'pgbackrest-production-bd7be6.ourbucket.s3.us-east-1.vpce.amazonaws.com', authorization: <redacted>}}, waitForResponse: false, contentCache: false)
       common/io/http/request.c:httpRequestNew:(client: {ioClient: {type: tls, driver: {ioClient: {type: socket, driver: {host: pgbackrest-production-bd7be6.ourbucket.s3.us-east-1.vpce.amazonaws.com, port: 443, timeoutConnect: 60000, timeoutSession: 60000}}, timeoutConnect: 60000, timeoutSession: 60000, verifyPeer: true}}, reusable: 1, timeout: 60000}, verb: {"PUT"}, path: {"/our-data/backup/our-data/20231031-125906F_20231101-150742D/backup.manifest.copy"}, param.query: null, param.header: {content-length: '2010544', content-md5: 'EEVXIyo2qtu0iSLmaojdQA==', x-amz-content-sha256: '6512997d206fb8e644aee5169a0e010ba2babc289a24812caf4b45cb96204750', x-amz-date: <redacted>, host: 'pgbackrest-production-bd7be6.ourbucket.s3.us-east-1.vpce.amazonaws.com', authorization: <redacted>}, param.content: {used: 2010544, size: 5242880})
       storage/s3/storage.c:storageS3RequestAsync:(this: {StorageS3}, verb: {"PUT"}, path: {"/our-data/backup/our-data/20231031-125906F_20231101-150742D/backup.manifest.copy"}, param.header: null, param.query: null, param.content: {used: 2010544, size: 5242880}, param.sseKms: true, param.tag: true)
       storage/s3/storage.c:storageS3Request:(this: {StorageS3}, verb: {"PUT"}, path: {"/our-data/backup/our-data/20231031-125906F_20231101-150742D/backup.manifest.copy"}, param.header: null, param.query: null, param.content: {used: 2010544, size: 5242880}, param.allowMissing: false, param.contentIo: false, param.sseKms: true, param.tag: true)
       storage/s3/write.c:storageWriteS3Close:(this: {StorageWriteS3})
       common/io/write.c:ioWriteClose:(this: {IoWrite})
       info/info.c:infoSave:(this: {Info}, write: {IoWrite}, callbackFunction: (function *), callbackData: *void)
       info/manifest.c:manifestSave:(this: {Manifest}, write: {IoWrite})
       command/backup/backup.c:backupManifestSaveCopy:(manifest: {Manifest}, final: false)
       command/backup/backup.c:backupProcess:(backupData: {BackupData}, manifest: {Manifest}, lsnStart: {"26256/1000308"})
       command/backup/backup.c:cmdBackup:(void)
       main.c:main:(debug log level required for parameters)
```

Related comment:
https://github.com/pgbackrest/pgbackrest/issues/2200#issuecomment-1787180087

**Comment by dwsteele** [comment] 2023-11-02 20:35
When you increased `io-timeout`, did you see the new timeout in this error: `timeout after 60000ms waiting for write to 'ourbucket-s3.us-east-1.vpce.amazonaws.com:443'`?

What values did you try for io-timeout?

**Comment by jordanenglish** [comment] 2023-11-02 21:12
> When you increased `io-timeout`, did you see the new timeout in this error: `timeout after 60000ms waiting for write to 'ourbucket-s3.us-east-1.vpce.amazonaws.com:443'`?
> 
> What values did you try for io-timeout?

Yes we did see the value in the error. I believe the highest we went was `120`.

**Comment by adkinsn** [comment] 2023-11-03 14:03
#2200

**Comment by dwsteele** [comment] 2023-11-08 18:35
We have not been able to reproduce this issue, but we are pretty sure it is due to a regression in how retries are handled. See #2221. Closing since there is now a PR for this issue.

**Closed by dwsteele** 2023-11-08 18:35 UTC
Labels: bug, module [core]
