### ISSUE TITLE
Difficult to diagnose issue

### ISSUE THREAD

**Issue by kaceymiri** [pgbackrest/pgbackrest#1392] opened 2021-05-08 00:40 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

pgBackRest 2.33

2. PostgreSQL version:

13.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Ubuntu

4. Did you install pgBackRest from source or from a package?

package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

archive_push was failing with error:

ERROR: [082]: unable to push WAL file '000000010000000000000001' to the archive asynchronously after 60 second(s)
2021-05-07 23:58:43.008 P00   INFO: archive-push command end: aborted with exception [082]

Turns out the issue was the specified spool directory was not created. It would be very helpful if this error message was a little more verbose.

**Comment by pgstef** [comment] 2021-05-10 07:52
Hi,

This message is thrown [here](https://github.com/pgbackrest/pgbackrest/blob/2bfebff2ec73b0af6d937f303fbb9b8a0b8ee649/src/command/archive/push/push.c#L388). And I believe at that point, we don't know "why" the archive wasn't pushed without the defined timeout. Could be anything.

Usually, when `archive-push` fails, it sends its console logs to PG logs. Where you can fin `DETAIL:  The failed archive command was:...` and then try that command manually adding (e.g.) `--log-level-console=debug`. 
Also, you could find more info/debug (depending on your `log-level-file` setting) in the log path, in something like `/var/log/pgbackrest/STANZA-archive-push-async.log`.

The question would more be how/where you've seen those errors. What are your `log-level-console` and `log-level-file` levels ? You don't really provide any interesting information to reproduce your case unfortunately. And I'm not sure we could provide more info at that stage in the code.

So, if you could share more details, perhaps @dwsteele will have better ideas than mine.

Kind regards

**Comment by dwsteele** [comment] 2021-05-10 22:44
> So, if you could share more details, perhaps @dwsteele will have better ideas than mine.

@pgstef, I agree with your analysis. The specific error will be in the postgres log because postgres is the one executing the archive_command. I'm pretty sure that error would clearly state that this is a permissions issue.

**Comment by kaceymiri** [comment] 2021-05-10 23:39
I apologize for not supplying enough information and again for not having retained the console output.

To reproduce the issue you would include  the "spool-path" parameter in the pgbackrest.conf but not create the path.

I could see in the console output that the spool-path was referenced but I did not see(perhaps could have missed) a message stating the file was unable to be read or written to.

Unfortunately the PostgreSQL logs also do not suggest why the command is failing.

2021-05-07 00:03:37.096 UTC,,,53972,,608b3f62.d2d4,10043,,2021-04-29 23:21:06 UTC,,0,LOG,00000,"archive command failed with exit code 82","The failed archive command was: pgbackrest --stanza=cowdb archive-push pg_wal/000000010000000000000001",,,,,,,,"","archiver"
2021-05-07 00:03:37.096 UTC,,,53972,,608b3f62.d2d4,10044,,2021-04-29 23:21:06 UTC,,0,WARNING,01000,"archiving write-ahead log file ""000000010000000000000001"" failed too many times, will try again later",,,,,,,,,"","archiver"

This will now be one of the first things I check should this issue reoccur for me, but I thought it might help others.

**Comment by dwsteele** [comment] 2021-05-11 12:07
PostgreSQL does not log error messages from the archive command when logging in CSV mode. I'm not sure what we can do about this. One option is to run the archive-push command manually when it is failing to get more info.

**Closed** 2021-05-26 18:16 UTC
Labels: question
