### ISSUE TITLE
backup aborted with exception [025] + stack trace storage/storage:storagePath

### ISSUE THREAD

**Issue by vadius45** [pgbackrest/pgbackrest#1177] opened 2020-09-18 17:19 UTC
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.26

2. PostgreSQL version:
11.8

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux release 8.2 (Ootpa)

4. Did you install pgBackRest from source or from a package?
package, pgbackrest-2.26-1.rhel8.x86_64

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

2020-09-18 15:02:03.730 P00   INFO: backup command begin 2.26: --archive-check --archive-copy --config=/pgsql/dba/xxxxxxxxxxx/cfg/pgbackrest.conf --log-level-console=info --log-level-file=info --log-path=/pgsql/dba/xxxxxxxxxxx/log --pg1-path=/pgsql/data/11/xxxxxxxxxxx --pg1-port=25011 --pg1-socket-path=/tmp --process-max=2 --repo1-path=/pgsql/dump/xxxxxxxxxxx --repo1-retention-full=2 --stanza=xxxxxxxxxxx --start-fast --type=full

7. Describe the issue:

One primary, one standby, local repository on each host. 

Full backup fails with : 
2020-09-18 15:02:06.215 P00  WARN: resumable backup 20200905-010508F of same type exists -- remove invalid files and resume
.....
2020-09-18 15:02:27.314 P00   INFO: backup command end: aborted with exception [025]

And the following stack trace is displayed:
2020-09-18 15:02:11.158 P00 ASSERT: [025]: expression '<IDLE>' not valid without callback function
                                    STACK TRACE:
                                    storage/storage:storagePath:718:(test build required for parameters)
                                        ... function(s) omitted ...
                                    command/backup/backup:backupProcess:(debug log level required for parameters)
                                    command/backup/backup:cmdBackup:(debug log level required for parameters)
                                    main:main:(debug log level required for parameters)

In postgresql.log: 
2020-09-18 15:02:11 BST [835960]: [3-1] user=dp-postgres, db=postgres, app=pgBackRest [backup], client=[local], WARNING:  aborting backup due to backend exiting before pg_stop_backup was called

What I did: 
- info / check did not report any issue
- cluster is up and running, and healthy
- clean-up the repository, recreate the stanza / repo, not better
- switchover to the standby, take a full backup there, no issue -> issue comes from the ex-primary cluster
- drop the standby cluster, clone from primary, and switchover
- take a full backup of the primary cluster, no more error. 

I suspect there's something not well managed there, but I could not identify the root cause. Checked also the changelog of 2.27/2.28 and the open issues, it does not seem to be a known issue. 

Thanks !

**Comment by dwsteele** [comment] 2020-09-18 18:51
Could you run this again with `--log-level-console=debug` so we can get more detail on that stack trace?

Then try adding `--no-resume` to the backup command and see if that works. Hopefully that will get you going again.

**Comment by dwsteele** [comment] 2020-09-18 19:33
OK -- I see you've already resolved this. We'll have a look and see if we can track it down.

**Comment by vadius45** [comment] 2020-09-30 16:36
Hi, 
I do have a debug file but my enterprise proxy settings do not allow me to upload it, and it's too large to be split in chunks here. I am still looking for a legit way to push the file to github ...
As far as I can see, we find DEBUG and DETAIL messages, no obvious error until the ASSERT block at the end

**Comment by dwsteele** [comment] 2020-10-05 20:13
Can you just provide the last ~100 lines of the log? Might be enough to figure out what is going on.

**Comment by dwsteele** [comment] 2021-03-30 19:57
Since I've been unable to reproduce this and there's no more information available I'll have to close it. It seems like a bug but without a repro there's not much to be done.

**Closed by dwsteele** 2021-03-30 19:57 UTC
Labels: question
